grafana/oncall

- docs/sources/open-source.md
not sure if this should link to dev or main branch but the original url here was a 404
> fix 404 on link to helm chart

- docker-compose.yml
- Remove setting for celery to exit
- Only bind required ports keep others internal
> Tweak docker-compose

- docs/sources/chat-options/configure-teams.md
add microsoft teams doc to support integration release
> Add MS teams doc

- engine/apps/public_api/serializers/integrations.py
Context: https://raintank-corp.slack.com/archives/CRUKW54N5/p1656946147548309
> Add possibility to modify default route on integration create

- engine/apps/twilioapp/twilio_client.py
Fix https://github.com/grafana/oncall/issues/145
> Fix phone notifications for oss

- docs/sources/integrations/create-custom-templates.md
- engine/common/jinja_templater/filters.py
- engine/common/jinja_templater/jinja_template_env.py
- engine/common/tests/test_regex_replace.py
I've created this PR to outline the change proposed in #226. This is only intended to help convey my understanding of what would need to change in code.
If this is something the maintainers are willing to support I can add the required unit tests and documentation updates.
> support regex_replace()

- helm/oncall/templates/engine/service-external.yaml
- helm/oncall/values.yaml
add ability to specify annotations for external service
> [helm] enable annotations for external service

- grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
> Add configured URLs details to plugin config page

- grafana-plugin/src/img/grafanaGlobalStyles.css
Fix for bug where oncall becones blank on narrow window
> 260-oncall-narrow-fix

- engine/apps/api/views/schedule.py
Argument name was clashing with timezone from django.utils
> Fix timezone naming clash

- engine/apps/api/views/maintenance.py
Resolves https://github.com/grafana/oncall/issues/183
> Show only maintenances for current team

- engine/apps/integrations/metadata/heartbeat/_heartbeat_text_creator.py
- engine/apps/integrations/mixins/browsable_instruction_mixin.py
- engine/apps/integrations/views.py
- engine/apps/oss_installation/cloud_heartbeat.py
- engine/apps/oss_installation/models/cloud_connector.py
- engine/apps/telegram/client.py
- engine/apps/twilioapp/models/phone_call.py
- engine/apps/twilioapp/models/sms_message.py
- engine/common/api_helpers/utils.py
Make any URLs built from env vars tolerant of path prefix, and trailing/leading slashes
> Conform URLs

- engine/apps/twilioapp/views.py
Reverts grafana/oncall#293
Re-testing in dev.
> Revert "Revert fix for twilio path prefix, not working needs more testing"

- grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.module.css
- grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.tsx
- grafana-plugin/src/containers/AlertTemplatesFormContainer/AlertTemplatesFormContainer.tsx
- grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
- grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.module.css
- grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
- grafana-plugin/src/pages/integrations/Integrations.tsx
- URLs for tabs have been added
- Check for invalid autoresolving condition at settings tab has been added
- Link from Autoresolving select to autoresolving condition has been added
> Autoresolve condition select is linked with alert template tab

- docs/sources/open-source.md
- engine/apps/slack/scenarios/resolution_note.py
This PR fixes the bug when resolution note was not able to be added from the context menu in Slack.
> Fix resolution notes bug

- engine/apps/social_auth/backends.py
> Fix spelling of "lose"

- engine/apps/auth_token/auth.py
Handle change to header introduced by:
https://github.com/grafana/grafana/pull/53343
> Tolerate UserId/UserID in X-Grafana-Context header

- engine/settings/base.py
- engine/settings/prod_without_db.py
For https://github.com/grafana/oncall-private/issues/1265
> Make STATIC_URL configurable from env

- engine/apps/api/tests/test_schedules.py
- engine/apps/schedules/models/custom_on_call_shift.py
- engine/apps/schedules/tests/test_custom_on_call_shift.py
Update generating ical for on-call shifts with respect to `rotation_start`
> Update generating ical for on-call shifts

- .drone.yml
Moving step to tag, looks like the plugin we use (plugins/github-release) does not work if it is on promote.
> Move step to publish plugin in github to tag

- docker-compose-developer-pg.yml
- docker-compose-developer.yml
Track grafana:main instead of pinned version
> Change condition so doesn't get stuck during startup. 

- engine/apps/base/models/live_setting.py
- grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
- grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
- grafana-plugin/src/containers/UserSettings/parts/tabs/TelegramInfo/TelegramInfo.tsx
- grafana-plugin/src/pages/migration-tool/MigrationTool.tsx
Fix for #351 
Changes:
- External links open in a new tab
> 351 - Open external links in new tab

- engine/apps/api/serializers/alert.py
- engine/apps/api/urls.py
- engine/apps/api/views/alerts.py
Backend for the https://github.com/grafana/oncall/issues/63
> Add alert detail view

- docs/sources/chat-options/configure-telegram.md
- docs/sources/open-source.md
- grafana-plugin/src/containers/TelegramIntegrationButton/TelegramIntegrationButton.tsx
https://github.com/grafana/oncall/issues/284
> Telegram docs/instructions update

- .drone.yml
> Add Drone step for pushing linux/arm64 image to DockerHub

- engine/apps/api/tests/test_user.py
- engine/apps/api/views/user.py
- grafana-plugin/src/containers/UserSettings/parts/connectors/SlackConnector.tsx
- grafana-plugin/src/models/user/user.ts
> Add unlink slack account option to profile

- engine/apps/alerts/tasks/notify_group.py
Check notification_policies before accessing
> Check notification policies

- engine/apps/schedules/models/custom_on_call_shift.py
- engine/apps/schedules/tests/test_custom_on_call_shift.py
Revert changes in events start date calculation, fix bug with getting wrong events start date
> Fix events start date calculation

- engine/apps/api/serializers/organization.py
- grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
- Remove version mismatch warning generation on backend side
- Make version mismatch warning banner closeable
> Improve version mismatch warning

- tools/pagerduty-migrator/migrator/resources/integrations.py
Fixes https://github.com/grafana/oncall/issues/377.
> Handle vendor = None for pagerduty migrator

- engine/apps/alerts/tasks/notify_ical_schedule_shift.py
- engine/apps/schedules/ical_utils.py
- engine/apps/schedules/tasks/refresh_ical_files.py
Fix ical comparision 
Co-authored-by: Julia <ferril.darkdiver@gmail.com>
> New ical comparision func (#480)

- grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
Fix for [#1299](https://github.com/grafana/oncall-private/issues/1299)
> 1299 - Hide grafana url if undefined on plugin config

- grafana-plugin/src/plugin.json
> 336 - Mismatch between plugin and tabs order

- engine/apps/public_api/serializers/schedules_calendar.py
- engine/apps/public_api/tests/test_schedules.py
Issue reported via support escalation
> Fix shifts/schedule teams validation on schedule creation

- engine/apps/user_management/sync.py
Fix log message not displaying primary key for organization being deleted.
> Fix log message 

- grafana-plugin/src/components/SourceCode/SourceCode.module.scss
- grafana-plugin/src/components/SourceCode/SourceCode.tsx
- grafana-plugin/src/containers/ApiTokenSettings/ApiTokenForm.module.css
- grafana-plugin/src/containers/ApiTokenSettings/ApiTokenForm.tsx
- grafana-plugin/src/containers/ApiTokenSettings/ApiTokenSettings.tsx
> 135 - token form

- engine/apps/alerts/models/alert_group.py
Avoid OR queries when filtering root vs dependent alert groups, switching to split queries/updates instead.
> Rework queries for alert groups bulk actions

- docker-compose-developer-pg.yml
- docker-compose-developer.yml
- docker-compose.yml
Update docker-comose version to 3.8 and use proper keys for memory and cpu limits.
Also use an [extension field](https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields) for oncall environment.
> Update docker-compose version to 3.8

- engine/apps/alerts/tasks/notify_ical_schedule_shift.py
- engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
Fixes https://github.com/grafana/oncall/issues/576
> Update slack lookup days when checking for next shift

- tools/pagerduty-migrator/scripts/README.md
- tools/pagerduty-migrator/scripts/add_users_pagerduty_to_grafana.py
* Added script to import users from pagerduty to grafana
* Added readme to make using the script easier
> Pagerduty migrator/add scripts

- helm/oncall/templates/celery/_deployment.tpl
- helm/oncall/values.yaml
For #570
Updated healthcheck with Celery 5.0 params. Made celery healthcheck configurable via Helm values.
> Fix helm celery healthcheck

- grafana-plugin/src/containers/IncidentsFilters/IncidentsFilters.tsx
- grafana-plugin/src/models/alertgroup/alertgroup.ts
- grafana-plugin/src/pages/incidents/Incidents.tsx
Affects the following issues:
#504 
#297
> 504 - reload incidents every 15s

- .github/pull_request_template.md
Add a template for pull requests to give reminders for updating the changelog.
Checklist is not meant to block reviews just provider more info to reviewers.
> Add simple pull request template

- .github/workflows/ci.yml
- engine/Dockerfile
Add docker-build step to workflows to make a simple test that the docker build is working, previously this check was only being done in drone.
**Checklist**
> Add step to check docker build

- helm/oncall/Chart.yaml
> Bump oncall backend version

- engine/apps/schedules/ical_utils.py
- engine/apps/schedules/tests/test_ical_utils.py
- engine/apps/user_management/apps.py
- engine/apps/user_management/tests/test_user.py
> Update ical event/user email matching to be case-insensitive

- engine/apps/alerts/models/alert_receive_channel.py
- engine/apps/alerts/tests/test_alert_receiver_channel.py
> Handle multiple general team manual integrations available

- docs/sources/alert-behavior/alert-templates/index.md
- docs/sources/alert-behavior/outgoing-webhooks/index.md
- docs/sources/get-started/_index.md
- docs/sources/integrations/available-integrations/configure-alertmanager/index.md
- docs/sources/integrations/available-integrations/configure-grafana-alerting/index.md
- docs/sources/integrations/available-integrations/configure-webhook/index.md
- docs/sources/integrations/available-integrations/configure-zabbix/index.md
- docs/sources/integrations/chatops-integrations/_index.md
- docs/sources/integrations/chatops-integrations/configure-slack/index.md
- docs/sources/integrations/chatops-integrations/configure-teams/index.md
- docs/sources/integrations/chatops-integrations/configure-telegram/index.md
Rewrites absolute aliases to be relative, ignoring the absolute alias that refers to the current page location.
> Rewrite absolute aliases to be relative

- engine/apps/alerts/tasks/notify_group.py
Fix error where notify group is trying to get users from undefined group
**Checklist**
> Add check for usergroup to notify group task

- CHANGELOG.md
- grafana-plugin/CHANGELOG.md
> Update changelog for v1.0.43

- CHANGELOG.md
- engine/apps/api/tests/test_custom_button.py
- engine/apps/api/views/custom_button.py
- grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
- remove POST /api/internal/v1/custom_buttons/{id}/action
- bug fixes
> release v1.0.46

- engine/apps/api/tests/test_schedules.py
- engine/apps/api/views/schedule.py
Change schedules endpoint to filter items by their numeric type
> Update schedules endpoint to filter by numeric type

- grafana-plugin/src/pages/chat-ops/parts/tabs/SlackSettings/SlackSettings.tsx
- grafana-plugin/src/pages/chat-ops/parts/tabs/TelegramSettings/TelegramSettings.tsx
> Chatops livesettings fix

- grafana-plugin/src/pages/chat-ops/parts/tabs/TelegramSettings/TelegramSettings.module.css
- grafana-plugin/src/pages/chat-ops/parts/tabs/TelegramSettings/TelegramSettings.tsx
> navigation css fix

- grafana-plugin/src/pages/livesettings/LiveSettingsPage.tsx
Fix bug
https://github.com/grafana/oncall/issues/753
**Checklist**
> fix live settings caching columns render

- DEVELOPER.md
- README.md
- engine/config_integrations/README.md
- engine/config_integrations/zabbix.py
- engine/settings/base.py
Readme about how to add Integrations and Zabbix Integration
> Readme about how to add Integrations and Zabbix Integration

- engine/engine/middlewares.py
Request already contained user, add user id and org id to request log so we can better understand the data when troubleshooting errors or slow performance.
**Checklist**
> Add user and org id to log to make troubleshooting easier

- CHANGELOG.md
- docs/sources/chat-options/configure-telegram.md
- docs/sources/integrations/available-integrations/add-alertmanager.md
- docs/sources/integrations/available-integrations/add-grafana-alerting.md
- docs/sources/integrations/available-integrations/add-zabbix.md
- docs/sources/oncall-api-reference/users.md
- docs/sources/permissions/_index.md
Updates documentation, and `CHANGELOG.md`, to reflect latest RBAC changes.
`grafana/oncall-private` [#1381](https://github.com/grafana/oncall-private/issues/1381)
**Checklist**
RBAC PRs (once approved, all of these PRs will be merged into the `jorlando/rbac` branch and that branch will then be merged to `dev`):
- #685 
- #635 
- #634 
- #687 
- #699
> [RBAC]: update changelog and documentation

- CHANGELOG.md
- engine/apps/alerts/models/alert_receive_channel.py
- engine/apps/alerts/models/custom_button.py
- engine/apps/api/serializers/custom_button.py
- engine/apps/public_api/serializers/action.py
> Use common environment for templates

- helm/oncall/Chart.yaml
- helm/oncall/values.yaml
Fix for https://github.com/grafana/oncall/issues/791
**Checklist**
> Fix helm values.yaml, bump helm version

- engine/apps/user_management/middlewares.py
Testing fixes for headers inside cloud gateways and proxies.
**Checklist**
> Fix organization rerouting headers

- grafana-plugin/src/GrafanaPluginRootPage.tsx
- grafana-plugin/src/pages/schedule/Schedule.tsx
- grafana-plugin/src/pages/schedules/Schedules.tsx
- grafana-plugin/src/utils/hooks.tsx
- fix schedules deletion,
- remove support for new schedules feature flag
**Checklist**
> Fix schedules deletion, remove new schedules feature flag support

- Makefile
- dev/README.md
Add a Makefile command for rebuilding docker images and `exec`'ing into the engine pod.
> Add Makefile command for rebuilding images

- engine/apps/public_api/serializers/routes.py
- engine/apps/public_api/tests/test_routes.py
- engine/apps/public_api/views/routes.py
- engine/common/api_helpers/mixins.py
https://github.com/grafana/oncall-private/issues/1466
**Checklist**
> Add additional validation for route's position field

- engine/apps/slack/views.py
Add warning pop-up on action in slack if user is not connected to OnCall
https://github.com/grafana/oncall/issues/835
> Fix warning pop-up on action in slack

- grafana-plugin/src/components/SchedulesFilters_NEW/SchedulesFilters.tsx
- grafana-plugin/src/components/UserTimezoneSelect/UserTimezoneSelect.module.css
- grafana-plugin/src/components/UserTimezoneSelect/UserTimezoneSelect.tsx
- grafana-plugin/src/containers/RotationForm/RotationForm.module.css
- grafana-plugin/src/containers/Rotations/Rotations.tsx
- grafana-plugin/src/containers/Rotations/ScheduleOverrides.tsx
- grafana-plugin/src/models/user/user.ts
- grafana-plugin/src/pages/schedule/Schedule.tsx
- grafana-plugin/src/pages/schedules/Schedules.module.css
Fix schedules bugs fund after first release
https://github.com/grafana/oncall/issues/532
**Checklist**
> Web schedules minor bug fixes after initial release

- engine/apps/user_management/middlewares.py
Only send headers we actually need when forwarding to another oncall backend.
**Checklist**
> Organization moved headers

- dev/README.md
See https://github.com/grafana/oncall/issues/846
> Note that Docker Compose >=v2.10 is required

- Makefile
- dev/README.md
See https://github.com/grafana/oncall/pull/868
> Create generic Make command to run Django `manage.py`

- engine/apps/schedules/models/custom_on_call_shift.py
copy of https://github.com/grafana/oncall/pull/882
making hotfix to main
**Checklist**
> Fix web oncall calendars not loading

- CHANGELOG.md
- grafana-plugin/src/state/plugin/__snapshots__/plugin.test.ts.snap
- grafana-plugin/src/state/plugin/index.ts
- grafana-plugin/src/state/plugin/plugin.test.ts
- grafana-plugin/src/state/rootBaseStore/index.ts
- grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
fix issue where frontend would not properly handle scenario where Grafana API token was not yet available/valid
> [Hotfix] UI not handling invalid grafana tokens properly

- engine/celery_with_exporter.sh
> Add celery parameters to disable gossip, heartbeat, mingle

- dev/README.md
- engine/celery_with_exporter.sh
> Add flag to debug logs

- engine/engine/celery.py
- engine/requirements.txt
- engine/settings/base.py
> Add celery profiling

- engine/apps/schedules/models/on_call_schedule.py
- engine/apps/schedules/tests/test_on_call_schedule.py
Fix ical/TF schedules to correctly render overrides with different priority levels
> Update final schedule to consider priority level for overrides

- CHANGELOG.md
- engine/apps/alerts/models/alert_group.py
- engine/apps/public_api/tests/test_incidents.py
**Public API response**
**Internal API response**
> add permalinks.web attribute to alert group internal/public api response

- grafana-plugin/jest.config.js
- grafana-plugin/src/containers/MobileAppVerification/MobileAppVerification.module.scss
- grafana-plugin/src/containers/MobileAppVerification/MobileAppVerification.test.tsx
- grafana-plugin/src/containers/MobileAppVerification/MobileAppVerification.tsx
- grafana-plugin/src/containers/MobileAppVerification/__snapshots__/MobileAppVerification.test.tsx.snap
- grafana-plugin/src/containers/MobileAppVerification/parts/QRCode/QRCode.test.tsx
- grafana-plugin/src/containers/MobileAppVerification/parts/QRCode/QRCode.tsx
- grafana-plugin/src/containers/UserSettings/UserSettings.tsx
- Added auto refresh on QR (every 50s) + blur/loading display while we fetch a new QR
[#1508](https://github.com/grafana/oncall-private/issues/1508)
> Mobile app screen tweaks

- engine/apps/grafana_plugin/helpers/client.py
Remove unused parameter from gcom call
> Remove unused parameter from gcom call

- engine/apps/grafana_plugin/helpers/gcom.py
this field will be addressed in a subsequent sync call it is not necessary here
> remove is_rbac_permissions_enabled logic from check_gcom_permission function

- tools/pagerduty-migrator/migrator/__main__.py
Issues: https://github.com/grafana/oncall/issues/990
> Increasing library default timeout

- grafana-plugin/src/pages/incident/Incident.tsx
Small wording fix (Incident -> AG)
> Small wording fix (Incident -> AG)

- grafana-plugin/src/containers/MobileAppVerification/MobileAppVerification.module.scss
- grafana-plugin/src/containers/MobileAppVerification/MobileAppVerification.tsx
- grafana-plugin/src/containers/MobileAppVerification/__snapshots__/MobileAppVerification.test.tsx.snap
- Adds white border around the QR code + small margin below
> add qr code class with white background

- engine/apps/telegram/renderers/message.py
> Don't render logs for too big telegram dm

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- tools/pagerduty-migrator/migrator/report.py
- tools/pagerduty-migrator/requirements.txt
- Add PD migrator related hooks to `.pre-commit-config.yaml`
- Add Github Actions step for running PD migrator tests
> Add PD migrator lint & test steps to CI

- tools/pagerduty-migrator/migrator/resources/users.py
- tools/pagerduty-migrator/migrator/tests/test_matching.py
- tools/pagerduty-migrator/migrator/tests/test_user_matching.py
https://github.com/grafana/oncall/issues/1025
> Make user matching by email case-insensitive for PD migrator

- engine/requirements.txt
This change fixes the following issue:
```bash
Traceback (most recent call last):
File "/etc/app/manage.py", line 15, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
output = self.handle(*args, **options)
File …
```
> bump crptography version

- engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
Make sure slack rendered alert group truncates title block to keep it below the Slack max block size
> Truncate slack alert group title block below max size

- CHANGELOG.md
- engine/Dockerfile
- engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
- engine/apps/api/tests/test_schedules.py
- engine/apps/schedules/models/custom_on_call_shift.py
- engine/apps/schedules/tests/test_custom_on_call_shift.py
- engine/requirements.txt
> merge dev to main

- engine/requirements.txt
> Add uwsgidecorators to requirements.txt

- tools/pagerduty-migrator/migrator/report.py
Resolves https://github.com/grafana/oncall/issues/1066
> Fix "existing schedule will be deleted" message for PD migrator

- README.md
> Revert "testing branch merge strategy"

- docker-compose-developer.yml
- engine/apps/alerts/incident_appearance/renderers/telegram_renderer.py
- engine/apps/mobile_app/alert_rendering.py
- engine/apps/mobile_app/tasks.py
- engine/apps/telegram/tests/test_message_renderer.py
Updates the mobile app push notification text to:
**iOS**
```
title: New Alert / New Critical Alert
subtitle:  #324134 KubePodCrashLooping via Amixr Prod AlertManager
body: Status: firing
```
**Android**
```
title: New Alert / New Critical Alert
body: #324134 KubePodCrashLooping via Amixr Prod AlertManager
Status: firing
```
> update mobile app push notification text + make telegram alert verbage consistent ("Firing" instead of "Alerting")

- grafana-plugin/src/pages/schedule/Schedule.tsx
> Restore schedule export option for all types

- .github/workflows/helm_release.yml
- .github/workflows/issue_commands.yml
Separate tokens for GH actions with minimal scope
> Update tokens used by GH Actions

- CHANGELOG.md
> v1.1.15 CHANGELOG

- engine/apps/mobile_app/fcm_relay.py
- engine/apps/mobile_app/tasks.py
This PR changes how `FCMRelayView` handles push notifications from OSS instances, also changing how the mobile app backend sends push notifications.
> Re-implement FCM relay after introducing firebase

- grafana-plugin/src/containers/UserSettings/parts/tabs/SlackTab/SlackTab.tsx
Typo fix in slack connect on user's profile
> Fix typo in slack connect

- CHANGELOG.md
- engine/apps/grafana_plugin/helpers/client.py
- engine/apps/grafana_plugin/tests/test_gcom_api_client.py
- engine/apps/grafana_plugin/tests/test_grafana_api_client.py
- engine/apps/mobile_app/fcm_relay.py
- engine/apps/mobile_app/tasks.py
- engine/apps/user_management/models/organization.py
- engine/apps/user_management/sync.py
- engine/apps/user_management/tests/test_sync.py
- grafana-plugin/src/containers/UserSettings/parts/tabs/SlackTab/SlackTab.tsx
- grafana-plugin/src/plugin.json
- helm/oncall/Chart.yaml
- helm/oncall/README.md
- helm/oncall/values.yaml
> Dev to main

- .github/workflows/helm_release.yml
- helm/cr.yaml
Please See https://github.com/grafana/helm-charts/pull/2107
> Remove helm chart signing

- grafana-plugin/src/PluginPage.tsx
- grafana-plugin/src/img/grafanaGlobalStyles.css
- grafana-plugin/src/plugin/PluginSetup/PluginSetup.test.tsx
- grafana-plugin/src/plugin/PluginSetup/__snapshots__/PluginSetup.test.tsx.snap
- grafana-plugin/src/plugin/PluginSetup/index.tsx
#1096 - Show plugin loading inside PluginPage
> #1096 - Show loading inside PluginPage

- engine/apps/api/serializers/on_call_shifts.py
- engine/apps/api/tests/test_oncall_shift.py
Related to https://github.com/grafana/oncall-private/issues/1550
> Web schedules overrides are the higher priority level

- engine/apps/alerts/models/custom_button.py
Fix error where rendered_data was being used without being defined.
> Fix UnboundLocalError in webhooks

- engine/requirements.txt
- engine/settings/base.py
> Add pyroscope integration

- engine/Dockerfile
- engine/apps/api/views/alert_group.py
> Optimize alertgroups endpoint

- engine/apps/alerts/models/alert_group.py
> Optimize alert group filtering queries

- CHANGELOG.md
- engine/apps/api/views/alert_group.py
- grafana-plugin/src/models/alertgroup/alertgroup.ts
> Remove resolved and acknowledged filters as we switched to status

- engine/apps/alerts/paging.py
- engine/apps/alerts/tests/test_paging.py
- engine/apps/slack/scenarios/paging.py
- engine/apps/slack/tests/test_scenario_steps/test_paging.py
> Add schedules support for slack direct paging

- grafana-plugin/src/plugin.json
Change copy for description based on #1003
> Plugin description copy

- CHANGELOG.md
- grafana-plugin/src/PluginPage.tsx
- grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
- grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
- grafana-plugin/src/navbar/Header/Header.tsx
- grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
> Fix on teams switch NPE

- CHANGELOG.md
- engine/apps/api/serializers/alert_group.py
> Fix bug with root/dependant alert groups list api endpoint

- engine/apps/public_api/serializers/incidents.py
- engine/apps/public_api/views/incidents.py
> Revert count query in alert groups internal api endpoint

- tools/pagerduty-migrator/migrator/oncall_api_client.py
Improves PagerDuty migrator error traceback when getting HTTP 400 errors from OnCall public API.
> Improve PD migrator traceback on HTTP 400

- CHANGELOG.md
- docs/sources/mobile-app/_index.md
- grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
- grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/__snapshots__/DownloadIcons.test.tsx.snap
- grafana-plugin/src/containers/MobileAppConnection/parts/DownloadIcons/index.tsx
Adds the IPhone mobile app link to web UI.
> Add App Store link to web UI

- .github/ISSUE_TEMPLATE/issue-template.md
- CHANGELOG.md
- engine/apps/alerts/models/alert_group.py
- engine/common/oncall_gateway/oncall_gateway_client.py
- Fixed too long declare incident link in Slack
> Release 1.1.25

- grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
> Update phone verification error message

- .github/dependabot.yml
- CHANGELOG.md
- engine/apps/api/serializers/user.py
- engine/apps/api/tests/test_user.py
- engine/apps/api/views/user.py
- engine/requirements.txt
- engine/settings/base.py
- grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
- grafana-plugin/src/models/user/user.ts
- grafana-plugin/src/network/index.ts
- grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
- grafana-plugin/src/style/global.css
- grafana-plugin/src/utils/consts.ts
- grafana-plugin/src/utils/loadJs.ts
Adds reCAPTCHA validation to the get mobile verification code endpoint
> Add Google reCAPTCHA for mobile app phone verification

- engine/apps/schedules/models/on_call_schedule.py
- engine/apps/schedules/tests/test_on_call_schedule.py
> Revert "Revert "Rework schedules cached ical file values""

- CHANGELOG.md
- grafana-plugin/src/containers/UserSettings/parts/connectors/ICalConnector.tsx
https://www.loom.com/share/c6da9a51786a483999b19eba94c7e2f5
> fixed UI permission related bug where Editors could not export their user iCal link

- CHANGELOG.md
- engine/apps/schedules/models/custom_on_call_shift.py
- engine/apps/schedules/tests/test_custom_on_call_shift.py
Fixes https://github.com/grafana/oncall-private/issues/1648
> Use UTC instead of Etc/UTC when passing tz to dateutil rrule

- grafana-plugin/src/containers/UserSettings/parts/tabs/CloudPhoneSettings/CloudPhoneSettings.tsx
- grafana-plugin/src/pages/settings/tabs/Cloud/CloudPage.tsx
Fix message on Phone Verification tab.
> Fix wording for cloud notifications

- engine/apps/integrations/templates/heartbeat_link.html
- engine/apps/integrations/templates/integration_link.html
Adds integrity hash for scripts loaded from CDN's.
> Chore: add integrity hash to templates

- engine/apps/api/views/alert_group.py
Rework query to make it more efficient.
> Rework alert group mine filter query

- grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx
Fix for the crash of Chat-ops page
https://github.com/grafana/oncall/issues/1467
> Chat-ops fix

- CHANGELOG.md
- engine/apps/api/tests/test_alert_group.py
- engine/apps/api/views/alert_group.py
Fixes https://github.com/grafana/oncall-private/issues/1673
> Fix involved users filter, add missing test

- engine/apps/email/tests/test_notify_user.py
Adds a simple test for https://github.com/grafana/oncall/pull/1499
> Add test for newlines in email subject

- grafana-plugin/src/pages/integrations/Integrations.tsx
> Quickfix for integrations

- docs/sources/configure-user-settings/_index.md
RBAC for OnCall will be GA with Grafana 9.4 release.
Update [this doc](https://grafana.com/docs/oncall/latest/configure-user-settings/) to include details about RBAC for OnCall and link to RBAC-specific docs.
Issue #1399
> Add RBAC guidance to users and teams documentation 

- tools/pagerduty-migrator/migrator/resources/rulesets.py
Update PD migrator to create routes with no escalation chain selected for event rules referencing deleted services
> PD migrator: ignore deleted services in event rules

- CHANGELOG.md
- grafana-plugin/src/containers/HeartbeatModal/HeartbeatForm.tsx
> update integration heartbeat description to use 'alert group' instead of 'incident'

- grafana-plugin/integration-tests/integrations/uniqueIntegrationNames.test.ts
- grafana-plugin/integration-tests/utils/integrations.ts
- grafana-plugin/src/components/Text/Text.tsx
- grafana-plugin/src/containers/CreateAlertReceiveChannelContainer/CreateAlertReceiveChannelContainer.tsx
related to https://github.com/grafana/oncall-private/pull/1692
> add e2e test that we have unique integrations

- docker-compose-developer.yml
> Add new grafana topnav menu to developer docker-compose

- engine/apps/user_management/models/user.py
- grafana-plugin/src/containers/TeamsList/TeamsList.tsx
> Fix teams duplication and user list permission control

- engine/apps/api/views/team.py
> Add rbac to teams endpoint

- engine/apps/api/views/alert_group.py
- engine/apps/api/views/alert_receive_channel.py
- engine/apps/api/views/alert_receive_channel_template.py
- engine/apps/api/views/channel_filter.py
- engine/apps/api/views/custom_button.py
- engine/apps/api/views/escalation_chain.py
- engine/apps/api/views/escalation_policy.py
- engine/apps/api/views/integration_heartbeat.py
- engine/apps/api/views/on_call_shifts.py
- engine/apps/api/views/resolution_note.py
- engine/apps/api/views/schedule.py
- engine/apps/api/views/webhooks.py
> Fix resource duplication caused by available_teams_lookup_args

- grafana-plugin/src/containers/TeamName/TeamName.tsx
> Do not show team name if it doesn't exist in store

- engine/apps/api/views/webhooks.py
- grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.ts
- grafana-plugin/src/models/outgoing_webhook_2/outgoing_webhook_2.ts
- grafana-plugin/src/pages/outgoing_webhooks_2/OutgoingWebhooks2.tsx
> Add filters to outgoing webhooks 2

- docs/sources/configure-user-settings/_index.md
> Update team management docs

- engine/wait_for_test_mysql_start.sh
> Fix failing ci task

- CHANGELOG.md
- engine/apps/slack/scenarios/resolution_note.py
> Disable mentions when resolution note is created

- grafana-plugin/src/components/Policy/EscalationPolicy.tsx
Restore escalation policy importance explanations
> Restore escalation policy importance explanations

- docs/sources/configure-user-settings/_index.md
- changes `Alerts & incidents` to `Alerts & IRM` in the docs
> Docs: change 'Alerts & incidents' to 'Alerts & IRM' in the docs

- engine/apps/webhooks/tasks/trigger_webhook.py
- engine/apps/webhooks/tests/test_trigger_webhook.py
- engine/apps/webhooks/utils.py
Enable additional context data when building webhooks payload.
> Add more context data to webhook templating

- CHANGELOG.md
- grafana-plugin/src/components/GForm/GForm.tsx
Fixed `onChange` handler within `GForm` component
> Fix a bug in GForm

- README.md
- dev/README.md
- engine/apps/api/views/user_notification_policy.py
Add mobile app authentication for `notification_policies` endpoint
> Add mobile app auth for `notification_policies` endpoint

- grafana-plugin/src/containers/AlertRules/AlertRules.tsx
It was a bug https://raintank-corp.slack.com/archives/C0415S5L76Y/p1681287849538729
> creating escalation chain from integration fix

- tools/pagerduty-migrator/migrator/config.py
- tools/pagerduty-migrator/migrator/report.py
- tools/pagerduty-migrator/migrator/resources/integrations.py
https://github.com/grafana/oncall/issues/1718
> Migrate unsupported integrations to webhook

- engine/apps/api/serializers/alert_receive_channel.py
> Fix templates bug

- CHANGELOG.md
- engine/apps/api/tests/test_schedules.py
- engine/apps/api/views/schedule.py
- engine/apps/schedules/models/on_call_schedule.py
- engine/apps/schedules/tests/test_on_call_schedule.py
- grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.tsx
- grafana-plugin/src/components/SchedulesFilters/SchedulesFilters.types.ts
- grafana-plugin/src/models/schedule/schedule.ts
- grafana-plugin/src/pages/schedules/Schedules.tsx
> Add mine filter to schedules listing

- README.md
> Make screenshots bigger in README.md

- engine/apps/api/views/alert_group.py
> Optimise alert groups private api endpoint

- grafana-plugin/src/components/AlertTemplates/AlertTemplatesForm.config.ts
- grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts
- grafana-plugin/src/components/CheatSheet/CheatSheet.module.css
- grafana-plugin/src/components/CheatSheet/CheatSheet.tsx
- grafana-plugin/src/components/MonacoJinja2Editor/MonacoJinja2Editor.tsx
- grafana-plugin/src/components/NewScheduleSelector/NewScheduleSelector.tsx
- grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.css
- grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
- grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx
- grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
- grafana-plugin/src/models/alertgroup/alertgroup.ts
- grafana-plugin/src/pages/integration_2/Integration2.tsx
- Drawer for editing templates
- Saving
- Checking the result using latest endpoints with payload 
- cheatsheets
- Additional parameters with conditional templates
- Use Custom payload
> Edit template modal

- CHANGELOG.md
- engine/apps/schedules/ical_utils.py
Update iCal schedule and personal exports to use final schedule events.
> Enable final schedule exports

- CHANGELOG.md
- engine/apps/api/serializers/user.py
- engine/apps/api/tests/test_schedules.py
- engine/apps/api/views/schedule.py
- engine/apps/schedules/models/on_call_schedule.py
- engine/apps/schedules/tests/test_on_call_schedule.py
Related to https://github.com/grafana/oncall/issues/1820.
> Rework schedule related users, add endpoint

- grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.module.scss
- grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.tsx
- grafana-plugin/src/components/Policy/EscalationPolicy.tsx
- grafana-plugin/src/components/Policy/NotificationPolicy.tsx
- grafana-plugin/src/components/Timeline/TimelineItem.tsx
- grafana-plugin/src/containers/AlertRules/parts/index.tsx
- grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
- grafana-plugin/src/containers/GSelect/GSelect.module.css
- grafana-plugin/src/containers/GSelect/GSelect.module.scss
- grafana-plugin/src/containers/GSelect/GSelect.tsx
- grafana-plugin/src/containers/PersonalNotificationSettings/PersonalNotificationSettings.tsx
- grafana-plugin/src/pages/integration_2/Integration2.config.ts
- grafana-plugin/src/pages/integration_2/Integration2.helper.ts
- grafana-plugin/src/pages/integration_2/Integration2.module.scss
- grafana-plugin/src/pages/integration_2/Integration2.tsx
- grafana-plugin/src/pages/integration_2/IntegrationBlock.module.scss
- grafana-plugin/src/pages/integration_2/IntegrationBlock.tsx
- grafana-plugin/src/pages/integration_2/IntegrationBlockItem.module.scss
- grafana-plugin/src/pages/integration_2/IntegrationBlockItem.tsx
- grafana-plugin/src/pages/integration_2/IntegrationRouteDisplay.module.scss
- grafana-plugin/src/pages/integration_2/IntegrationRouteDisplay.tsx
- grafana-plugin/src/pages/integration_2/IntegrationTemplateBlock.tsx
> Merge routing changes to main branch grouping-templating-frontend

- engine/apps/slack/models/slack_user_identity.py
- engine/apps/slack/scenarios/invited_to_channel.py
- engine/apps/slack/scenarios/notified_user_not_in_channel.py
- engine/apps/slack/views.py
Handles case when user press "Go to alert group" button in DM with bot.
> Handle invitation button press

- grafana-plugin/src/components/GBlock/Block.tsx
- grafana-plugin/src/components/Tag/Tag.module.css
- grafana-plugin/src/pages/incident/Incident.module.scss
- grafana-plugin/src/pages/incident/Incident.tsx
- grafana-plugin/src/pages/incidents/parts/IncidentDropdown.module.scss
Minor UI Tweaks after releasing the grouping&templating changes
> Minor tweaks to Tag component

- CHANGELOG.md
- engine/apps/grafana_plugin/helpers/client.py
- engine/apps/grafana_plugin/tests/test_gcom_api_client.py
> properly parse grafana cloud feature toggles

- grafana-plugin/src/containers/IntegrationForm/IntegrationForm.config.ts
- grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
- grafana-plugin/src/pages/integration_2/Integration2.tsx
> Use the correct description

- CHANGELOG.md
- engine/apps/api/tests/test_maintenance.py
- engine/apps/api/views/maintenance.py
Related to https://github.com/grafana/support-escalations/issues/5862
> Fix teams filter related issue setting maintenance mode

- grafana-plugin/src/components/NewScheduleSelector/NewScheduleSelector.tsx
> fix-new-schedule-creation

- docs/sources/integrations/available-integrations/configure-appdynamics/index.md
- engine/apps/integrations/templates/html/integration_appdynamics.html
- grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.config.ts
Adds docs & logo for AppDynamics integration. 
Main PR in private repo: https://github.com/grafana/oncall-private/pull/1790.
https://github.com/grafana/oncall-private/issues/1621
- No changelog (AppDynamics integration will be only available in cloud)
> Add docs & logo for AppDynamics integration

- grafana-plugin/src/containers/IntegrationForm/IntegrationForm2.tsx
- grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
- grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
- grafana-plugin/src/pages/integration_2/Integration2.tsx
Fix for creating Integration
After creating Integration we land on Integration page, not a table
Added error notification for TemplateFoEdit obj to avoid crashing
Loading state for AlertGroup List
Small style fixes
> Fix for creating Integration

- engine/apps/api/serializers/alert_receive_channel.py
- engine/apps/public_api/serializers/integrations.py
- engine/config_integrations/alertmanager.py
- engine/config_integrations/formatted_webhook.py
> Allow null for short description in integrations api

- grafana-plugin/src/components/IntegrationCollapsibleTreeView/IntegrationCollapsibleTreeView.module.scss
- grafana-plugin/src/components/Tag/Tag.module.css
- grafana-plugin/src/pages/integration_2/CollapsedIntegrationRouteDisplay.module.scss
- grafana-plugin/src/pages/integration_2/CollapsedIntegrationRouteDisplay.tsx
- grafana-plugin/src/pages/integration_2/ExpandedIntegrationRouteDisplay.tsx
- grafana-plugin/src/pages/integration_2/Integration2.helper.ts
- grafana-plugin/src/pages/integration_2/Integration2.module.scss
- grafana-plugin/src/pages/integration_2/Integration2.tsx
- grafana-plugin/src/pages/integration_2/IntegrationBlockItem.module.scss
- grafana-plugin/src/pages/integration_2/IntegrationTemplateBlock.module.scss
- grafana-plugin/src/pages/integration_2/IntegrationTemplateBlock.tsx
- grafana-plugin/src/pages/integration_2/IntegrationTemplatesList.tsx
- Fixed Templates view
- Fixed main integration page view for smaller screens
- Show No Escalation Chain/ChatOps (Slack/Telegram for now, no MS teams yet)
> Templates tweaks

- grafana-plugin/src/pages/integration_2/Integration2.tsx
> Fixed delete integration copy

- engine/apps/twilioapp/gather.py
- engine/apps/twilioapp/status_callback.py
- engine/apps/twilioapp/views.py
> Improve twilio callback logging

- engine/apps/mobile_app/tasks.py
This log should line should have been removed as part of #2006
> Remove spammy log message for device not setup 2

- engine/apps/slack/views.py
In trying to solve https://github.com/grafana/oncall-private/issues/1836, it is very difficult to understand the root cause without seeing the event payload. This PR will log this out.
> update logging for slack interactive_api_endpoint

- .github/workflows/linting-and-tests.yml
- helm/oncall/.helmignore
- helm/oncall/templates/_env.tpl
- helm/oncall/tests/postgres_env_test.yaml
- helm/oncall/tests/postgres_password_env_test.yaml
- helm/oncall/values.yaml
Fixing some bugs with external Postgresql configuration.
Also I added some unit tests for helm chart using [helm-unittest](https://github.com/helm-unittest/helm-unittest). If it's not an appropriate tool, please suggest another, or I can remove that test. I added [this](https://github.com/marketplace/actions/helm-unit-tests) Github Action to run helm unit tests. 
closes #1727 
closes #1923
closes #1245
closes #845
> Fix bugs in helm chart with external postgresql configuration

- docs/sources/jinja2-templating/_index.md
- docs/sources/notify/phone-calls-sms/index.md
Answering customer's questions by updating docs.
> Answering customer's questions by updating docs.

- CHANGELOG.md
- grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
> add description to "Default channel for Slack notifications" UI dropdown

- grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
- grafana-plugin/src/pages/integration_2/Integration2.config.ts
- removed msteams usage from public
- removed check for chatops
> Templates&grouping changes

- grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
- grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
When Opening Template Editor, on first load Monaco editor height is 0
> fix for MonacoEditor height

- engine/Dockerfile
- engine/uwsgi.ini
> Add 413 for requests with content-length > 15Mb on uwsgi

- engine/apps/api/views/alert_group.py
> temporarily disable searching for alert groups

- docs/sources/integrations/_index.md
> fixing another broken reference for jinja2 templating

- grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.css
- grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.tsx
- grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.module.scss
- grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
- grafana-plugin/src/pages/integration_2/Integration2.module.scss
- grafana-plugin/src/pages/integration_2/Integration2.tsx
- grafana-plugin/src/pages/integrations_2/Integrations2.module.scss
- grafana-plugin/src/pages/integrations_2/Integrations2.tsx
UID has been added to Integrations table, Integration page and routes
> UID has been added to Integrations table, Integration page and routes

- grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
Fix issue when  phone code verification field not became active after verifying number via phone
> Fix phone code verification field

- grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
- grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
- grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
Fixes for search, for last alert payload and some design changes
> Fixes for search, for last alert payload and some design changes

- grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.module.css
- grafana-plugin/src/containers/EditRegexpRouteTemplateModal/EditRegexpRouteTemplateModal.tsx
- grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
- grafana-plugin/src/pages/integration_2/Integration2.tsx
- Wrong behaviour after saving Route template fix
- Add notification/error when try to save empty template for routes.
> fix for templates for routes

- engine/apps/api/serializers/alert_receive_channel.py
> Fix demo-payload

- grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
> Edit route hint

- engine/apps/phone_notifications/models/phone_call.py
- engine/apps/phone_notifications/models/sms.py
- engine/apps/phone_notifications/phone_provider.py
- engine/apps/phone_notifications/simple_phone_provider.py
> Better simple phone provider

- docs/sources/open-source/_index.md
Mentioning 
```
FEATURE_TELEGRAM_INTEGRATION_ENABLED=True
FEATURE_SLACK_INTEGRATION_ENABLED=True
```
Closing #1735
> Adding a note about OSS env vars to enable tg/slack features

- engine/apps/metrics_exporter/helpers.py
- engine/apps/metrics_exporter/tasks.py
Save only organizations with integrations in cache  for collecting metrics
> Save only organizations with integrations in cache 

- engine/apps/api/views/alert_receive_channel.py
> Fix integrations options order

- grafana-plugin/src/pages/integration_2/Integration2.tsx
- grafana-plugin/src/pages/integrations_2/Integrations2.tsx
> Add 'Edit templates' to dropdown, change wording

- engine/apps/api/serializers/channel_filter.py
> Add telegram details field

- engine/apps/schedules/models/custom_on_call_shift.py
- engine/apps/schedules/tests/test_custom_on_call_shift.py
Related to https://github.com/grafana/oncall/issues/2118#issuecomment-1592889257
> Update daily shifts by day to handle changed week start

- CHANGELOG.md
- engine/apps/alerts/models/alert_group.py
- engine/apps/alerts/tasks/resolve_alert_group_by_source_if_needed.py
- engine/apps/alerts/tests/test_alert_group.py
> Optmise autoresolve query

- engine/apps/api/serializers/alert_receive_channel.py
> Add inbound email field to private api

- engine/apps/metrics_exporter/tasks.py
Optimize getting response time for alert groups in calculation metrics task
> Optimize getting response time for alert groups

- grafana-plugin/src/components/UserTimezoneSelect/UserTimezoneSelect.tsx
- grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
- grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
- grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
- grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.types.ts
- grafana-plugin/src/pages/integration_2/Integration2.module.scss
- grafana-plugin/src/pages/integration_2/Integration2.tsx
- grafana-plugin/src/style/vars.css
- Fixed a few issues when using the light theme
- Show/Hide Escalation - Search Escalation - Reload Escalation (all fixes)
- Inbound Email show in http endpoint
- Allow opening the route template in collapsed state (added new button for it)
> Fixes for templates&grouping

- CHANGELOG.md
- docs/sources/insights-and-metrics/_index.md
> Metrics doc

- grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.scss
- grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.tsx
- grafana-plugin/src/containers/IntegrationContainers/CollapsedIntegrationRouteDisplay/CollapsedIntegrationRouteDisplay.tsx
- grafana-plugin/src/pages/integration/Integration.helper.ts
- grafana-plugin/src/pages/integration/Integration.tsx
- grafana-plugin/src/style/vars.css
> Added chatops fetch (for MSTeams) and changed styling to be compatible with global grafana styles in templates

- README.md
Fix the getting started guide error when enabling prometheus.
https://github.com/grafana/oncall/issues/2326
> [README]fix prometheus yml indentation error

- CHANGELOG.md
- engine/apps/mobile_app/tasks.py
- engine/apps/mobile_app/tests/test_your_going_oncall_notification.py
- engine/apps/user_management/models/user.py
> For "You're Going OnCall" push notifications, show shift times in the user's configured timezone, otherwise UTC

- CHANGELOG.md
- grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx
> Fix for #2357

- engine/apps/base/models/ordered_model.py
Make `OrderedModel.save()` respect additional arguments (e.g. `using`)
> Make `OrderedModel.save()` respect additional arguments

- CHANGELOG.md
- helm/oncall/templates/celery/_deployment.tpl
- helm/oncall/templates/engine/job-migrate.yaml
- helm/oncall/tests/__snapshot__/affinity_deployments_test.yaml.snap
- helm/oncall/tests/__snapshot__/nodeselector_deployments_test.yaml.snap
- helm/oncall/tests/__snapshot__/tolerations_deployments_test.yaml.snap
- helm/oncall/tests/affinity_deployments_test.yaml
- helm/oncall/tests/nodeselector_deployments_test.yaml
- helm/oncall/tests/tolerations_deployments_test.yaml
- helm/oncall/values.yaml
Add affinity and tolerations for celery
> fix(oncall): fix celery tolerations and affinity

- docs/sources/open-source/_index.md
- engine/apps/slack/scenarios/manual_incident.py
- engine/apps/slack/views.py
Reverts grafana/oncall#2499
`/oncall` command was removed by mistake.
> Bring back `/oncall` Slack command

- engine/apps/api/views/webhooks.py
- grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.tsx
- grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
- grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
- Fix Integrations drop down loading
- Fix template editor preview for newly created webhooks
> Webhooks 2 template editor fixes

- grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.module.css
- grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx
> Fix markup bug and change text

- grafana-plugin/src/containers/IntegrationContainers/IntegrationHeartbeatForm/IntegrationHeartbeatForm.tsx
- grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts
- grafana-plugin/src/pages/integration/Integration.tsx
This reverts commit 03f5b0f071e9f9622e45a471708b73bc6c36b28e.
> Revert "bring heartbeats back to UI"

- grafana-plugin/src/pages/integration/Integration.tsx
> fix UI typo

- CHANGELOG.md
- engine/apps/api/tests/test_auth.py
- engine/apps/api/views/auth.py
- engine/apps/social_auth/pipeline.py
- engine/conftest.py
- grafana-plugin/src/containers/Alerts/Alerts.tsx
Related to https://github.com/grafana/oncall/issues/313
> Reworked slack login pipeline errors

- engine/apps/public_api/tests/test_integrations.py
- engine/common/ordered_model/serializer.py
Fix bug related to `order` and default route introduced in https://github.com/grafana/oncall/pull/2572
> Fix public API integration default route

- CHANGELOG.md
- engine/apps/api/views/alert_receive_channel.py
> Add filter integrations by type

- CHANGELOG.md
- engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
- engine/apps/alerts/tests/test_escalation_policy_snapshot.py
- engine/apps/api/tests/test_schedules.py
- engine/apps/api/views/on_call_shifts.py
- engine/apps/api/views/schedule.py
- engine/apps/mobile_app/tasks.py
- engine/apps/public_api/views/schedules.py
- engine/apps/schedules/ical_utils.py
- engine/apps/schedules/models/on_call_schedule.py
- engine/apps/schedules/tests/test_ical_utils.py
- engine/apps/schedules/tests/test_on_call_schedule.py
- engine/apps/schedules/tests/test_quality_score.py
Reverts grafana/oncall#2625
Found a small issue, reverting for now until the problem is fixed not to block other changes
> Revert "Refactoring schedule final events for reusability"

- engine/apps/grafana_plugin/helpers/gcom.py
> Fix race condition in plugin auth

- grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
- grafana-plugin/src/state/rootBaseStore/index.ts
- grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
> Update basic data after installation

- grafana-plugin/src/state/rootBaseStore/index.ts
- grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
> Reload plugin after installation

- grafana-plugin/src/pages/incidents/Incidents.tsx
> Remove IRM loader

- grafana-plugin/src/pages/schedule/Schedule.tsx
- grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
> Require basic data loaded for schedule page

- .drone.yml
> Do not publish frontend plugin to github releases

- CHANGELOG.md
- engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
- engine/apps/alerts/tests/test_escalation_policy_snapshot.py
- engine/apps/api/tests/test_schedules.py
- engine/apps/api/views/on_call_shifts.py
- engine/apps/api/views/schedule.py
- engine/apps/mobile_app/tasks.py
- engine/apps/public_api/views/schedules.py
- engine/apps/schedules/ical_utils.py
- engine/apps/schedules/models/on_call_schedule.py
- engine/apps/schedules/tests/test_ical_utils.py
- engine/apps/schedules/tests/test_on_call_schedule.py
- engine/apps/schedules/tests/test_quality_score.py
Update `list_users_to_notify_from_ical` to use schedule final events
> Refactoring schedule final events

- docs/sources/notify/slack/index.md
To reduce confusion, added comments to slack bot permissions.
> Commented permissions required by our Slack bot.

- docs/sources/integrations/_index.md
Spelling correction of uers to users.
> Update _index.md to correct spelling error of uers to users.

- docs/sources/integrations/zabbix/index.md
> Update index.md to correct the ordered list numbers.

- CHANGELOG.md
- grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
- grafana-plugin/src/plugin/PluginSetup/index.tsx
- grafana-plugin/src/state/rootBaseStore/index.ts
- grafana-plugin/src/utils/loadJs.ts
https://github.com/grafana/oncall/issues/2687
> Fix for mobile verification

- .drone.yml
- .github/workflows/linting-and-tests.yml
- .github/workflows/snyk.yml
- tools/pagerduty-migrator/Dockerfile
Following up on https://github.com/grafana/oncall/pull/2680
> Bump Python version in CI to 3.11.4

- engine/apps/slack/models/slack_usergroup.py
Adds more logging for `SlackUserGroup.update_oncall_members` so it's easier to debug.
Related to https://github.com/grafana/support-escalations/issues/6936
> Add more logging for `SlackUserGroup.update_oncall_members`

- engine/apps/schedules/models/shift_swap_request.py
- engine/apps/schedules/tests/test_shift_swap_request.py
> Revert "Enable push notifications for SSR beneficiary for testing purposes"

- CHANGELOG.md
- engine/apps/mobile_app/tasks.py
- engine/apps/schedules/models/shift_swap_request.py
- engine/apps/schedules/tasks/shift_swaps/__init__.py
- engine/apps/schedules/tasks/shift_swaps/slack_followups.py
- engine/apps/schedules/tests/tasks/shift_swaps/test_slack_followups.py
- engine/apps/slack/scenarios/shift_swap_requests.py
- engine/settings/base.py
- engine/settings/prod_without_db.py
Add Slack follow-up messages for shift swap requests:
https://github.com/grafana/oncall/issues/2679
> Shift swap request Slack follow-ups

- docs/sources/insights-and-metrics/_index.md
- docs/sources/mobile-app/push-notifications/index.md
- docs/sources/on-call-schedules/_index.md
- docs/sources/on-call-schedules/shift-swaps/_index.md
- engine/apps/api/views/shift_swap.py
- engine/apps/schedules/models/shift_swap_request.py
Related to https://github.com/grafana/oncall/issues/2589
> Add documentation about shift swap requests

- docker-compose-developer.yml
- engine/settings/base.py
- engine/settings/prod_without_db.py
> Set schema url for Swagger via env variable

- engine/apps/alerts/models/escalation_policy.py
Reverts this PR - https://github.com/grafana/oncall/pull/2729
Fixes https://github.com/grafana/support-escalations/issues/7164
> Remove UTC from step as it is using local time

- CHANGELOG.md
- grafana-plugin/src/components/IntegrationHowToConnect/IntegrationHowToConnect.tsx
> Changed HTTP Endpoint to Email for inbound email integrations

- docs/sources/on-call-schedules/_index.md
- docs/sources/user-and-team-management/_index.md
Adds a demo video for Shift Swaps to the public documentation.
Closes #2832
> add shift swap request demo video to public docs

- engine/settings/base.py
> Tune spectacular settings

- grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
- Fix oncall logo URL
- Add note about possible missing data
> Minor metrics dashboard updates

- engine/uwsgi.ini
`uwsgi` configuration is hard to understand (the docs are 💩 and what is a `harakiri`?!). This PR adds comments to the config file so that it is easier to know what each setting does. Also adds links to a few reference blog articles that I found useful.
> add comments to uwsgi config + tweak a few settings

- engine/requirements.txt
> Revert "Bump uwsgi from 2.0.21 to 2.0.22 in /engine"

- engine/uwsgi.ini
Fixes https://github.com/grafana/oncall/issues/1521 (see https://github.com/unbit/uwsgi/issues/2299)
> Prevent uWSGI from consuming too much memory

- helm/oncall/tests/__snapshot__/telegram_polling_deployment_test.yaml.snap
- helm/oncall/tests/telegram_polling_deployment_test.yaml
> Fix helm unittests

- CHANGELOG.md
- engine/apps/slack/tests/test_interactive_api_endpoint.py
- engine/apps/slack/views.py
Fixes https://github.com/grafana/oncall/issues/2647
> Fix slack schedule notification settings dialog

- CHANGELOG.md
- Makefile
- helm/oncall/templates/_env.tpl
- helm/oncall/tests/__snapshot__/telegram_polling_deployment_test.yaml.snap
- helm/oncall/tests/__snapshot__/wait_for_db_test.yaml.snap
- helm/oncall/tests/redis_env_test.yaml
> patch helm broker env variable issue

- docs/sources/oncall-api-reference/users.md
remove duplicate line in first example.
> Remove duplicate line

- engine/apps/alerts/tasks/check_escalation_finished.py
Clean up check escalation finished task, update description
> Clean up check escalation finished task

- CHANGELOG.md
- engine/apps/slack/scenarios/distribute_alerts.py
> fix issue with slack_sdk call update

- CHANGELOG.md
- engine/apps/slack/tasks.py
[logs](https://ops.grafana-ops.net/explore?panes=%7B%22FZ0%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D~%5C%22%28prod-us-central-0%7Cprod-eu-west-0%7Cops-us-east-0%29%5C%22,%20namespace%3D~%5C%22amixr-%28staging%7Cprod%29%5C%22%7D%20%7C%3D%20%60KeyError%28%27cursor%27%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1)
> fix slack-sdk issue

- CHANGELOG.md
- engine/apps/slack/alert_group_slack_service.py
- engine/apps/slack/client.py
- engine/apps/slack/scenarios/distribute_alerts.py
- engine/apps/slack/tests/conftest.py
- engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
- engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py
- engine/apps/slack/tests/test_scenario_steps/test_slack_channel_integration.py
- engine/apps/slack/tests/test_slack_client.py
https://github.com/grafana/oncall-private/issues/2156
> Fix handling Slack rate limits

- CHANGELOG.md
- engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
- engine/apps/slack/scenarios/schedules.py
Related to https://github.com/grafana/oncall/issues/2916
Updated notification:
> Update slack schedule shift change notification

- engine/apps/telegram/models/connectors/personal.py
- engine/apps/telegram/tests/test_personal_connector.py
Fixes https://github.com/grafana/oncall-private/issues/2154
> Fix "Replied message not found" Telegram bug

- engine/apps/user_management/models/team.py
- grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
Fixes https://github.com/grafana/oncall/pull/3064
> Direct paging improvements (hotfix)

- dev/README.md
> Tilt Docs polishing

- docs/sources/integrations/amazon-sns/index.md
- docs/sources/integrations/appdynamics/index.md
- docs/sources/integrations/datadog/index.md
- docs/sources/integrations/fabric/index.md
- docs/sources/integrations/jira/index.md
- docs/sources/integrations/newrelic/index.md
- docs/sources/integrations/pingdom/index.md
- docs/sources/integrations/prtg/index.md
- docs/sources/integrations/sentry/index.md
- docs/sources/integrations/servicenow/index.md
- docs/sources/integrations/stackdriver/index.md
- docs/sources/integrations/uptimerobot/index.md
- docs/sources/integrations/zendesk/index.md
Related to https://github.com/grafana/oncall/issues/2616
> Update labels and add note for cloud-only integrations in docs

- engine/apps/alerts/tasks/acknowledge_reminder.py
Prefer partial since it is the what the [docs suggests](https://docs.djangoproject.com/en/4.2/topics/db/transactions/#performing-actions-after-commit). Also because partial is evaluated immediately while lambda is evaluated at runtime (which may be causing some issues):
```
>>> from functools import partial
>>> def foo(a, b, c):
...   print(a, b, c)
... 
>>> x = 10
>>> bar_partial = partial(foo, 1, 2, x)
>>> bar_lambda = lambda: foo(1, 2, x)
>>> x = 20
>>> bar_partial()
1 2 10
>>> bar_lambda()
1 2 20
```
> Use partial instead of lambda when queuing ack task

- CHANGELOG.md
- grafana-plugin/src/components/Unauthorized/Unauthorized.test.tsx
- grafana-plugin/src/components/Unauthorized/index.tsx
- grafana-plugin/src/index.d.ts
- grafana-plugin/src/state/rootBaseStore/index.ts
- grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts
Update calls used for access control to match changes in Grafana:
https://github.com/grafana/grafana/pull/76187
https://github.com/grafana/grafana/pull/76237
> Change functions for access control

- CHANGELOG.md
- engine/apps/api/tests/test_schedules.py
- engine/apps/api/views/schedule.py
- engine/apps/schedules/models/on_call_schedule.py
- engine/apps/schedules/tests/test_on_call_schedule.py
Fixes https://github.com/grafana/oncall-private/issues/2212
> Fix iCal imported schedules related users and next shifts per user

- .drone.yml
See [this](https://drone.grafana.net/grafana/oncall/2896/1/4) Drone job as an example output of what this build step looks like
Closes #3216
> automerge Helm release PRs after Docker images have been released to Docker Hub

- CHANGELOG.md
- engine/apps/mobile_app/migrations/0011_alter_mobileappusersettings_going_oncall_notification_timing.py
Fixes bd migration
Closes https://github.com/grafana/oncall/issues/3222
> Fix db migration for mobile app

- engine/engine/tests/test_views.py
https://github.com/grafana/oncall/pull/3274#discussion_r1383891837
> Fix assert_called_once usage in tests

- engine/engine/management/commands/continue_escalation.py
Add a flag to rebuild escalation snapshot when use `continue_escalation` command
> Add a flag to rebuild escalation snapshot when use `continue_escalation` command

- engine/apps/alerts/models/alert.py
- engine/apps/alerts/tests/factories.py
- engine/apps/labels/tests/factories.py
- engine/apps/labels/tests/test_alert_group.py
- engine/apps/labels/utils.py
- engine/apps/slack/tests/factories.py
- engine/apps/webhooks/tests/factories.py
- engine/common/utils.py
> Pass all integration labels down to alert groups

- docs/sources/escalation-chains-and-routes/_index.md
> Docs: Typo fix

- grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
> Grafana IRM -> Grafana OnCall

- CHANGELOG.md
- engine/apps/slack/scenarios/paging.py
- engine/apps/slack/tests/test_scenario_steps/test_paging.py
Closes https://github.com/grafana/support-escalations/issues/8380
> fix issue in /escalate Slack command when selecting a team

- engine/apps/api/serializers/alert_group.py
- engine/apps/api/tests/test_alert_group.py
- engine/apps/api/tests/test_escalation_chain.py
- engine/apps/api/tests/test_team.py
- engine/apps/api/views/alert_group.py
- engine/apps/api/views/alert_receive_channel.py
- engine/apps/api/views/escalation_chain.py
- engine/apps/api/views/team.py
- engine/apps/public_api/views/incidents.py
- engine/common/api_helpers/filters.py
Related to https://github.com/grafana/oncall-private/issues/2177
> Rework alert group internal API team filter

- engine/apps/integrations/tests/test_views.py
> Revert "Add test to ensure integrations work when cache is down"

- CHANGELOG.md
- engine/apps/slack/views.py
Remove bots_info call while handling slack messages.
> Fix slack ratelimit

- engine/apps/alerts/tasks/custom_button_result.py
- engine/apps/alerts/tasks/escalate_alert_group.py
- engine/apps/alerts/tasks/maintenance.py
- engine/apps/alerts/tasks/notify_user.py
- engine/apps/alerts/tasks/unsilence.py
- engine/apps/heartbeat/tasks.py
For reference, https://adamj.eu/tech/2022/08/22/use-partial-with-djangos-transaction-on-commit/.
I think this may help with this one too: https://github.com/grafana/oncall-private/issues/2318
> Update transaction.on_commit to use partial instead of lambda

- .pre-commit-config.yaml
- engine/apps/alerts/models/alert_manager_models.py
- engine/apps/alerts/models/alert_receive_channel.py
- engine/apps/alerts/tests/test_maintenance.py
- engine/apps/alerts/utils.py
- engine/apps/api/serializers/escalation_chain.py
- engine/apps/api/tests/test_labels.py
- engine/apps/api/tests/test_schedules.py
- engine/apps/api/tests/test_team.py
- engine/apps/api/views/auth.py
- engine/apps/grafana_plugin/tests/test_gcom_api_client.py
- engine/apps/metrics_exporter/metrics_collectors.py
- engine/apps/public_api/serializers/integrations.py
- engine/apps/public_api/serializers/routes.py
- engine/apps/public_api/tests/test_schedules.py
- engine/apps/public_api/tests/test_webhooks.py
- engine/apps/schedules/ical_utils.py
- engine/apps/schedules/tests/test_on_call_schedule.py
- engine/apps/slack/alert_group_slack_service.py
- engine/apps/social_auth/backends.py
- engine/apps/user_management/tests/test_region.py
- engine/apps/webhooks/models/webhook.py
- engine/apps/webhooks/tests/test_trigger_webhook.py
- engine/apps/webhooks/tests/test_webhook.py
- engine/common/api_helpers/mixins.py
- engine/common/insight_log/resource_insight_logs.py
- engine/common/tests/test_ordered_model.py
- engine/common/utils.py
- engine/conftest.py
Enables [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear), checking for bugs/design problems, and [fixes the issues found](https://pastebin.com/fEDBz6Ta) (some interesting ones, particularly with mutable args).
Related to https://github.com/grafana/oncall/pull/3448
> Enable flake8-bugbear, fix issues

- engine/apps/integrations/tests/test_views.py
- engine/apps/labels/tests/test_labels.py
- engine/apps/labels/utils.py
- engine/conftest.py
- engine/settings/base.py
It's needed because anyway labels plugin provisioned per stack, not per org
> Change labels feature flag to work per oncall org

- engine/apps/mobile_app/fcm_relay.py
- engine/apps/mobile_app/utils.py
Add more logging around `FCMDevice.send_message` in an effort to fix https://github.com/grafana/oncall-private/issues/1820
> Improve FCMDevice.send_message logging

- engine/apps/alerts/tasks/check_escalation_finished.py
- engine/apps/alerts/tests/test_check_escalation_finished_task.py
Related to https://github.com/grafana/oncall-private/issues/2347
> Log average/max delta between alert ingestion and alert group creation

- grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.helpers.ts
- grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
- grafana-plugin/src/containers/Labels/Labels.tsx
- grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
> Further improvements on labels

- grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
- grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
- grafana-plugin/src/pages/integration/Integration.tsx
- grafana-plugin/src/pages/integrations/Integrations.tsx
**Rename in the integrations menus:**
Alert Group Labels -> Alert Group Labeling
**Rename options  in the Alert Group Labeling - Add labels:**
Plain Label -> Static Label
Templates Label -> Dynamic Label
> Fix labels wording

- CHANGELOG.md
- grafana-plugin/src/pages/schedule/Schedule.helpers.ts
Fix schedules invalid dates issue
https://github.com/grafana/support-escalations/issues/8084
> Fix schedules invalid dates issue

- grafana-plugin/e2e-tests/integrations/heartbeat.test.ts
- grafana-plugin/e2e-tests/utils/schedule.ts
- grafana-plugin/package.json
- grafana-plugin/src/PluginPage.tsx
- grafana-plugin/src/navbar/Header/Header.module.scss
- grafana-plugin/src/navbar/Header/Header.tsx
- grafana-plugin/src/pages/integrations/Integrations.module.scss
- grafana-plugin/yarn.lock
> Revert "Unified logo with IRM, added few minor UI tweaks, bumped labels version"

- grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
- grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
> fix typo and edit template btn position

- engine/apps/alerts/tasks/send_update_log_report_signal.py
- engine/apps/telegram/tasks.py
> Fix task retries for deleted alert groups

- grafana-plugin/src/pages/integration/Integration.module.scss
add missing borders
https://github.com/grafana/oncall/issues/3463
> add missing borders

- docs/sources/integrations/alertmanager/index.md
Added images to oncall migration guide for alert manager
> Added images to oncall migration guide for alert manager

- engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
- engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_snapshot.py
- engine/apps/alerts/tasks/check_escalation_finished.py
- engine/apps/alerts/tests/test_check_escalation_finished_task.py
- engine/apps/alerts/tests/test_escalation_snapshot.py
Speed up escalation auditor
- use raw escalation snapshot instead of serialized one
> Speed up escalation auditor

- engine/apps/alerts/tasks/check_escalation_finished.py
- engine/apps/alerts/tasks/notify_user.py
- engine/apps/alerts/tests/test_check_escalation_finished_task.py
- engine/apps/alerts/tests/test_notify_user.py
- engine/settings/celery_task_routes.py
Requires https://github.com/grafana/oncall/pull/3557
Related to https://github.com/grafana/oncall-private/issues/2347
> Update auditor to check personal notifications

- CHANGELOG.md
- engine/apps/integrations/tasks.py
https://github.com/grafana/oncall-private/issues/2374
> Fix posting slack message about ratelimits

- engine/apps/api/tests/test_features.py
- engine/apps/api/views/features.py
Related to https://github.com/grafana/oncall-private/issues/2144
> Add msteams feature flag

- CHANGELOG.md
- engine/apps/telegram/tasks.py
- engine/apps/telegram/tests/test_tasks.py
Similar to https://github.com/grafana/oncall/pull/404
> Handle telegram message to reply to not found on send log task

- engine/requirements.txt
Reverts #3600 (related to https://github.com/grafana/oncall-private/issues/2406)
> revert forked redis lib change (#3600)

- CHANGELOG.md
- engine/apps/api/views/paging.py
> Let mobile use paging endpoint

- CHANGELOG.md
- engine/apps/api/tests/test_schedules.py
- engine/apps/api/views/schedule.py
Fixes https://github.com/grafana/oncall/issues/3626
> Fix oncall_now for a schedule in orgs with multiple entries

- CHANGELOG.md
- grafana-plugin/src/components/GForm/GForm.tsx
- grafana-plugin/src/components/GForm/GForm.types.ts
- grafana-plugin/src/components/TextEllipsisTooltip/TextEllipsisTooltip.tsx
- grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx
- grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.module.css
- grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
https://github.com/grafana/oncall/issues/3690
> Proper fix for GForm not resetting the hidden fields to undefined

- CHANGELOG.md
- engine/apps/slack/scenarios/distribute_alerts.py
- engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
Fixes https://github.com/grafana/oncall/issues/3646
> Fix posting Slack message when route is deleted

- engine/apps/api/tests/test_user.py
- engine/apps/api/views/user.py
- engine/common/api_helpers/filters.py
This should hopefully fix the lint issue [here](https://drone.grafana.net/grafana/oncall/3361/1/7)
> Update and refactor users API team filter

- engine/apps/mobile_app/tests/test_mobile_app_gateway.py
- engine/apps/mobile_app/views.py
Changes as requested by Grafana Incident team
> update mobile app gateway jwt to include user email

- engine/apps/mobile_app/tests/test_mobile_app_gateway.py
- engine/apps/mobile_app/views.py
Some more necessary changes after local testing w/ Grafana Incident team
> modify mobile app proxy gateway headers + request body

- grafana-plugin/src/pages/insights/scenes/AlertGroupsByIntegration.tsx
- grafana-plugin/src/pages/insights/scenes/AlertGroupsByTeam.tsx
- grafana-plugin/src/pages/insights/scenes/NewAlertGroupsDuringTimePeriod.tsx
- grafana-plugin/src/pages/insights/scenes/NewAlertGroupsForSelectedPeriod.tsx
- grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsDuringTimePeriod.tsx
- grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsForPeriodTable.tsx
- grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsInTotal.tsx
- grafana-plugin/src/pages/insights/scenes/TotalAlertGroups.tsx
- grafana-plugin/src/pages/insights/scenes/TotalAlertGroupsByState.tsx
- fix wrongly renamed instance in promql queries
> fix queries in insights scenes

- CHANGELOG.md
- grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx
- grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.tsx
Fix dynamic labels & multi-label extraction labels
https://github.com/grafana/oncall/issues/3750
> Fix dynamic labels & multi-label extraction labels

- CHANGELOG.md
- engine/apps/api/serializers/user.py
- engine/apps/api/tests/test_user.py
- engine/apps/api/views/user.py
Related to https://github.com/grafana/oncall/issues/3164
> Add is_currently_oncall information to internal user details API

- grafana-plugin/src/containers/GSelect/GSelect.tsx
- grafana-plugin/src/state/rootBaseStore/index.ts
- grafana-plugin/src/utils/types.ts
Improve GSelect modelName typing
> Improve GSelect modelName typing

- engine/common/oncall_gateway/client.py
Add necessary headers to ChatopsProxyAPIClient for dev environment testing.
> Add headers for ChatopsProxyAPIClient

- CHANGELOG.md
- engine/apps/api/tests/test_user.py
- engine/apps/api/views/user.py
- engine/apps/user_management/models/user.py
- engine/apps/user_management/tests/test_user.py
Fixes check whether user has telegram connection on `get_telegram_verification_code` endpoint
https://raintank-corp.slack.com/archives/C04JCU51NF8/p1706556583836909?thread_ts=1706545149.899349&cid=C04JCU51NF8
> Fix telegram connection check

- engine/apps/alerts/models/alert_group_log_record.py
- engine/apps/alerts/paging.py
- engine/apps/alerts/tasks/acknowledge_reminder.py
- engine/apps/alerts/tests/test_acknowledge_reminder.py
- engine/apps/alerts/tests/test_paging.py
Related to https://github.com/grafana/oncall/issues/3729
> Add transaction block and callbacks when triggering tasks

- engine/apps/alerts/tests/test_alert_receiver_channel.py
- engine/engine/management/commands/alertmanager_v2_migrate.py
> Add ability to migrate one org

- engine/apps/alerts/tasks/check_escalation_finished.py
- engine/apps/alerts/tests/test_check_escalation_finished_task.py
Count sms with status "accepted" as delivered in notification checker
https://raintank-corp.slack.com/archives/C025VMT6SPK/p1706799009342889?thread_ts=1706786822.083149&cid=C025VMT6SPK
> Update notification checker

- CHANGELOG.md
- engine/apps/telegram/tests/test_button_update_handler.py
- engine/apps/telegram/tests/test_update_handlers.py
- engine/apps/telegram/updates/update_handlers/button_press.py
Fixes https://github.com/grafana/oncall-private/issues/2364
> Handle alert group does not exist on telegram button press

- grafana-plugin/src/plugin.json
Changes the schema url to point to main so that it has latest changes (roles section is defined for instance)
> Fix plugin schema URL to point to main

- docs/sources/oncall-api-reference/alertgroups.md
- engine/apps/public_api/serializers/incidents.py
- engine/apps/public_api/tests/test_alert_groups.py
- engine/apps/public_api/views/incidents.py
Minor improvements to the alert groups public API (helping to get better reporting information)
> Add acknowledged/resolved by data to alert groups public API

- .github/workflows/linting-and-tests.yml
- engine/conftest.py
- engine/settings/ci-test.py
- engine/tox.ini
Follow up to https://github.com/grafana/oncall/pull/3839
> address occasional failing tests when run w/ pytest-xdist

- CHANGELOG.md
- engine/apps/api/views/escalation_policy.py
> let mobile app use escalation options endpoints

- engine/apps/alerts/models/escalation_policy.py
- engine/apps/base/models/user_notification_policy_log_record.py
Fixes https://github.com/grafana/oncall/issues/3828 (was debugging some code around, simple update)
> Update escalation step wording

- CHANGELOG.md
- engine/apps/slack/scenarios/paging.py
- engine/apps/slack/scenarios/scenario_step.py
- engine/apps/slack/scenarios/shift_swap_requests.py
- engine/apps/slack/scenarios/step_mixins.py
- engine/apps/slack/tests/test_scenario_steps/test_paging.py
- engine/apps/slack/tests/test_scenario_steps/test_shift_swap_requests.py
Fixes https://github.com/grafana/oncall/issues/3109
> Add permission checks for Slack paging and shift swaps actions

- CHANGELOG.md
- engine/apps/api/tests/test_user.py
- engine/apps/api/views/user.py
Related to https://github.com/grafana/oncall/issues/3859
> Include all upcoming shifts in upcoming shifts internal endpoint

- docs/sources/integrations/alertmanager/index.md
> Docs: fix typo

- grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
> Fix OnCall Insights dashboard version

- docs/sources/manage/mobile-app/_index.md
- docs/sources/manage/mobile-app/alert-groups-feed/index.md
- docs/sources/manage/mobile-app/installation-and-setup/index.md
- docs/sources/manage/mobile-app/push-notifications/index.md
- docs/sources/mobile-app/on-call-status-and-shifts/index.md
- docs/sources/mobile-app/schedules/index.md
fixes https://github.com/grafana/oncall-mobile-app/issues/417
> update mobile app docs

- CHANGELOG.md
- grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.helpers.ts
> Fix template preview

- grafana-plugin/yarn.lock
committing `yarn.lock` changes that I get after running `make init`
> fix yarn.lock drift

- grafana-plugin/src/components/CopyToClipboardIcon/CopyToClipboardIcon.tsx
- grafana-plugin/src/components/IntegrationContactPoint/IntegrationContactPoint.tsx
- grafana-plugin/src/components/IntegrationInputField/IntegrationInputField.tsx
- grafana-plugin/src/components/IntegrationLogo/IntegrationLogoWithTitle.tsx
- grafana-plugin/src/components/Integrations/IntegrationTag.tsx
- grafana-plugin/src/components/SourceCode/SourceCode.module.scss
- grafana-plugin/src/components/SourceCode/SourceCode.tsx
- grafana-plugin/src/components/Webhooks/WebhookLastEventDetails.tsx
- grafana-plugin/src/components/Webhooks/WebhookLastEventTimestamp.tsx
- grafana-plugin/src/components/Webhooks/WebhookStatusCodeBadge.tsx
- grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.module.css
- grafana-plugin/src/containers/OutgoingWebhookStatus/OutgoingWebhookStatus.tsx
- grafana-plugin/src/pages/integration/Integration.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/ConnectedIntegrationsTable.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/NewOutgoingWebhookDrawerContent.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/OtherIntegrations.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.styles.ts
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookDetailsDrawerTabs.tsx
- grafana-plugin/src/utils/styles.ts
> minor UI tweaks for webhooks

- grafana-plugin/src/models/alert_receive_channel_webhooks/alert_receive_channel_webhooks.ts
- grafana-plugin/src/network/oncall-api/types-generator/custom-schemas.ts
- grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.hooks.ts
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.styles.ts
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingTab.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookDetailsDrawerTabs.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhooksTable.tsx
- enable / disable SNOW webhook
https://github.com/grafana/oncall-private/issues/2462
> Enable / disable SNOW webhook

- .github/workflows/on-issue-creation.yml
> Remove add-to-project job

- engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
Make label consistent with casing in web ui
#2831
> Fix slack declare incident label

- engine/engine/wsgi.py
- engine/manage.py
- engine/requirements.in
- engine/requirements.txt
Instument requests lib to provide consistent trace_id
> Instrument requests lib

- CHANGELOG.md
- engine/apps/api/serializers/webhook.py
- engine/apps/api/tests/test_webhooks.py
Fixes https://github.com/grafana/oncall/issues/4006
> Allow setting integration_filter to null in webhooks internal API

- .github/pull_request_template.md
- .github/workflows/on-issue-creation.yml
Update PR template + change assigned label on issue creation
> update PR template + change assigned label on issue creation

- engine/apps/api/serializers/alert_receive_channel.py
Related to https://github.com/grafana/oncall-private/issues/2540
> Add additional settings serializer details for OpenAPI schema generation

- grafana-plugin/e2e-tests/users/userProfile.test.ts
- grafana-plugin/e2e-tests/utils/navigation.ts
- grafana-plugin/src/containers/UserSettings/parts/connectors/ICalConnector.tsx
- grafana-plugin/src/models/user/user.helpers.tsx
> Fix ical link revoke

- grafana-plugin/e2e-tests/users/userProfile.test.ts
> Fix user profile test

- grafana-plugin/src/components/IntegrationHowToConnect/IntegrationHowToConnect.tsx
- grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
Allow description input to be optional in the integration form
> Allow description to be optional

- engine/apps/api/tests/test_alert_receive_channel.py
- engine/apps/api/views/alert_receive_channel.py
- engine/common/exceptions/__init__.py
- engine/common/exceptions/exceptions.py
Related to https://github.com/grafana/oncall-private/issues/2542
Requires https://github.com/grafana/oncall/pull/4050
> Add integration status_options endpoint listing backsync possible statuses

- engine/apps/integrations/tests/test_integration_backsync.py
- engine/apps/integrations/throttlers/integration_backsync_throttler.py
- engine/apps/integrations/urls.py
- engine/apps/integrations/views.py
Adds endpoint for integration backsync
Related to https://github.com/grafana/oncall-private/issues/2542
> Integtation backsync endpoint

- grafana-plugin/src/containers/UserSettings/parts/connectors/Connectors.tsx
- grafana-plugin/src/containers/UserSettings/parts/connectors/MobileAppConnector.tsx
- grafana-plugin/src/containers/UserSettings/parts/connectors/PhoneConnector.tsx
- grafana-plugin/src/containers/UserSettings/parts/connectors/SlackConnector.tsx
- grafana-plugin/src/containers/UserSettings/parts/connectors/TelegramConnector.tsx
- grafana-plugin/src/models/user/user.ts
Fix unlink Slack and Telegram API calls
Closes https://github.com/grafana/oncall/issues/4102
> Fix unlink Slack and Telegram API calls

- grafana-plugin/src/components/WorkingHours/WorkingHours.tsx
> Fix working hours over the schedule events rendering

- engine/apps/integrations/mixins/ratelimit_mixin.py
- engine/apps/integrations/tests/test_ratelimit.py
Fixes a bug in the ratelimit logic when integration-specific ratelimit 429s are still counted towards the organization-wide ratelimit.
Related to https://github.com/grafana/support-escalations/issues/9579
> Fix ratelimit bug

- grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
Added NPE guard to fix search issue on slack channels inside integration
> Fix chatops search

- .pre-commit-config.yaml
- engine/apps/alerts/models/alert_group.py
- engine/apps/api/tests/test_alert_receive_channel.py
- engine/apps/api/views/alert_receive_channel.py
- engine/apps/base/tests/test_live_settings.py
- engine/apps/public_api/tests/test_schedule_export.py
- engine/apps/schedules/ical_utils.py
- engine/apps/schedules/models/on_call_schedule.py
- engine/apps/slack/scenarios/slack_renderer.py
- engine/common/utils.py
Fixes [this issue](https://github.com/grafana/oncall-private/pull/2620/files#diff-0144920543fd191db13f76c9fb797116e26eda2bdd2b79332b61bfbf5846208eR193-R197) (https://github.com/PyCQA/pycodestyle/issues/334#issuecomment-2027394413) in `grafana/oncall-private`
> upgrade flake8 to v7

- grafana-plugin/src/containers/RotationForm/RotationForm.tsx
Related to [discussion here](https://raintank-corp.slack.com/archives/C0229FD3CE9/p1712163585553429)
> Minor wording update in rotation form when weekdays mask is set

- engine/apps/integrations/mixins/ratelimit_mixin.py
> Fix bug in ratelimit logic introduced in #4137

- engine/apps/integrations/tests/test_views.py
Add test case and fixes test added in #4163 
> Add test for caching deleted integration, fix test wrap methods

- grafana-plugin/e2e-tests/insights/insights.test.ts
Fix and bring back Insights test
> Fix Insights e2e test

- engine/apps/api/tests/test_webhooks.py
- engine/apps/api/views/webhooks.py
- engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
- engine/tox.ini
> Allow getting details from connected integration webhooks

- engine/apps/api/tests/test_alert_receive_channel.py
- engine/apps/api/views/alert_receive_channel.py
> Update integration token generation endpoint to include usage details

- grafana-plugin/e2e-tests/insights/insights.test.ts
> Revert "Fix Insights e2e test"

- engine/apps/alerts/tests/test_acknowledge_reminder.py
- engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
- engine/tox.ini
Changed xdist dist setting to use `loadscope` value
See [docs](https://pytest-xdist.readthedocs.io/en/latest/distribution.html#running-tests-across-multiple-cpus)
> Update xdist load to use loadscope setting

- grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
Fix dayJSAddWithDSTFixed fn
https://github.com/grafana/oncall/pull/4103
> Proposal for dayJSAddWithDSTFixed fn fix

- engine/apps/mobile_app/tests/test_mobile_app_gateway.py
- engine/apps/mobile_app/views.py
- engine/common/cloud_auth_api/client.py
- engine/common/cloud_auth_api/tests/test_client.py
> update mobile app proxy's usage of the Cloud Auth API

- engine/apps/api/serializers/organization.py
- engine/apps/api/tests/test_organization.py
- engine/apps/api/urls.py
- engine/apps/api/views/organization.py
- engine/apps/base/messaging.py
Related to https://github.com/grafana/oncall-private/issues/2563
> Add endpoint for organization config checks

- grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
- grafana-plugin/src/pages/insights/scenes/AlertGroupsByIntegration.tsx
- grafana-plugin/src/pages/insights/scenes/AlertGroupsByTeam.tsx
- grafana-plugin/src/pages/insights/scenes/MTTRAverageStat.tsx
- grafana-plugin/src/pages/insights/scenes/MTTRByIntegration.tsx
- grafana-plugin/src/pages/insights/scenes/MTTRByTeam.tsx
- grafana-plugin/src/pages/insights/scenes/MTTRChangedTimeseries.tsx
- grafana-plugin/src/pages/insights/scenes/NewAlertGroups.tsx
- grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTable.tsx
- grafana-plugin/src/pages/insights/scenes/NewAlertGroupsNotificationsTimeseries.tsx
- grafana-plugin/src/pages/insights/scenes/NewAlertGroupsTimeseries.tsx
> Update PromQL queries on Insights page and dashboard

- engine/apps/alerts/models/alert_group.py
- engine/apps/public_api/tests/test_alert_groups.py
- engine/apps/slack/models/slack_message.py
- engine/apps/slack/tests/test_slack_message.py
- grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
Related to https://github.com/grafana/oncall/issues/4122
> Add Slack deep link entry to alert group permalinks

- .pre-commit-config.yaml
- grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
- grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowAuthSection.tsx
- grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfigDrawer.tsx
- grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowTokenSection.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/ConnectedIntegrationsTable.tsx
> SNOW minor wording & docs URL updates

- grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
Closes https://github.com/grafana/oncall/issues/4190
> Fixed labels update within Integration Form

- grafana-plugin/package.json
- grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
- grafana-plugin/yarn.lock
Updated labels version + autogenerated types
> Updated labels version + autogenerated types

- grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx
- grafana-plugin/src/models/user/user.ts
> Polish GCal UI texting

- engine/apps/schedules/ical_utils.py
- engine/apps/schedules/tests/test_ical_utils.py
Fixes https://github.com/grafana/oncall-private/issues/2529
> Update cached schedule users to consider deleted users

- engine/apps/alerts/tasks/check_escalation_finished.py
- engine/apps/alerts/tests/test_check_escalation_finished_task.py
Related to https://github.com/grafana/oncall-private/issues/2637
> Ignore uncompleted notifications if policy is deleted

- engine/apps/api/serializers/organization.py
- engine/apps/api/tests/test_organization.py
Related to https://github.com/grafana/oncall-private/issues/2563
> Update chatops connected integration organization check

- grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
- grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
- grafana-plugin/src/containers/MobileAppConnection/parts/LinkLoginButton/LinkLoginButton.tsx
- grafana-plugin/src/containers/MobileAppConnection/parts/LinkLoginButton/__snapshots__/LinkLoginButton.test.tsx.snap
Changed the text of the deep link sign in button and reorders the sections so that the qr code is on top in mobile mode
Closes https://github.com/grafana/oncall-mobile-app/issues/605
> Update mobile app sign in page

- engine/apps/alerts/models/alert_group.py
- engine/apps/public_api/serializers/incidents.py
Related to some API latency issues we were noticing.
> Minor query optimizations

- grafana-plugin/src/components/Policy/EscalationPolicy.tsx
- grafana-plugin/src/containers/AlertRules/parts/connectors/MSTeamsConnector.tsx
- grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
- grafana-plugin/src/containers/AlertRules/parts/connectors/TelegramConnector.tsx
- grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
- grafana-plugin/src/containers/EscalationChainForm/EscalationChainForm.tsx
- grafana-plugin/src/containers/GSelect/GSelect.tsx
- grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
- grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
- grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
- grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookFormFields.tsx
- grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
- grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx
- grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
Fix Slack User Group search in Escalation Steps
Closes https://github.com/grafana/support-escalations/issues/10488
> Fix Slack User Group search in Escalation Steps

- .drone.yml
https://raintank-corp.slack.com/archives/C04JCU51NF8/p1715713651334509
> pin drone docker image version

- engine/apps/slack/alert_group_slack_service.py
- engine/apps/slack/scenarios/resolution_note.py
Related to https://github.com/grafana/oncall/pull/4329
> Do not retry on SlackAPICantUpdateMessageError errors

- engine/apps/alerts/tasks/check_escalation_finished.py
Related to https://github.com/grafana/oncall-private/issues/2619
> Update escalation auditor to log total and failed escalations info

- grafana-plugin/src/models/schedule/schedule.ts
- grafana-plugin/src/pages/schedule/Schedule.styles.ts
- grafana-plugin/src/pages/schedule/Schedule.tsx
> Schedules minor fixes

- .github/actions/build-sign-and-package-plugin/action.yml
- .github/actions/set-engine-version-in-settings/action.yml
- .github/workflows/build-engine-docker-image-and-publish-to-dockerhub.yml
- .github/workflows/linting-and-tests.yml
- .github/workflows/on-commits-to-dev.yml
- .github/workflows/on-pull-requests.yml
- .github/workflows/on-release-published.yml
Related to https://github.com/grafana/oncall-private/issues/2691
> Drone -> GitHub Actions migration

- .github/workflows/build-engine-docker-image-and-publish-to-dockerhub.yml
Minor final updates to the new GitHub Actions workflows
> update github actions workflows

- engine/apps/slack/models/slack_message.py
Fixes retrying perform_notification task when Slack API returns 429 (Ratelimited)
See [thread](https://raintank-corp.slack.com/archives/C025VMT6SPK/p1717725432075029) for more details
> Handle SlackAPIRatelimitError in perform_notification

- grafana-plugin/package.json
- grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/OtherIntegrations.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhookDetailsDrawerTabs.tsx
- grafana-plugin/src/pages/integration/OutgoingTab/OutgoingWebhooksTable.tsx
- grafana-plugin/yarn.lock
add missing deps, dont use mobx-react-lite
Related to: https://github.com/grafana/irm/issues/2
> add missing deps, dont use mobx-react-lite

- engine/requirements-dev.txt
- engine/requirements.txt
Closes https://github.com/grafana/oncall/issues/4511
Also closes https://github.com/grafana/oncall/security/dependabot/108
> update `sqlparse` to address CVE-2024-4340

- helm/oncall/Chart.yaml
> Revert "Merge: Release oncall Helm chart 1.7.1"

- docs/sources/oncall-api-reference/_index.md
opened in favour of https://github.com/grafana/oncall/pull/4252
> update api docs

- grafana-plugin/src/utils/faro.ts
Fix "Cannot read ... of undefined" from Axios response
> Fix "Cannot read ... of undefined" from Axios response

- docs/sources/set-up/get-started/index.md
Simple doc typofix, Grafana was misspelled.
None
> Typofix: Grafaana -> Grafana

- Tiltfile
- dev/grafana/provisioning/plugins/grafana-oncall-app-provisioning.yaml
- engine/apps/grafana_plugin/helpers/client.py
- engine/apps/grafana_plugin/tests/test_grafana_api_client.py
fix rbac check, add grafanaUrl to provisioning file, fix resource dep in Tiltfile
> fix rbac check, add grafanaUrl to provisioning file, fix Tiltfile

- docs/sources/set-up/open-source/index.md
> Remove beta warning for mobile app

- grafana-plugin/pkg/plugin/install.go
Return bad request with error info instead of OK with error info
> Fix error status code used for /install

- Makefile
- engine/apps/public_api/tests/test_shift_swap.py
Update Makefile rule for backend bootstrap dev environment (uv wasn't finding Python in env).
Also update test to prevent timing/ordering issues.
> Update Makefile dev bootstrap; fix test

- engine/settings/base.py
> Add START_SYNC_ORG_WITH_CHATOPS_PROXY_ENABLED

- grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
- grafana-plugin/src/containers/RotationForm/parts/DaysSelector.tsx
- grafana-plugin/src/utils/faro.ts
- Fixes a couple of npe reported by faro dashboard
> FARO npe fixes

- grafana-plugin/src/pages/incidents/Incidents.tsx
As discussed in here https://raintank-corp.slack.com/archives/C0229FD3CE9/p1719242462717459
> Changed polling to 10s for alert groups

- grafana-plugin/src/plugin.json
Remove ending dot for consistency. See [thread](https://raintank-corp.slack.com/archives/C06F3A3BE3F/p1719471465827699?thread_ts=1719304572.218249&cid=C06F3A3BE3F).
> Minor plugin description update

- grafana-plugin/src/components/GTable/GTable.tsx
- grafana-plugin/src/components/Table/Table.styles.ts
- grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowTokenSection.tsx
- grafana-plugin/src/pages/schedules/Schedules.styles.ts
- grafana-plugin/src/pages/schedules/Schedules.tsx
- Fixed column spacing
Closes https://github.com/grafana/oncall/issues/4480
> Fix column caret display on schedules

- grafana-plugin/src/utils/consts.ts
fix faro reporting errors from local env
> fix faro reporting errors from local env

- engine/apps/email/inbound.py
Related to https://github.com/grafana/oncall-private/issues/2683
> Handle unexpected recipient value. Add logging.

- engine/apps/grafana_plugin/tasks/sync.py
Disable retry on cleanup tasks.  Since these will be scheduled to occur again on a regular interval minimize the tasks left on queue.  These are not critical tasks.
> Don't retry cleanup tasks

- tools/scripts/discord_webhooks.py
- tools/scripts/mattermost_webhooks.py
- tools/scripts/oncall_hours_report.py
- tools/scripts/oncall_reports.py
- tools/scripts/readme.md
- tools/scripts/shift_shifts.py
- tools/scripts/swap_requests_workday.py
A few useful Python scripts using the public API I had laying around to perform misc tasks and reporting.
> Add misc useful scripts using public API

- .github/workflows/linting-and-tests.yml
- grafana-plugin/pkg/plugin/settings.go
- grafana-plugin/pkg/plugin/users.go
> use more Grafana versions in PRs e2e tests

- engine/settings/base.py
Related to https://raintank-corp.slack.com/archives/C04JCU51NF8/p1720695995646029
> Fix `start_sync_org_with_chatops_proxy` crontab

- .github/actions/install-frontend-dependencies/action.yml
- dev/README.md
- grafana-plugin/Dockerfile.dev
- grafana-plugin/package.json
- grafana-plugin/yarn.lock
bump nodejs version to latest stable
> bump nodejs version to latest stable

- engine/common/ordered_model/serializer.py
- engine/common/tests/test_ordered_model.py
We are noticing some [issues](https://ops.grafana-ops.net/goto/sQFLv4XSg?orgId=1) when updating routes via Terraform because when receiving multiple concurrent requests updating position, the order is updated in a transaction but it is then tried to save again in the `.save` call, which could lead to `IntegrityError`s, because the order may have been updated in a concurrent request meanwhile.
Test run with the reproduced error (before the serializer update):
```
_____________________________ test_ordered_model_swap_all_to_zero_via_serializer _____________________________
@pytest.mark.django_db(transaction=True)
def test_ordered_model_swap_all_to_zero_via_serializer():
THREADS = 300
exceptions = []
TestOrderedModel.objects.all().delete()  # clear table
instances = …
```
> Update OrderedModel serializer not to save previously updated order

- grafana-plugin/src/pages/schedule/Schedule.tsx
hide forbidden actions from Add menu in schedule
> hide forbidden actions from Add menu in schedule

- grafana-plugin/e2e-tests/pluginInitialization/configuration.test.ts
- grafana-plugin/pkg/plugin/settings.go
> oncall init fixes

- engine/apps/slack/scenarios/paging.py
Related to https://github.com/grafana/oncall-gateway/issues/276
> Fix `/escalate` predefined org

- engine/apps/api/views/alert_group.py
Following up on https://github.com/grafana/oncall/pull/4731
> Force index only on list & stats

- grafana-plugin/package.json
Related to https://github.com/grafana/irm/issues/25
> change version in package.json to 1.0.0

- docs/sources/manage/notify/ms-teams/index.md
Fixes MS Teams product label as reported in Slack - https://raintank-corp.slack.com/archives/C0229FD3CE9/p1722442127606989
> fix ms teams doc product label

- docs/sources/manage/notify/phone-calls-sms/index.md
Updates the public documentation to explain SMS notification bundling behavior
> [Docs] Notification bundle update

- grafana-plugin/e2e-tests/alerts/sms.test.ts
SMS message text was changed in https://github.com/grafana/oncall/pull/4624
> Fix e2e test

- engine/apps/grafana_plugin/views/install_v2.py
- grafana-plugin/pkg/plugin/install.go
- grafana-plugin/pkg/plugin/proxy.go
- grafana-plugin/pkg/plugin/resources.go
- grafana-plugin/pkg/plugin/settings.go
- Serialization of error message from install endpoint when running in cloud
- Install endpoint read error if available
- Cloud regex make v optional
- Remove cookie headers, same as plugin proxy
> OnCall initialization minor tweaks

- docs/sources/oncall-api-reference/alertgroups.md
- docs/sources/oncall-api-reference/alerts.md
- docs/sources/oncall-api-reference/escalation_chains.md
- docs/sources/oncall-api-reference/escalation_policies.md
- docs/sources/oncall-api-reference/integrations.md
- docs/sources/oncall-api-reference/on_call_shifts.md
- docs/sources/oncall-api-reference/outgoing_webhooks.md
- docs/sources/oncall-api-reference/personal_notification_rules.md
- docs/sources/oncall-api-reference/resolution_notes.md
- docs/sources/oncall-api-reference/routes.md
- docs/sources/oncall-api-reference/schedules.md
- docs/sources/oncall-api-reference/shift_swaps.md
- docs/sources/oncall-api-reference/slack_channels.md
- docs/sources/oncall-api-reference/user_groups.md
- docs/sources/oncall-api-reference/users.md
Fixes https://github.com/grafana/oncall-private/issues/2852
> Public API docs: add note on pagination

- engine/apps/grafana_plugin/tests/test_sync_v2.py
- engine/apps/grafana_plugin/views/sync_v2.py
- engine/conftest.py
- grafana-plugin/pkg/plugin/proxy.go
- grafana-plugin/pkg/plugin/resources.go
- grafana-plugin/pkg/plugin/settings.go
- grafana-plugin/pkg/plugin/status.go
- grafana-plugin/pkg/plugin/sync.go
- grafana-plugin/pkg/plugin/teams.go
- grafana-plugin/pkg/plugin/users.go
- grafana-plugin/src/plugin.json
- Compare sync structs directly when syncing
- Permission fixes
- Return error for status != 200
- Remove debug statements
- Split up setting headers so that proxy can be done with a service account for sync
- Change sync endpoint to not require user to allow service account
- Fix bug in sync
> Plugin initialization fixes

- engine/apps/api/serializers/alert_receive_channel.py
Reduce a number of requests to db on `alert_receive_channel` internal api endpoint
from
to
> Reduce a number of requests to db on `alert_receive_channel` internal api endpoint

- docs/sources/oncall-api-reference/_index.md
- docs/sources/oncall-api-reference/alertgroups.md
- docs/sources/oncall-api-reference/alerts.md
- docs/sources/oncall-api-reference/escalation.md
- docs/sources/oncall-api-reference/escalation_chains.md
- docs/sources/oncall-api-reference/escalation_policies.md
- docs/sources/oncall-api-reference/integrations.md
- docs/sources/oncall-api-reference/on_call_shifts.md
- docs/sources/oncall-api-reference/organizations.md
- docs/sources/oncall-api-reference/outgoing_webhooks.md
- docs/sources/oncall-api-reference/personal_notification_rules.md
- docs/sources/oncall-api-reference/resolution_notes.md
- docs/sources/oncall-api-reference/routes.md
- docs/sources/oncall-api-reference/schedules.md
- docs/sources/oncall-api-reference/shift_swaps.md
- docs/sources/oncall-api-reference/slack_channels.md
- docs/sources/oncall-api-reference/teams.md
- docs/sources/oncall-api-reference/user_groups.md
- docs/sources/oncall-api-reference/users.md
> update public API docs subpage ordering

- docs/sources/manage/notify/ms-teams/index.md
- grafana-plugin/src/containers/MSTeams/MSTeamsInstructions.tsx
Update missing references to MSTeams OnCall app to now refer to Grafana IRM.
> Update msteams app refs to be for Grafana IRM

- grafana-plugin/package.json
remove engine field so that `yarn install` works on different versions of Node.js
> remove engine field

- grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
use mobx-react to fix IRM build
> chore: use mobx-react

- engine/settings/base.py
> Fix getting metrics list from env

- engine/apps/user_management/sync.py
- engine/apps/user_management/tests/test_sync.py
Since we will be triggering sync for orgs without a `last_time_synced` set, we need to make sure the token is valid (previously both, `last_time_synced` and the token, were updated from the frontend plugin)
> Make sure organization token is valid before sync

- .gitignore
- grafana-plugin/.gitignore
- grafana-plugin/e2e-tests/users/usersActions.test.ts
- grafana-plugin/e2e-tests/utils/integrations.ts
- grafana-plugin/pkg/plugin/permissions.go
- grafana-plugin/pkg/plugin/settings.go
- grafana-plugin/src/network/grafana-api/http-client.ts
- grafana-plugin/src/utils/consts.ts
- grafana-plugin/src/utils/utils.ts
- remove hardcoded plugin id so it can run from IRM monorepo context
- minor e2e tests tweaks
Related to https://github.com/grafana/irm/issues/41
> chore: more adjustments to irm monorepo

- engine/apps/slack/scenarios/distribute_alerts.py
- engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
Related to https://github.com/grafana/oncall-private/issues/2758
> Handle TimeoutError on sending message to Slack

- engine/apps/grafana_plugin/tasks/sync_v2.py
- engine/apps/grafana_plugin/views/sync_v2.py
- grafana-plugin/pkg/plugin/status.go
- Fix incorrect response for error message on sync
- Remove sleep delay from sync (natural latency provides enough delay)
> Fix plugin sync issues

- grafana-plugin/.bra.toml
- grafana-plugin/package.json
Related to https://github.com/grafana/irm/pull/45
> IRM tilt changes

- engine/apps/grafana_plugin/helpers/gcom.py
- engine/apps/grafana_plugin/tests/test_gcom.py
Related to https://github.com/grafana/oncall-private/issues/2203
> Handle a deleted organization triggering auth

- engine/apps/grafana_plugin/serializers/sync_data.py
- engine/apps/grafana_plugin/tests/test_sync_v2.py
- engine/apps/grafana_plugin/views/sync_v2.py
- grafana-plugin/pkg/plugin/debug.go
- grafana-plugin/pkg/plugin/permissions.go
- grafana-plugin/pkg/plugin/resources.go
- grafana-plugin/pkg/plugin/settings.go
- grafana-plugin/pkg/plugin/sync.go
- grafana-plugin/pkg/plugin/teams.go
- grafana-plugin/pkg/plugin/users.go
- Compresses sync data being sent to engine
- Minor fix to log messages when JSON parse errors occur
> Compress sync data

- engine/apps/alerts/tasks/notify_user.py
- engine/apps/alerts/tests/test_notify_user.py
Fixes https://github.com/grafana/oncall/issues/4760 (also provides a workaround for https://github.com/grafana/oncall/issues/4761)
> Fix direct paging ack

- grafana-plugin/package.json
- grafana-plugin/playwright.config.ts
Related to https://github.com/grafana/irm/pull/62
> `grafana/irm` tilt changes

- grafana-plugin/pkg/plugin/sync.go
- Fix logging when no error
- Add more logging to request errors during sync
> Plugin sync logging improvements

- grafana-plugin/e2e-tests/schedules/schedulesList.test.ts
- grafana-plugin/package.json
provide mod:download command and stabilize schedule test
> chore: provide mod:download command and stabilize schedule test

- Tiltfile
- Tilt would complain, on a completely fresh setup, if the `./dev/helm-local.dev.yml` file didn't exist
- fix issue when building the `grpcio` wheel
> fix some Tilt hiccups

- engine/settings/base.py
Replaces old scheduled sync task with new one.
> Enable schedule for new sync process

- grafana-plugin/e2e-tests/schedules/schedulesList.test.ts
- grafana-plugin/e2e-tests/schedules/timezones.test.ts
Related to https://github.com/grafana/irm/pull/99
Closes https://github.com/grafana/oncall/issues/4991
> improve reliability of scheduleList +timezone e2e tests

- engine/Dockerfile
> Bump base image version

- grafana-plugin/package.json
- grafana-plugin/pnpm-lock.yaml
https://github.com/grafana/gops-labels/pull/136
> Bump @grafana/labels to 1.6.4

- grafana-plugin/e2e-tests/schedules/timezones.test.ts
- grafana-plugin/playwright.config.ts
Toggle off timezone test temporarily
Use 4 workers always
> test: use 4 workers, disable timezone test

- engine/common/incident_api/client.py
- engine/common/incident_api/tests/test_client.py
Related to https://github.com/grafana/oncall-private/issues/2831
> Add incident API client

- .github/workflows/snyk-security-scan.yml
Similar to https://github.com/grafana/gops-labels/pull/137, use common vault secret rather than the org github secret
> ci: fix snyk security scans

- docs/sources/oncall-api-reference/integrations.md
Related to https://github.com/grafana/terraform-provider-grafana/issues/1665
> docs: add `templates.mobile_app` entry to Integrations API docs

- helm/oncall/Chart.yaml
> Revert "Merge: Release oncall Helm chart 1.9.29"

- engine/apps/mattermost/client.py
- engine/apps/mattermost/models/channel.py
- engine/apps/mattermost/serializers.py
- engine/apps/mattermost/tests/conftest.py
- engine/apps/mattermost/tests/test_mattermost_channel.py
- engine/apps/mattermost/tests/test_mattermost_client.py
- grafana-plugin/src/containers/MattermostIntegrationButton/MattermostIntegrationButton.module.css
- grafana-plugin/src/containers/MattermostIntegrationButton/MattermostIntegrationButton.tsx
- grafana-plugin/src/models/mattermost/mattermost.types.ts
- grafana-plugin/src/models/mattermost/mattermost_channel.ts
- grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/MattermostSettings/MattermostSettings.module.css
- grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/MattermostSettings/MattermostSettings.tsx
- grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
Add UI changes for the channel integration
> Mattermost Channel Integration UI Changes

- engine/apps/alerts/models/alert_group_log_record.py
- engine/apps/alerts/tests/test_alert_group_log_record.py
Related to https://github.com/grafana/oncall/issues/4537.
Related frontend changes: https://github.com/grafana/oncall/pull/5111/files#diff-98c45c177708c814aa5a8aafad36b0a76e9cf49d7e25dada214ae1ce9ed10699
> Include link information for objects referenced in alert group timeline

- engine/apps/alerts/incident_appearance/templaters/web_templater.py
- engine/apps/alerts/tests/test_alert_group_renderer.py
- engine/apps/api/tests/test_alert_receive_channel.py
- engine/apps/api_for_grafana_incident/tests/test_views.py
- engine/common/utils.py
Related to https://github.com/grafana/support-escalations/issues/12860
(and it should also help with https://github.com/grafana/oncall/issues/3031)
> Allow valid URLs for web image_url template

- engine/apps/alerts/models/alert_receive_channel.py
- engine/apps/alerts/tasks/notify_user.py
Small fixes for some retrying tasks
https://github.com/grafana/oncall-private/issues/2965
https://github.com/grafana/oncall-private/issues/2964
> Fix retrying tasks

- engine/settings/celery_task_routes.py
> Move send_alert_group_signal to critical

- engine/apps/alerts/tasks/notify_ical_schedule_shift.py
- engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
Related to https://github.com/grafana/support-escalations/issues/12893
> Update shift change notification to consider microsecond timestamps

- engine/apps/api/serializers/channel_filter.py
- engine/apps/api/serializers/organization.py
- engine/apps/api/serializers/schedule_base.py
- engine/apps/api/serializers/schedule_calendar.py
- engine/apps/api/serializers/schedule_ical.py
- engine/apps/api/serializers/schedule_polymorphic.py
- engine/apps/api/serializers/schedule_web.py
- engine/apps/api/serializers/slack_channel.py
- engine/apps/api/tests/test_channel_filter.py
- engine/apps/api/tests/test_schedules.py
- engine/apps/api/tests/test_set_org_default_slack_channel.py
- engine/apps/api/views/channel_filter.py
Follow up PR to https://github.com/grafana/oncall/pull/5199 and https://github.com/grafana/oncall/pull/5224, addresses a few issues I noticed on dev while testing the feature
> chore: fix some minor issues with recent `slack_channel` changes

- engine/apps/api/tests/test_schedules.py
- engine/apps/api/views/schedule.py
Related to https://github.com/grafana/irm/issues/343
> fix: update `next_shifts_per_user` to only list users with upcoming shifts

- engine/apps/api/tests/test_auth.py
- engine/apps/api/views/auth.py
- engine/apps/mattermost/backend.py
- engine/apps/social_auth/middlewares.py
Few lint fixes and path changes for new updates on oauth in base
> Fixing Lint and User auth redirect flow

- engine/apps/email/tests/test_inbound_email.py
- engine/apps/email/validate_amazon_sns_message.py
Minor inbound email improvements:
* Adds SNS certificate caching (the [original JS SDK](https://github.com/aws/aws-js-sns-message-validator/blob/a6ba4d646dc60912653357660301f3b25f94d686/index.js#L101-L104) does that as well)
* Makes sure we see a 500 when OnCall can't fetch the certificate
Related to https://github.com/grafana/oncall-private/issues/2905
> Inbound email improvements (continued)

- docs/sources/manage/notify/mattermost/index.md
- docs/sources/set-up/open-source/index.md
> Documentation for mattermost integration

- engine/apps/mattermost/backend.py
- engine/apps/mattermost/models/channel.py
- engine/apps/mattermost/tests/models/test_channel.py
- engine/apps/mattermost/tests/test_backend.py
- grafana-plugin/src/containers/AlertRules/AlertRules.tsx
- grafana-plugin/src/containers/AlertRules/parts/connectors/MattermostConnector.tsx
- grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx
- grafana-plugin/src/models/mattermost/mattermost_channel.ts
- grafana-plugin/src/pages/integration/Integration.helper.ts
> Add mattermost alert group integration flow

- docs/sources/oncall-api-reference/_index.md
- docs/sources/oncall-api-reference/alertgroups.md
- docs/sources/oncall-api-reference/alerts.md
- docs/sources/oncall-api-reference/escalation.md
- docs/sources/oncall-api-reference/escalation_chains.md
- docs/sources/oncall-api-reference/escalation_policies.md
- docs/sources/oncall-api-reference/integrations.md
- docs/sources/oncall-api-reference/on_call_shifts.md
- docs/sources/oncall-api-reference/organizations.md
- docs/sources/oncall-api-reference/outgoing_webhooks.md
- docs/sources/oncall-api-reference/personal_notification_rules.md
- docs/sources/oncall-api-reference/resolution_notes.md
- docs/sources/oncall-api-reference/routes.md
- docs/sources/oncall-api-reference/schedules.md
- docs/sources/oncall-api-reference/shift_swaps.md
- docs/sources/oncall-api-reference/slack_channels.md
- docs/sources/oncall-api-reference/teams.md
- docs/sources/oncall-api-reference/user_groups.md
- docs/sources/oncall-api-reference/users.md
Related to https://github.com/grafana/oncall-private/issues/2826
> chore: update public API docs authentication and perms

- docs/sources/manage/notify/ms-teams/index.md
Addressing a couple of docs support escalations related to the MS teams integration. 
https://github.com/grafana/support-escalations/issues/13489
> docs: clarify MS Teams connect steps and limitations

- engine/apps/auth_token/auth.py
- engine/apps/auth_token/tests/test_grafana_auth.py
Related to https://github.com/grafana/irm/issues/538
> fix: validate grafana URL value during organization auth check

- engine/apps/alerts/incident_log_builder/incident_log_builder.py
- engine/apps/alerts/tasks/notify_user.py
- engine/apps/api/views/schedule.py
- engine/apps/slack/scenarios/resolution_note.py
- engine/apps/slack/scenarios/schedules.py
- engine/apps/slack/views.py
Related to https://github.com/grafana/irm/issues/425
> chore: capitalize Slack name references

- grafana-plugin/src/containers/UserSettings/parts/UserSettingsParts.tsx
- grafana-plugin/src/containers/UserSettings/parts/connectors/PersonalWebhookConnector.tsx
- grafana-plugin/src/containers/UserSettings/parts/tabs/PersonalWebhookInfo/PersonalWebhookInfo.tsx
- grafana-plugin/src/models/user/user.ts
Adds the personal webhook form to the user profile settings.
Related to https://github.com/grafana/irm/issues/332
> feat: add personal webhook form to user profile settings

- grafana-plugin/src/pages/settings/tabs/Cloud/CloudPage.tsx
Related to https://github.com/grafana/irm/issues/1089
> chore: add warning to cloud connection

- .github/workflows/build-engine-docker-image-and-publish-to-dockerhub.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/linting-and-tests.yml
- .github/workflows/on-issue-closed.yml
- .github/workflows/on-issue-creation.yml
- .github/workflows/on-release-published.yml
- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release.yml
- .github/workflows/snyk-security-scan.yml
- .github/workflows/update-make-docs.yml
This pull request updates multiple GitHub Actions workflows to improve security, stability, and functionality. The most notable changes include pinning action versions to specific commit SHAs, adding validation for branch names, and updating dependencies and configurations.
* Added `persist-credentials: false` to `actions/checkout` steps in `.github/workflows/build-engine-docker-image-and-publish-to-dockerhub.yml` and `.github/workflows/e2e-tests.yml` to reduce the risk of unauthorized access to credentials. [[1]](diffhunk://#diff-f87667d48e22abfbbccf3695a8acc386143e3542286f432e6e3d8330960c76f9R29) [[2]](diffhunk://#diff-194218c48b9a0cdd03974145733804c2d992ca818529fe2fa69a501d8b5b1cc3R48-R59)
* Validated branch names against a safe pattern in `.github/workflows/linting-and-tests.yml` to …
> chore: update gh workflows with zizmor suggested fixes
