.github/workflows/ci.yml

This is the same workflow that gates the publishing of docs to the
website in the publish-technical-documentation-*.yml workflows.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

Add CI test to ensure that broken docs links are not merged to dev or main

---

docs/README.md

Current link https://grafana.com/docs/amixr/ -> 404
Changed to: https://grafana.com/docs/oncall/

fix link to documentation

---

engine/uwsgi.ini

fixes https://github.com/grafana/oncall/issues/84

Remove too high connections numbers from uwsgi.ini

---

docker-compose.yml

Docker compose doesn't restart containers, especially during controlled celery shutdown

Add restart always policy to the services

---

engine/apps/public_api/serializers/action.py
engine/apps/public_api/tests/test_custom_actions.py
engine/apps/public_api/views/action.py

Improve public api endpoint for for outgoing webhooks (`/actions`) by adding ability to create, update and delete outgoing webhook instance

Update public api endpoint for outgoing webhooks

---

helm/oncall/values.yaml

`externalRedis` in https://github.com/grafana/oncall/blob/dev/helm/oncall/templates/_env.tpl#L141 but here `external_redis`

Fix externalRedis for correct template

---

docker-compose.yml

Caddy container has been removed in https://github.com/roock/grafana-oncall/commit/bd923936575bed2a92cfbc5b7e348d9ca4ce1e3d
but volumes have not been removed

Remove unused caddy volumes from docker compose

---

docs/sources/chat-options/configure-telegram.md
engine/apps/alerts/models/alert_group.py
engine/apps/alerts/tasks/notify_user.py
engine/apps/base/models/user_notification_policy_log_record.py
engine/apps/telegram/alert_group_representative.py
engine/apps/telegram/models/connectors/channel.py
engine/apps/telegram/tests/test_channel_connector.py

This PR allows to have DM messages posted to Telegram without connecting a Telegram channel to routes.
The previous version with restrictions on this was not straightforward to use, see #137 for example.

Allow Telegram DMs without channel connection

---

docs/sources/open-source.md

Reverting OSS docs changes to make sure docs links are working. Further updates of this page should be aligned with the frontend and the backend rollout.

Fixing links in the OSS docs page, restoring "Production environment" paragraph

---

engine/apps/slack/utils.py

Format timestamp as UTC instead of displaying integer in cases where slack is failing to format the timestamp at the client.
https://github.com/grafana/oncall/issues/140

Use formatted UTC time for fallback in slack message

---

engine/settings/base.py

Always use the correct method to read Bol from env variables otherwise you can get into the following situation:
```
>>> settings.PUSH_NOTIFICATIONS_SETTINGS.get("APNS_USE_SANDBOX")
'False'
>>> bool(settings.PUSH_NOTIFICATIONS_SETTINGS.get("APNS_USE_SANDBOX"))
True
```

Fix wrong env var for mobile app settings

---

engine/apps/twilioapp/views.py

When checking call is coming from twilio account for path prefix being stripped by a server earlier in the chain

Twilio permission account for path prefix

---

helm/oncall/templates/ingress-regular.yaml
helm/oncall/values.yaml

**This is stacked on top of #314 -- ignore the first commit in this PR**
This supports adding paths to the oncall host so the ingress can be
configured to work with annotation-based ingress controllers (for
example, the ALB ingress controller).
By default no extra paths are added, and this change should be backwards
compatible.
---
With the "default" values (I've disabled the grafana deploy to cut down on overall output):
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: test-oncall
labels:
helm.sh/chart: oncall-1.0.2
app.kubernetes.io/name: oncall
app.kubernetes.io/instance: test
app.kubernetes.io/version: "v1.0.3"
app.kubernetes.io/managed-by: Helm
annotations:
cert-manager.io/issuer: letsencrypt-prod
kubernetes.io/ingress.class: nginx
spec:
tls:
- hosts:
- …
```

Allow chart user to add extra ingress paths

---

helm/oncall/templates/ingress-regular.yaml
helm/oncall/values.yaml

This will let the ingress work with more than just the nginx/cert-manager combination installed as part of the chart.
The default values render in a way that makes this backwards compatible, so no major version change is required.
---
With default:
Renders:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: test-oncall
labels:
helm.sh/chart: oncall-1.0.2
app.kubernetes.io/name: oncall
app.kubernetes.io/instance: test
app.kubernetes.io/version: "v1.0.3"
app.kubernetes.io/managed-by: Helm
annotations:
cert-manager.io/issuer: letsencrypt-prod
kubernetes.io/ingress.class: nginx
spec:
tls:
- hosts:
- 'example.com'
secretName: certificate-tls
rules:
- host: "example.com"
http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: test-oncall-engine
port:
number: 8080
``` …

Allow ingress TLS to be configured

---

engine/apps/twilioapp/models/phone_call.py
engine/apps/twilioapp/tests/test_phone_calls.py
engine/apps/twilioapp/twilio_client.py

Since there is no related alert group in the cloud when making a call from an OSS installation via cloud, disable the gather digit message to update alert status (which makes the call fail if an action is tried). Eventually we should provide some way to forward the action to an on-prem installation.
This is related to: https://github.com/grafana/oncall/issues/312

Disable gather digit step for cloud phone call

---

engine/apps/api/views/schedule.py
engine/apps/schedules/ical_utils.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py

Move helpers to base schedule model, making them available for any kind of schedule and also making it simple to reuse from existing and coming schedule related endpoints (e.g. shift preview, but also for future public API updates)

Move schedule helpers (filter events, final events) to model

---

docs/sources/open-source.md

Add note to OnCall OSS guide stating that the Grafana OnCall engine supports one instance of the Grafana OnCall plugin.

1 engine = 1 frontend

---

grafana-plugin/src/containers/RemoteSelect/RemoteSelect.tsx
grafana-plugin/src/containers/ScheduleForm/ScheduleForm.config.ts
grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx

Fix for #360 
Issue was on the Schedule edit `Drawer`, caused by the `openMenuOnFocus` property (which was `true` all the time) on `RemoteSelect` component
Changes:
- Added `openMenuOnFocus` prop to `RemoteSelect` - this way we can pass it as `false` from the `ScheduleForm.config`

360 - Prevent continuous focus on RemoteSelect component

---

grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
grafana-plugin/src/containers/GSelect/GSelect.tsx

Fix for [#1206](https://github.com/grafana/oncall-private/issues/1206)
Changes:
- Added new `excludedOptionsIdList` option to `GSelect` component to allow excluding ids from the selection
- Hide active incident from the attach incident list

1206 - Hide active incident from the attach incident list

---

grafana-plugin/src/containers/UserSettings/UserSettings.module.css
grafana-plugin/src/containers/UserSettings/UserSettings.tsx
grafana-plugin/src/utils/consts.ts

Fix for #304 
Changes:
- Increased modal sizing to fit in all possible tabs
- Change modal to wide modal for mobile screens
- Moved `BREAKPOINT_TABS` to separate `consts.tsx` file for possible future reuse - (_I think it'd be a good idea to have some breakpoints defined in the future_)

304 - Fixed tabs sizing in user edit modal

---

engine/apps/alerts/tasks/call_ack_url.py
engine/apps/slack/models/slack_message.py
engine/apps/slack/scenarios/distribute_alerts.py
engine/apps/slack/scenarios/escalation_delivery.py
engine/apps/slack/scenarios/notification_delivery.py
engine/apps/slack/scenarios/scenario_step.py
engine/apps/slack/scenarios/slack_renderer.py
engine/apps/slack/scenarios/step_mixins.py
engine/apps/slack/tasks.py
engine/apps/slack/views.py
grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx

#167 
Use text fallback field in all places where attachments and blocks are used. Replace attachments with blocks in some cases so text is not repeated in both.
Blocks do not support having the colored line on the left.  Alternatively we could use a colored dot emoji.
From slack docs:
> Any content displayed within attachments may be wrapped, truncated, or hidden behind a "show more" style option by Slack clients. This isn't the case with the top-level blocks field.

Fix slack notifications not displaying properly

---

engine/apps/alerts/models/alert.py

There's a `unique_together` constraint on the `AlertGroup` model for fields (`channel_id`, `channel_filter_id`, `distinction`, `is_open_for_grouping`). We rely on this uniqueness when grouping the alert groups, but in some cases when the distinction cannot be rendered due to the templating errors, the `distinction` field is set to `None`. In this case there could exist multiple alert groups with `distinction=None` and it breaks the expectation of uniqueness for this list of fields.
This PR makes sure that every alert group has a distinction not equal to `None`. In case there's an error in templating, a unique distinction will be generated, so every alert will end up in different alert groups for channels with broken templates / unrenderable distinction.

Generate unique distinction for alert groups with broken templates / unrenderable distinction

---

engine/apps/alerts/incident_log_builder/incident_log_builder.py
engine/apps/alerts/tasks/notify_group.py
engine/apps/alerts/tasks/notify_user.py
engine/apps/api/views/user_notification_policy.py
engine/apps/base/models/user_notification_policy.py
engine/apps/base/tests/test_user_notification_policy.py
engine/apps/public_api/views/personal_notifications.py
engine/apps/user_management/models/user.py
engine/common/exceptions/__init__.py
engine/common/exceptions/exceptions.py
engine/conftest.py

It's removed to get rid of select_for_update on User on each notify_user_task.
Now we checking presence of UserNotificationPolicies on each notification and if they are deleted we create set of default ones. For that logic select_for_update is needed to prevent duplicates of these sets, but it causes Deadlocks. (31 last day) So, I decided to remove this logic and just forbid to delete last UserNotificationPolicy.

Remove auto-recreating logic for UserNotificationPolicy

---

engine/apps/api/tests/test_schedules.py
engine/apps/api/views/schedule.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py

Update `next-shifts-per-user` endpoint to list all users referenced by the schedule, even if there is no coming shift for them (web schedules only).

Update next shifts per user to list all (web) schedule users

---

engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
engine/apps/alerts/incident_appearance/renderers/sms_renderer.py
engine/apps/slack/scenarios/manual_incident.py
engine/apps/twilioapp/phone_manager.py

Use of org-title is confusing, org-title is the Grafana cloud org title, users may have multiple Grafana/OnCall instances within their cloud org.  Stack slug is unique to the active OnCall installation and should be less confusing.

Use stack-slug instead of org-title

---

engine/apps/alerts/tasks/notify_ical_schedule_shift.py
engine/apps/schedules/ical_utils.py

Fix shifts and gaps notifications for web schedules with respect to `rotation_start` and `until` dates

Fix slack notification for web schedules

---

engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/helpers/gcom.py
engine/apps/grafana_plugin/tasks/sync.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py
engine/settings/base.py
engine/settings/prod_without_db.py

Code to delete organizations for stacks that no longer exist was not being run because we filter for active stacks in the start_sync_organizations task.   Deleted stacks will never be active so they are always being skipped.
This adds a task to get deleted instances from gcom and match with organizations that have not synchronized in a while and delete them if their corresponding stack has been deleted in gcom.

Add task to delete organizations if their stack has been deleted in gcom

---

engine/apps/schedules/models/custom_on_call_shift.py

This fixes a bug when `shift.by_day` is equal to empty list and the final ICAL rrule is ending up containing `BYDAY=;` (which is parsed incorrectly)

Fix empty byday in ICAL rrule

---

engine/apps/base/utils.py

Use phonenumbers package instead of regex to validate live settings to support EU number for Twilio

Use phonenumbers for validation instead of regex

---

grafana-plugin/src/state/rootBaseStore.ts

Already 5 retries (5 * 2 sec = 10 sec) is not enough in our cases. Usually, we have 15 seconds of latency.

Increase num of `getPluginSyncStatus` retries to 10

---

engine/apps/public_api/tests/test_incidents.py
engine/common/api_helpers/paginators.py

Fix API responses not using path prefix in links returning for previous/next pages during pagination.

Use create_engine_url to add prefix to previous/next links

---

CHANGELOG.md
docs/sources/oncall-api-reference/alertgroups.md
engine/apps/alerts/incident_appearance/renderers/email_renderer.py
engine/apps/alerts/incident_appearance/renderers/sms_renderer.py
engine/apps/alerts/models/alert_group.py
engine/apps/api/serializers/alert_group.py
engine/apps/public_api/serializers/incidents.py
engine/apps/public_api/tests/test_incidents.py
engine/apps/slack/scenarios/distribute_alerts.py
grafana-plugin/src/models/alertgroup/alertgroup.types.ts
grafana-plugin/src/pages/incident/Incident.tsx

This PR closes #549.
It does the following:
- renames/refactors the `AlertGroup` model's `permalink` property to `slack_permalink`
- adds a `telegram` key to the `permalinks` object in the alert group's public API HTTP response object
**Tested locally**

Feat 549 - add telegram permalink to alert groups http response

---

engine/apps/slack/scenarios/resolution_note.py

In the situation where a slack user id for the author of a message is no longer associated with a user in OnCall (User deletion in OnCall or Slack) catch the exception and display a message instead of 500 server error.

Catch exception for when oncall user is out of sync with slack user

---

engine/apps/schedules/models/custom_on_call_shift.py
engine/apps/schedules/tests/test_custom_on_call_shift.py

Example failing pipeline: https://github.com/grafana/oncall/actions/runs/3161062267/jobs/5167383842#step:4:614

Fix failing tests due to bug in month calculations

---

engine/apps/slack/scenarios/alertgroup_appearance.py

close #596
Add checking that object has attribute before access to attribute.
But not defined Amazon SNS [here](https://github.com/grafana/oncall/blob/2bfb834e92f4e7eb02760bcda33daa3f1fff67f3/engine/settings/base.py#L468-L481), so always false this block probably. ([refs](https://github.com/grafana/oncall/blob/2bfb834e92f4e7eb02760bcda33daa3f1fff67f3/engine/apps/alerts/integration_options_mixin.py#L26))
I confirmed showing a dialog after clicking "Format Alert" button.
<details>
<summary> capture </summary>
</details>
The Amazon SNS Integration seems to be not supported from #37.
If the Amazon SNS Integration removed permanently, I think that need to remove below block (and some codes).
https://github.com/grafana/oncall/blob/2bfb834e92f4e7eb02760bcda33daa3f1fff67f3/engine/apps/slack/scenar …

Fix failure of "Format Alert" button on Slack.

---

helm/oncall/templates/ingress-regular.yaml

As per [here](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation), the annotation-based approach of setting Ingress Class was deprecated in Kubernetes v1.18, which is presumably why there is a [check](https://github.com/grafana/oncall/blob/7deb6fb9206f7372be36c7f0c1e06880dbe83772/helm/oncall/templates/ingress-regular.yaml#L4) to only add the annotation for Kubernetes versions lower than this. However, there was no corresponding logic to add an explicit `ingressClassName` for later versions. This change adds that.

Fully specify ingressClassName

---

grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
grafana-plugin/src/state/plugin.ts
grafana-plugin/src/state/rootBaseStore.ts

For https://github.com/grafana/oncall/issues/249
Use exponential backoff for wait times between attempts when syncing during configuration or loading instead of a fixed 2 seconds.  This will result in much quicker response when loading.  This will also cover cases where you have longer latency as the later steps will wait much longer (For https://github.com/grafana/oncall/pull/529).

Improve Plugin Initialization Latency

---

docs/sources/integrations/available-integrations/add-alertmanager.md

Fix Alertmanager naming `AlertManager` -> `Alertmanager` because it's named [Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/) indeed 🙂 
none

Docs: Fix Alertmanager naming

---

helm/oncall/templates/_env.tpl

Rename webhook env from `TELEGRAM_WEBHOOK_URL` to `TELEGRAM_WEBHOOK_HOST` as per documentation https://grafana.com/docs/oncall/latest/open-source/#telegram-setup
**Checklist**

[helm] change telegram webhook host

---

helm/oncall/templates/_env.tpl
helm/oncall/values.yaml

This PR allows to disable to default restarts from values.yaml.
This feature increases the k8s pod restart counter, but we do it intentionally, as a precaution additional to probes.

Allow disabling autorestarts in helm deployment

---

tools/pagerduty-migrator/migrator/config.py
tools/pagerduty-migrator/migrator/report.py
tools/pagerduty-migrator/migrator/resources/integrations.py
tools/pagerduty-migrator/scripts/add_users_pagerduty_to_grafana.py

1. Allow `ONCALL_API_URL` without trailing slash
2. Show vendor name for unsupported integrations
3. run isort and black in `scripts` folder

PagerDuty migrator minor improvements

---

engine/apps/integrations/middlewares.py
engine/settings/base.py

Add a new middleware to catch PermissionDenied exception coming out of calls to non-existent integrations.
The tracebacks for these are spamming the logs, already have a status=403 in the log so we don't need the traceback here.
**Checklist**

Add middleware to catch exception for missing integration

---

engine/apps/alerts/models/channel_filter.py

If we get a channel filter regex in the database which does not parse treat as no match instead of raising exception which prevents message delivery.
https://github.com/grafana/oncall-private/issues/1416
**Checklist**

Catch exception for parsing regex during channel filtering

---

engine/apps/api/serializers/custom_button.py
engine/apps/api/tests/test_custom_button.py
engine/apps/public_api/serializers/action.py
engine/apps/public_api/tests/test_custom_actions.py

Previously, both the provided template _and_ the rendered template had
to be valid JSON in order for validation to pass. This was unnecessarily
restrictive: really, only the rendered template needs to be valid JSON.
It also disallowed using templates such as:
{
"labels": {{ alert_payload.labels | tojson }}
}
even though this would be valid JSON after rendering.
This commit relaxes the validation of custom webhook templates so that
they don't need to be valid JSON, provided that the rendered template
_is_ valid JSON. This is checked using a dummy dictionary of render
params, which use a constant string for the `alert_group_id` field
and a `defaultdict(dict)` for the `alert_payload` field. This should
permit templates like the one above, but still deny templates such as
{
"labels": {{ …

Allow non-JSON custom webhook templates, provided they render as valid JSON

---

helm/oncall/templates/_env.tpl
helm/oncall/values.yaml

The former helm values apiToken and apiTokenCommon were outdated/unused by the application.
Replaces unused environment variables in the helm release with updated env variables.
Slack ChatOps integration for helm.
**Checklist**

fix(helm): Update the Slack helm values and environment variables

---

helm/oncall/templates/_env.tpl
helm/oncall/templates/celery/_deployment.tpl
helm/oncall/templates/engine/deployment.yaml
helm/oncall/templates/engine/job-migrate.yaml
helm/oncall/templates/secrets.yaml
helm/oncall/values.yaml

This PR adds the new SMTP settings from https://github.com/grafana/oncall/pull/621 to the Helm chart.
/cc @vadimkerr since this is related to your PR that was just merged.
**Checklist**

Helm chart: add smtp settings to helm chart

---

engine/apps/slack/scenarios/resolution_note.py

I'm seeing this error in logs:
> invalid additional property: emoji [json-pointer:/blocks/0/text]
It looks like the 'emoji' argument is not supported when type: mrkdwn. This PR removes that property in the same place that the change to `mrkdwn` was made - see [this PR](https://github.com/grafana/oncall/pull/646).

Remove 'emoji' property from Slack markdown blocks in resolution notes

---

engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
engine/apps/api/tests/test_schedules.py
engine/apps/api/views/schedule.py

Related to #666.
Allow schedules type filtering by passing `?type=<type>` (where `type` is one of `api`, `ical`, `web`).
If no type is provided, all schedules are returned.

Add optional type filter to internal schedules endpoint

---

engine/apps/alerts/incident_log_builder/incident_log_builder.py

Avoid raising error when generating log line for a backend not explicitly handled, and not a registered messaging backend (eg. mobile).

Fix error when generating log line for non-handled messaging backend

---

CHANGELOG.md
grafana-plugin/src/containers/AlertRules/parts/connectors/TelegramConnector.tsx
grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx

Reverts two recent changes made in #678 which destructured `useStore` and implicitly changed how `this` is bound. See [this article](https://suhanwijaya.medium.com/a-method-destructured-from-an-object-loses-its-original-context-21e73cf1451f) for more context on this behavior.
Fixes [this](https://github.com/grafana/support-escalations/issues/4364) issue
Loom video which shows phone verification now working:
https://www.loom.com/share/b7267b788c2d4b0f985bf3efe4a9b2ed
**Checklist**

revert object destructuring changes which affect the value of 'this'

---

CHANGELOG.md
engine/apps/alerts/models/alert.py

This PR patches issue related to #708.
#708 forgot to remove attributes on models outside of the `migration_tool` django app that were referencing model attributes from `migration_tool`.
The only attribute that referenced a field in migration_tool was `migrator_lock` on the `Alert` model. This PR removes any references to that attribute.
https://www.loom.com/share/c7824ee21b8745e0a06249d9e3e7e65a
**Checklist**

Remove references to Alert.migrator_lock attribute

---

CHANGELOG.md
engine/apps/api/tests/test_custom_button.py
engine/apps/api/views/custom_button.py
grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts

It removes the `POST /api/internal/v1/custom_buttons/{id}/action endpoint` and the only reference to it in the frontend.
I am running across this endpoint in my work on RBAC. Either I would need to create a separate permission to accommodate this endpoint's current authorization setup, or I remove it since it is not used.
AFAICT it is only referenced in one method in the frontend [here](https://github.com/grafana/oncall/blob/6e5cb4e8a7577f6318ea937491e2b796ba2a419e/grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts#L317-L322), and that method isn't actually called anywhere. I did a quick [loki query](https://ops.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22typ …

remove POST /api/internal/v1/custom_buttons/{id}/action

---

docker-compose-developer-pg.yml

Updates `docker-compose-developer-pg.yml` to use a PostgreSQL db when setting up grafana (ie. no mysql needed)
Fixes #745

Update pg docker developer compose to setup grafana using pg db

---

helm/oncall/Chart.yaml
helm/oncall/README.md
helm/oncall/templates/_env.tpl
helm/oncall/templates/secrets.yaml
helm/oncall/values.yaml

This PR adds the ability to use an existing secret for external RabbitMQ. It a key in the existing secret can be specified for both the password and the username. The ability to specify the username key is required when an operator is used to create RabbitMQ credentials. We are using the [RabbitMQ Messaging Topology Kubernetes Operator](https://github.com/rabbitmq/messaging-topology-operator) to create the vhost, user and permissions for OnCall, where both the username and password are auto-generated and placed into a secret.
**Checklist**

Helm: allow for using existing secret for RabbitMQ

---

engine/apps/email/tasks.py
engine/apps/email/tests/test_notify_user.py

Changes how `from_email` field is set for email notifications on cloud license
**Checklist**

Send emails from <slug>.grafana.net on cloud

---

docs/sources/alert-behavior/_index.md

Adds temporary language to new top-level Configure alert behavior doc that was added in the docs file restructure. 
The content for this doc is in progress and will replace the basic placeholder language once complete. In the meantime, we don't want this doc to appear empty.

Add placeholder language to  alert behavior doc 

---

helm/oncall/templates/_env.tpl

This PR fixes the bug when the installation without rabbitmq external secrets didn't work ( see https://github.com/grafana/oncall/pull/761)
**Checklist**

Fix missing RABBITMQ_USERNAME field for new installations

---

grafana-plugin/src/plugin.json

- marks the `dependencies.grafanaDependency` and `dependencies.grafanaVersion` configurations in `plugin.json` to version `x.y.z` (**TODO**  once @gamab deploys his changes to `grafana/grafana`, update this)
- defines 26 new custom roles in `plugin.json` (these are the roles that get shown in the Grafana role component, see screenshot below). The main roles are:
- `Admin`: read/write access to everything in OnCall
- `Reader`: read access to everything in OnCall
- `OnCaller` : read access to everything in OnCall + edit access to Alert Groups and Schedules
- `<object-type> Editor`: read/write access to everything related to `<object-type>`
- `<object-type> Reader`: read access for `<object-type>`
- `User Settings Admin`: read/write access to _all_ user's settings, not …

[RBAC]: Frontend Part I (plugin.json)

---

Makefile
engine/apps/api/serializers/on_call_shifts.py
engine/apps/api/tests/test_oncall_shift.py
engine/apps/api/views/schedule.py
engine/apps/public_api/serializers/on_call_shifts.py
engine/apps/public_api/tests/test_on_call_shifts.py
engine/apps/schedules/ical_events/adapter/amixr_recurring_ical_events_adapter.py
engine/apps/schedules/models/custom_on_call_shift.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_custom_on_call_shift.py
engine/apps/schedules/tests/test_on_call_schedule.py
grafana-plugin/src/containers/RotationForm/RotationForm.tsx

- Enable daily/by-day shifts option for web schedules
- A few minor fixes for schedules backend (to handle some ical/terraform cases)
- Update Makefile
Related to #633 and #733

Enable daily/by-day shifts option for web schedules

---

engine/apps/api/views/schedule.py
engine/apps/schedules/models/custom_on_call_shift.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_custom_on_call_shift.py

Enforce `until` value if set for override shifts
Related to #532

Enforce until on override shifts

---

engine/tox.ini

Add rule to flake8 to remind use of apply_jinja_template instead of importing Template.
**Checklist**

Add rule for jinja2.Template to remind common environment use

---

.drone.yml
.github/workflows/ci.yml

Currently the `dev` branch [build is failing](https://drone.grafana.net/grafana/oncall/872), this PR fixes this by being explicit about the image build target (`prod`).
**More info**
For whatever reason, the `plugins/docker` image used in our Drone config builds _all_ build targets in `engine/Dockerfile` (it should skip `dev` and `dev-enterprise`). The failing command being run on drone is:
```shell
/usr/local/bin/docker build --rm=true -f engine/Dockerfile -t 1177e44cc7efb15ad0439915321ed112138f24cb \
engine/ --pull=true \
--label org.opencontainers.image.created=2022-11-09T06:23:46Z \
--label org.opencontainers.image.revision=1177e44cc7efb15ad0439915321ed112138f24cb \
--label org.opencontainers.image.source=https://github.com/grafana/oncall.git \
--label …
```

specify "prod" as the docker build target for both the drone and GitHub Actions CI pipelines

---

.drone.yml

specify `DOCKER_BUILDKIT=1` env var, this will force it to use buildkit which is what supports skipping build stages that are not required for the final image.
See [this](https://github.com/docker/cli/issues/1134) GitHub issue for more context.

force the plugins/docker drone image to use buildkit

---

Makefile
docker-compose-developer.yml
engine/.gitignore
engine/Dockerfile

Addresses some minor issues that @mderynck pointed out when running the project locally w/ the new setup:
- use `docker compose` instead of `docker-compose` in `Makefile` commands (`docker-compose` is the older/deprecated version)
- default to using `latest` tag of `grafana/grafana` image, not `main` (`main` is "bleeding edge", causes certain bugs w/ OnCall atm)
- `make backend-bootstrap` will now install `./engine/requirements-enterprise.txt` (if it exists)
- fix issue when running a non-sqlite db, and the `./engine/oncall.db` file doesn't exist, docker would complain about the sqlite db file volume mount (volume is only mounted when `DB=sqlite`)
Some minor local dev issues
**Checklist**

local dev setup - fixes for some minor issues

---

engine/apps/twilioapp/views.py

When using a Twilio API key instead of an Auth token to send messages and make calls simply check the account SID is matching since the request validatation only supports auth tokens ([docs](https://www.twilio.com/docs/usage/security)).  The actual request handling code ensures that the Call SID matches a call we have.
If this isn't secure enough we can either scrap the use of the API key and force only using Auth token or we can leave it as a less secure option.
**Checklist**

Twilio add simple check if using API key instead of AUTH token

---

dev/README.md

Proof:
```
$ grep 'COMPOSE' dev/.env.dev
COMPOSE_PROFILE=overriden_value_1
COMPOSE_PROFILES=overriden_value_2
$ make start
COMPOSE_PROFILES=overriden_value_2 [...]
```
**Checklist**

Correct typos regarding `COMPOSE_PROFILES`

---

dev/README.md

Note - you may be wondering "how could your system possibly function if `.` is not part of `CDPATH`? Testing suggests that behaviour is inconsistent between shells - `sh` will entirely ignore the current directory if `.` is absent, but `zsh` will still attempt to search the current directory even if `.` is not in `CDPATH`

Add documentation for issue make when CDPATH is set unusually

---

grafana-plugin/yarn.lock

This commit _should_ fix this dependabot security issue (which is caused by a transitive CVE from `babel-loader`):
per @jackw's suggestion I did the following:
1. removed `@grafana/toolkit` from the `package.json`
2. ran `yarn`
3. added back `@grafana/toolkit`
4. run `yarn`

fix yarn.lock

---

grafana-plugin/src/containers/AlertRules/AlertRules.tsx
grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
grafana-plugin/src/containers/ApiTokenSettings/ApiTokenSettings.tsx
grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
grafana-plugin/src/containers/UserSettings/parts/tabs/CloudPhoneSettings/CloudPhoneSettings.tsx
grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
grafana-plugin/src/containers/WithPermissionControl/WithPermissionControl.tsx
grafana-plugin/src/containers/WithPermissionControl2/WithPermissionControl.tsx
grafana-plugin/src/models/user/user.ts
grafana-plugin/src/pages/index.tsx
grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.test.tsx
grafana-plugin/src/pages/outgoing_webhooks/OutgoingWebhooks.tsx
grafana-plugin/src/pages/routes.tsx
grafana-plugin/src/pages/schedule/Schedule.tsx
grafana-plugin/src/pages/settings/SettingsPage.tsx
grafana-plugin/src/pages/settings/tabs/LiveSettings/LiveSettingsPage.tsx
grafana-plugin/src/pages/users/Users.tsx
grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
grafana-plugin/src/state/rootBaseStore/index.ts
grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts

Previously the top tab bar (eg. "Alert Groups", "Users", etc) would show user tabs that they weren't authorized to see. This PR will hide tabs that user's don't have access to.
In addition it:
- removes `RootBaseStore.isUserActionAllowed` as this was simply a reference to the `isUserActionAllowed` function from `utils/authorization`. When I wanted to access this method in `pages/index.ts` I needed to have an instance of a `RootBaseStore` which seemed awkward. Refactored all references to `RootBaseStore.isUserActionAllowed`.
- removed `NavMenuItem` from `pages/routes.tsx` and `RootBaseStore.navMenuItem` attribute. Neither of these seemed referenced in `oncall` and `oncall-private` repos. I wanted to remove `NavMenuItem` initially …

don't show user tabs they aren't authorized to see

---

engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py

A web schedule could have been deleted while someone else is looking at it (`filter_events` will try to update the cached ical data and could potentially fail to do so).

Handle error when updating ical cache from deleted web schedule

---

engine/apps/schedules/ical_events/adapter/amixr_recurring_ical_events_adapter.py
engine/apps/schedules/models/custom_on_call_shift.py
engine/apps/schedules/tests/test_ical_utils.py

Related to https://github.com/grafana/oncall-private/issues/1491

Do not include event repetitions terminated before start (until rrule)

---

README.md
docker-compose-developer.yml

- Make sure the latest docker image is used for hobby setup by running `docker-compose pull` before `docker-compose up`
- Use `linux/amd64` as mysql platform in `docker-compose-developer.yml`, should fix Apple Silicon issues

docker-compose small fixes

---

engine/apps/grafana_plugin/helpers/client.py

Remove call to gcom `api-keys/check` endpoint as it is not being used.
https://github.com/grafana/oncall-private/issues/1510

Remove unused call for checking gcom api keys

---

CHANGELOG.md
helm/oncall/Chart.yaml
helm/oncall/values.yaml

Instructs helm deployments to always pull the latest `grafana/oncall` image.
This resolves some issues reported by the community where the plugin was not able to be configured. I was able to reproduce this locally by running 1.1.5 of the plugin in the UI, and `grafana/oncall:1.1.0` (the default that my helm deployment decided to use). With this version combination I was unable to successfully configure the plugin (likely due to some changes in [v1.1.3](https://github.com/grafana/oncall/releases/tag/v1.1.3)).
When I switched the engine image pull policy to "Always" and updated my helm deployment, this fixed the issue.

helm chart v1.0.13 - update appVersion to v1.1.5 + change image.pullPolicy to "Always"

---

engine/apps/api/permissions/__init__.py
engine/apps/api/tests/test_public_api_tokens.py
grafana-plugin/src/plugin.json
grafana-plugin/src/utils/authorization/index.ts

Previously we only allowed Admins to read/write OnCall public API keys, this PR reverts the current behaviour back to that:

only grant admins read/write access to public api keys

---

grafana-plugin/src/containers/RotationForm/RotationForm.tsx
grafana-plugin/src/pages/schedule/Schedule.helpers.ts

Fix issue when setting up by-day shifts in a non-UTC timezone but shift start "converts" selected days to different ones when submitting as UTC

Update selected days to UTC before submit

---

CHANGELOG.md
helm/oncall/Chart.yaml
helm/oncall/templates/engine/job-migrate.yaml
helm/oncall/values.yaml

Currently, `.spec.ttlSecondsAfterFinished` field is hardcoded within the template. This PR allows to customize this field without changing the default functionality of the app.
Having a ttl set can cause sync issues if the app is deployed via GitOps tools such as ArgoCD. https://github.com/argoproj/argo-cd/discussions/8247
To disable TTL mechanism entirely, we can set `ttlSecondsAfterFinished` to `""` or `null` in `values.yaml`.
From kubernetes [docs](https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs):
> If the field is unset, this Job won't be cleaned up by the TTL controller after it finishes.

Make job-migrate ttlSecondsAfterFinished customizable

---

grafana-plugin/src/containers/UserSettings/UserSettings.tsx
grafana-plugin/src/pages/users/Users.tsx

- Show/Hide mobile app screen only if user has permission
- Show/Hide mobile app screen only for current user
#926

Show mobile tab only if it's feature and the user has permissions

---

CHANGELOG.md
grafana-plugin/src/containers/UserSettings/UserSettings.tsx
grafana-plugin/src/pages/users/Users.tsx

We currently show the tab to all users. However, the [`unlink_backend` endpoint](https://github.com/grafana/oncall/blob/dev/engine/apps/api/views/user.py#L128) requires the `USER_SETTINGS_WRITE` RBAC permission (or "Editor" role when RBAC is disabled). If a viewer uses the QR code to link their mobile app, and then clicks disconnect, they will get an unauthorized error.
Therefore we should just do a quick check that the current user is authorized to see this, to conditionally display this tab.
Tested locally w/ an Admin and Viewer user and is now working as intended.

hide mobile app verification tab in the user settings modal for unauthed users

---

engine/apps/api/permissions/__init__.py
engine/apps/api/tests/test_oncall_shift.py
engine/apps/api/tests/test_schedules.py
grafana-plugin/src/plugin.json
grafana-plugin/src/utils/authorization/index.ts

Fix for `EDITOR` users not having perms to be considered oncall in a schedule (because of changes in RBAC and the related fallback config).

Update SCHEDULES_WRITE fallback role to EDITOR

---

engine/apps/user_management/sync.py

this PR reverts [this change](https://github.com/grafana/oncall/commit/9e598385f492df6d7fd336c0ef441762fc4f3a72#diff-a74aa8f07a8fdc31af66559390f0fc77b66692d43e6d3c5f94311ef7eed5efabL19-L55) and removes the `str` casting that was done on the `orgId` field returned from the Grafana COM API

fix cloud sync related issue

---

grafana-plugin/src/components/NewScheduleSelector/NewScheduleSelector.tsx
grafana-plugin/src/components/SchedulesFilters_NEW/SchedulesFilters.tsx
grafana-plugin/src/models/schedule/schedule.types.ts
grafana-plugin/src/pages/schedules/Schedules.tsx

Reverting some changes from https://github.com/grafana/oncall/pull/958 (still, types can be confusing, maybe we need to rename things in the enum?)

Fix schedules types UI confusion

---

CHANGELOG.md
Makefile
dev/README.md
dev/add_env_var.sh
engine/engine/management/commands/enable_mobile_app.py

Adds a make command, `enable-mobile-app-feature-flags`, which sets the backend feature flag in `./dev/.env.dev`, and updates a record in the `base_dynamicsetting` database table, which are needed to enable the mobile app backend features.
closes #963

add make command to configure mobile app feature

---

CHANGELOG.md
helm/oncall/Chart.yaml
helm/oncall/templates/engine/deployment.yaml
helm/oncall/values.yaml

Now it is possible to change engine deployment update strategy in values.yaml.
This is due to #334 and #316, as with rolling update, race conditions might happen when there is still an old engine pod running.

Helm: define engine update strategy in values.yaml

---

grafana-plugin/src/plugin.json

Change RBAC permission scope to `plugins:id:grafana-oncall-app` from `plugins.app:id:grafana-oncall-app` for permissions with `plugins.app:access` action. This is needed because [Grafana is expecting](https://github.com/grafana/grafana/blob/main/pkg/services/accesscontrol/pluginutils/utils.go#L20-L21) `plugins:` not `plugins.app` prefix for permissions with `plugins.app:access` action.

RBAC: update RBAC permissions scopes for `plugins.app:access` action

---

engine/Dockerfile

Currently unable to exec into a k8s pod. I believe this is because `bash` is missing from the Docker image after switching from alpine to debian buster. Debugging this by adding in `bash`.

add curl and bash to oncall engine docker image

---

engine/settings/base.py

Modifies the Firebase app initialization to explicitly specify the GCP project ID where the Firebase app is. Previously it would use the project associated with the service account being used.

specify Firebase GCP project id

---

engine/apps/api/tests/test_schedules.py
engine/apps/schedules/models/custom_on_call_shift.py
engine/apps/schedules/tests/test_custom_on_call_shift.py

Fixes issue when creating a by-day shift with no events in the given time range

Handle no start date when calculating by day ical shift events

---

engine/Dockerfile
engine/requirements.txt

Fixes issue when running OnCall locally, on an M1 Mac, and using PostgreSQL as the database. (ie. `COMPOSE_PROFILES=postgres...`). Currently getting:
```bash
django.db.utils.OperationalError: SCRAM authentication requires libpq version 10 or above
```
I also tried simply adding `libpq-dev` to the `Dockerfile` but this change alone does not solve the issue. See [here](https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1898) for a similar reported issue on GitHub.
**Root Cause**
This issue is caused because `psycopg2-binary` 2.9.3 [doesn't provide](https://pypi.org/project/psycopg2-binary/2.9.3/#files) binary wheels for MacOS arm64; binary wheels for MacOS are only provided for Intel x86 64 bits ([reference](https://stackoverflow.com/a/71653850/3902555)).

swap psycopg2-binary to psycopg2 in requirements.txt

---

engine/apps/alerts/models/alert.py

With the addition of tighter controls on jinja templates handle exceptions while rendering group data as follows:
- Title will cache error message as title and display to user and the error will be logged
- Group distinction will be left as None and the error will be logged
- Is resolve signal will be treated as False and the error will be logged
- Is acknowledge signal will be treated as False and the error will be logged
https://github.com/grafana/oncall-private/issues/1542

Improve handling of template exceptions during group data creation

---

engine/apps/api/views/schedule.py

Do not defer cached ical fields which are later needed for calculating on-call users listed in the schedules list page.

Update schedules query not to defer ical fields used for on-call check

---

CHANGELOG.md
engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/tests/test_gcom_api_client.py
engine/apps/grafana_plugin/tests/test_grafana_api_client.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py

Checks the `is_rbac_permissions_enabled` flag differently based on whether we are dealing with an open-source, or cloud installation:
- for open-source installations, simply continue making a `HEAD` request to the list RBAC permissions Grafana API endpoint.
- for cloud installations, use the `config` object returned from `GET /instances/{instance_id}?config=true` and check whether `instance_info["config"]["feature_toggles"]["accessControlOnCall"] == "true"`
Resolves the issue in hosted grafana where when a stack is inactive, the hosted grafana gateway, returns 200 to the `HEAD` request (which erroneously sets the `is_rbac_permissions_enabled` flag to `true`)

refactor the is_rbac_permissions_enabled check to be more robust

---

CHANGELOG.md
helm/oncall/Chart.yaml
helm/oncall/README.md
helm/oncall/values.yaml

The templates actually generate the SLACK_SLASH_COMMAND_NAME envvar from `.Values.oncall.slack.commandName`, not `command`. This commit changes the default values file to reflect this.
#1092 
^ Are these applicable with regards to updating the helm chart, not the core application? I did take the time to test both the default and changed value after this change in a kubernetes deployment.

correct values file stub for slack commandName

---

docs/sources/open-source/_index.md

Set home_tab_enabled for slack app manifest

Disable unused home tab

---

CHANGELOG.md
engine/apps/api/tests/test_user_notification_policy.py
engine/apps/api/views/user_notification_policy.py
engine/apps/base/messaging.py
engine/apps/mobile_app/backend.py

Allows messaging backends to be enabled/disabled per organization when getting a list of available personal notification channels.

Allow messaging backends to be enabled/disabled per organization

---

engine/apps/alerts/models/alert.py
engine/apps/alerts/paging.py
engine/apps/alerts/tests/test_alert.py
engine/apps/alerts/tests/test_paging.py
engine/apps/integrations/templates/html/integration_direct_paging.html
engine/config_integrations/direct_paging.py
engine/settings/base.py

Also changes the default integration used when creating an alert group for a direct page to a custom manual integration to avoid conflicts/unexpected behaviors with existing manual alerts.

Add escalation chain option when creating a direct page alert group

---

engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
engine/apps/slack/scenarios/declare_incident.py
engine/apps/slack/views.py

Add a dummy step for declare incident button to prevent raising 'Step is undefined' exception because Slack sends a POST request to the backend upon clicking a button with a redirect link to Incident.
This pr doesn't change any functionality

Add a dummy step for declare incident button in slack

---

docker-compose-developer.yml
engine/engine/urls.py
engine/settings/base.py
engine/settings/dev.py

This PR moves silk profiler under the settings flag which can be configured with env vars. It will allow us to enable silk on the clusters, e.g. dev

Move silk profiler under env variable setting

---

grafana-plugin/src/state/rootBaseStore/index.ts

Fixes a bug on the frontend when `this.cloudStore.loadCloudConnectionStatus()` fails to run due to features list not being updated yet in `updateBasicData` while initially loading the plugin page.

Fix cloud connection frontend bug

---

.github/workflows/verify-changelog-updated.yml

Add a GitHub Action to check that the `CHANGELOG.md` has been updated. If no `CHANGELOG.md` change is required, simply add the "no changelog" label to your PR, which will effectively skip this check.

add github action to verify that changelog has been updated

---

.github/verify-public-docs-updated.sh
.github/workflows/verify-public-docs-updated.yml

This PR adds a new GitHub Action which will run on PRs against `dev` and `main`. The GitHub action will not run if the label of "no public docs" has been applied to the PR in question:
Otherwise, it will check to see if any changes were made to either the `engine` or `grafana-plugin` directories. If so, it will then check whether changes were also made to the `docs` directory. If not, it will fail the job and block the build.
**No changes made to "engine" or "grafana-plugin" directories**
**Job skipped when "no public docs" label applied to PR**
**Changes made to "engine" and/or "grafana-plugin" directories and public docs also updated**
**Changes made to "engine" and/or "grafana-plugin" directories but public docs were not updated**
N/A

add small script + github action to check that public docs updated

---

engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/tests/test_alert_group.py
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/api/views/alert_receive_channel.py
engine/apps/public_api/tests/test_integrations.py
engine/apps/public_api/views/integrations.py
grafana-plugin/src/pages/incident/Incident.tsx

Hide direct paging integrations from the web UI. Related to https://github.com/grafana/oncall/issues/823

Hide direct paging integrations

---

CHANGELOG.md
grafana-plugin/src/state/rootBaseStore/index.ts

Related to [this PR comment](https://github.com/grafana/oncall/pull/1164#discussion_r1082337697) from @maskin25 
**Before**
**After**

remove duplicate call in UI to GET /alert_receive_channels

---

engine/Dockerfile
engine/apps/api/views/alert_group.py

Changing query to retrieve alert group in two requests instead of one with `join`
old query:
```
SELECT `alerts_alertgroup`.`id`
FROM `alerts_alertgroup`
INNER JOIN `alerts_alertreceivechannel` ON (`alerts_alertgroup`.`channel_id` = `alerts_alertreceivechannel`.`id`)
WHERE (`alerts_alertreceivechannel`.`organization_id` = 1
AND `alerts_alertreceivechannel`.`team_id` IS NULL
AND NOT `alerts_alertgroup`.`is_archived`
AND NOT `alerts_alertgroup`.`is_archived`
AND `alerts_alertgroup`.`root_alert_group_id` IS NULL
AND ((NOT `alerts_alertgroup`.`silenced`
AND NOT `alerts_alertgroup`.`acknowledged`
AND NOT `alerts_alertgroup`.`resolved`)
OR (`alerts_alertgroup`.`acknowledged`
AND NOT `alerts_alertgroup`.`resolved`))
AND NOT `alerts_alertgroup`.`is_archived`)
ORDER BY `alerts_alertgroup`.`id` …
```

Optimize alertgroups endpoint

---

engine/apps/slack/views.py

This just tweaks the message users get when they try to interact via slack but haven't connected their profile, it fixes a typo and streamlines the text.

Update message when user needs to connect their profile

---

CHANGELOG.md
engine/apps/oss_installation/tests/test_views.py
engine/apps/oss_installation/urls.py
engine/apps/oss_installation/views/cloud_connection.py
engine/engine/urls.py

Fixes the issue when users with the viewer role can't fetch the cloud connection status, which makes the plugin fail to load for viewers. This PR makes the cloud connection endpoint use `OTHER_SETTINGS_READ` for fetching the cloud connection status instead of `OTHER_SETTINGS_WRITE`.

Allow viewers fetch cloud connection status

---

.drone.yml

Add a check in drone so build fails if plugin is not successfully signed.

Add check for MANIFEST.txt after signing

---

.pre-commit-config.yaml
docs/sources/calendar-schedules/_index.md
docs/sources/calendar-schedules/ical-schedules/index.md
docs/sources/calendar-schedules/web-schedule/_index.md
docs/sources/calendar-schedules/web-schedule/calendar-export/index.md
docs/sources/calendar-schedules/web-schedule/create-schedule/index.md

This PR adds `--fix` flag to `markdownlint` pre-commit command and fixes existing formatting to comply with markdown formatting rules.

Fix markdown formatting in docs

---

engine/apps/mobile_app/backend.py

Make so there's no need to populate `mobile_app_settings` DynamicSetting when using the OSS license to turn on the mobile app backend.

Remove DynamicSetting usage for mobile app backend on OSS

---

engine/apps/slack/scenarios/paging.py

Fixes issue when there are more than 100 users to be listed in the direct pagination responders select. Alternatively we should consider moving to an `external_select` block later.

Add paging for direct paging users in slack dialog

---

.pre-commit-config.yaml

`lint` github action jobs on all builds are failing right now ([example](https://github.com/grafana/oncall/actions/runs/4042567074/jobs/6950923821#step:6:16)) because of [this issue](https://github.com/PyCQA/isort/issues/2077) with `isort`

fix failing lint github actions job due to issue w/ isort version

---

.github/CODEOWNERS

There is no need to add `@grafana/grafana-oncall-backend` as a PR reviewer when `CHANGELOG.md` is updated

don't tag oncall-backend when CHANGELOG is updated

---

CHANGELOG.md
engine/apps/api/views/alert_group.py
grafana-plugin/src/containers/IncidentsFilters/IncidentsFilters.tsx

Related to #1119 
It also adds a shortcut to filter current user's related alert groups (alert groups user was notified by, or in which user participated). Make the filter visible by default, with a false value.

Add a filter by involved users to alert groups page

---

.github/CODEOWNERS

Adding in reference to #1239.
@grafana/docs-oncall should be tagged as a PR reviewer for changes to `/docs` rahter than @grafana/grafana-oncall-backend.

tag @grafana/docs-oncall instead of oncall-backend for docs related changes

---

CHANGELOG.md
engine/requirements.txt
engine/settings/base.py

We occasionally see `django.db.utils.OperationalError` pop up. These seem to be sporadic and for whatever reason the engine/celery processes cannot connect to the database, but succeed on subsequent requests. This results in HTTP 500s for the original requests. The `django-dbconn-retry` library states in its documentation:
> This library monkeypatches django.db.backends.base.BaseDatabaseWrapper so that when a database operation fails because the underlying TCP connection was already closed, it first tried to reconnect, instead of immediately raising an OperationException.
I would like to give this a try and see if this patches these `django.db.utils.OperationalError` errors.

add django-dbconn-retry library

---

engine/apps/slack/models/slack_message.py
engine/apps/slack/models/slack_user_identity.py
engine/common/database.py
engine/common/tests/test_database.py

This is a minor refactor before implementing https://github.com/grafana/oncall-private/issues/1558.
Additionally, it cleans up a few spots where we do this:
```
```
We currently don't read anything from a read-only database, so this should be not necessary.

Add utility function to get readonly db key if defined

---

engine/apps/mobile_app/fcm_relay.py
engine/apps/mobile_app/tasks.py
engine/apps/mobile_app/tests/test_fcm_relay.py
engine/apps/mobile_app/tests/test_notify_user.py

Raise `FirebaseError` in celery tasks contacting FCM instead of just logging it + add tests

Better FCM error handling / retries

---

Makefile
dev/README.md
docker-compose-developer.yml
engine/engine/management/commands/start_celery.py
engine/settings/dev.py

Fixes an issue when a local dev setup becomes extremely slow.
- Set `DEBUG` and `SILK_PROFILER_ENABLED` to `False` by default + add utility make commands to toggle it
- Use `uwsgi` instead of Django's built-in `runserver` for local dev setup
- Limit Celery concurrency to 3 for local dev setup (previously was 20, used >1GB RAM on my machine)

Fix local dev setup slowness

---

engine/apps/alerts/paging.py
engine/apps/alerts/tests/test_paging.py

This will eventually allow to improve responders information in an alert group detail page

Keep track of direct paging schedule/importance in logs

---

engine/apps/api_for_grafana_incident/views.py

Grafana Incident API only ever accesses individual alert groups by ID.
Using the /api/gi/v1/alert-groups endpoint without an ID would list every
single alert group in the database (from what I can tell), since the auth
isn't org-specific.
This is a precursor to another PR which adds more details to the alert group
serializer, which makes the query more resource intensive, so I thought it
best to disable listing first.

Disable listing alert groups using Grafana Incident API 

---

engine/apps/api_for_grafana_incident/serializers.py

This will be used by Grafana Incident to infer details about the
incident if alert groups are present.
Depends on #1279

Include alert details in Grafana Incident alert-group endpoint

---

engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py

Related to #1216 
Set default cached empty value as `""`, while keeping `None` to indicate a refresh is needed.

Rework schedules cached ical file values

---

tools/pagerduty-migrator/migrator/report.py
tools/pagerduty-migrator/migrator/resources/escalation_policies.py
tools/pagerduty-migrator/migrator/resources/integrations.py
tools/pagerduty-migrator/migrator/resources/schedules.py
tools/pagerduty-migrator/migrator/tests/test_matching_extra_spaces.py

Currently PD migrator can fail with HTTP 400 error when dealing with PD resource names like " Schedule" (note the extra space). This PR makes sure that PD migrator script can handle such cases.

PD migrator: handle resource names with extra spaces

---

engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/api/views/alert_receive_channel.py

Changes the internal API to show direct paging integrations in list filter options.

Show direct paging integrations in list filter options

---

CHANGELOG.md
engine/apps/alerts/models/alert_group.py

Issue with too long declare incident link in Slack

Fix too long declare incident link

---

.github/dependabot.yml

This PR is meant to code-ify our dependabot configuration. This is being done mainly to override the default labels that dependabot adds to the PRs it opens.

code-ify dependabot configuration

---

engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py

Reverts grafana/oncall#1312
This change seems to have introduced some unexpected behavior with slack user groups. Reverting to reproduce locally and push an improved update.

Revert "Rework schedules cached ical file values"

---

.github/workflows/ci.yml
.github/workflows/snyk.yml
.github/workflows/verify-changelog-updated.yml
.github/workflows/verify-public-docs-updated.yml

Get the repo ready to support the [pull request merge queue](https://github.blog/changelog/2021-10-27-pull-request-merge-queue-limited-beta/):

trigger github actions jobs on merge_group event

---

.github/workflows/verify-changelog-updated.yml
.github/workflows/verify-public-docs-updated.yml

They don't appear to work properly there:

don't run changelog/public-docs CI checks on merge_group Github events

---

CHANGELOG.md
engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/tests/test_grafana_api_client.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py

this PR refactors the `sync_organization` and `GrafanaAPIClient.is_rbac_enabled_for_organization` methods to check the connected response bool rather than explicit check on HTTP 200. This handles the legitimate case where the Grafana instance may return an HTTP 302 (redirect) rather than an HTTP 200.
See [this](https://grafana.slack.com/archives/C02LSUUSE2G/p1677136582890269) Slack thread in the community channel for more context

patch minor sync issue when HTTP 302 is received from Grafana API instance

---

tools/pagerduty-migrator/migrator/resources/schedules.py
tools/pagerduty-migrator/migrator/tests/test_schedules.py

Handle deactivated users in PD when migrating schedules using PD migrator.

PD migrator: handle deactivated users in PD when migrating schedules

---

engine/apps/auth_token/auth.py
engine/apps/integrations/mixins/alert_channel_defining_mixin.py

When an organization is migrated to a different cluster it has it's `migration_destination_slug` set for redirection purposes but it also needs to be deleted so scheduled tasks for it do not run in the old cluster.  By changing the order so moved has precedence over deleted API calls will be correctly redirected for moved organizations while the organization is still considered deleted to suppress tasks that are no longer needed in the old cluster.

Change Organization Deleted/Moved Precedence

---

tools/pagerduty-migrator/migrator/__main__.py
tools/pagerduty-migrator/migrator/resources/schedules.py
tools/pagerduty-migrator/migrator/tests/test_schedules.py

Make PagerDuty migrator create shifts in UTC timezone when migrating web schedules.

PD migrator: create shifts in UTC timezone

---

CHANGELOG.md
engine/apps/api/serializers/alert_group.py
engine/apps/api/tests/test_alert_group.py
grafana-plugin/src/pages/incident/Incident.tsx

Make internal API return 100 latest alerts for alert group.
https://github.com/grafana/oncall/issues/857

Show 100 latest alerts on alert group page

---

grafana-plugin/src/pages/incident/Incident.tsx
grafana-plugin/src/pages/incidents/Incidents.tsx

Source link is not related with Integration, so it is just a label now
Icon of integration moved to Integration label-link
Incident word was removed from "1 attached Incidents"
https://github.com/grafana/oncall/issues/1387

1387 source link redesign

---

CHANGELOG.md
engine/apps/api/tests/test_schedules.py
engine/apps/api/views/schedule.py

Fixes a bug with inconsistent schedule count when searching by name.
Example (2 schedules returned, but count is incorrectly set to 12):

Fix pagination issue when searching schedules

---

CHANGELOG.md
engine/apps/slack/scenarios/resolution_note.py

changing the block element type from `plain_text` to `mrkdwn` now allows slack to properly render Slack usernames in the Slack UI.
Also, it seems that the `mrkdwn` context block type does not support the `emoji` key, hence getting rid of it. From the Slack [docs](https://api.slack.com/reference/block-kit/composition-objects#text):

fix resolution note Slack rendering bug

---

CHANGELOG.md
engine/apps/slack/models/slack_message.py
engine/apps/slack/scenarios/escalation_delivery.py

update wording in some Slack messages which mention 'incident' instead of 'alert group'

---

Makefile
dev/README.md

Moved part of dev/README.md into `make help` command:
```
make help
start                    start all of the docker containers
init                     build the frontend plugin code then run make start
restart                  restart all docker containers
build                    rebuild images (e.g. when changing requirements.txt)
cleanup                  this will remove all of the images, containers, volumes, and networks
lint                     run both frontend and backend linters
test                     run backend tests
start-celery-beat        start celery beat
purge-queues             purge celery queues
shell                    starts an OnCall engine Django shell
dbshell                  opens a DB shell
engine-manage            run Django's `manage.py` script, inside of a …
```

Add "make help" command

---

CHANGELOG.md
grafana-plugin/src/containers/AlertRules/AlertRules.tsx

Hello everyone 👋 
This is my first PR to the OnCall repo so please let me know if I'm not doing something right. I'm also not sure if the items in the Checklist are for me to complete or someone else. If those are for me, please let me know and I'll be happy to do them (with some guidance as a first-timer)!
This PR is a really small suggestion to the wording in this file. I believe it will help improve the way this line of text is read by users.

Update wording when creating an integration

---

engine/apps/mobile_app/tasks.py

In the "apns" key of the message sent to FCM, "headers" should not be nested under "payload", it should instead be at the same level. See Firebase docs for the `FirebaseAdmin.Messaging.ApnsConfig` class [here](https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/apns-config#class_firebase_admin_1_1_messaging_1_1_apns_config_1a7a9858f0b30ef7c437205ca01d6e62f6)

minor bugfix for ios push notifications config

---

CHANGELOG.md
engine/apps/mobile_app/tasks.py
engine/apps/mobile_app/tests/test_notify_user.py

I just noticed that ios notifications are always critical, even when the switch ("override DND") is set to `false`. I believe this is because `critical` should be either 1 or 0 
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2990112

Update apns payload with corrected `interruption-level` field

---

CHANGELOG.md
grafana-plugin/src/components/Tutorial/Tutorial.tsx
grafana-plugin/src/containers/AlertReceiveChannelCard/AlertReceiveChannelCard.tsx
grafana-plugin/src/containers/AlertRules/AlertRules.tsx
grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
grafana-plugin/src/containers/IncidentMatcher/IncidentMatcher.tsx
grafana-plugin/src/containers/IntegrationSettings/IntegrationSettings.tsx
grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.module.css
grafana-plugin/src/containers/IntegrationSettings/parts/Autoresolve.tsx
grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.config.tsx
grafana-plugin/src/containers/RotationForm/RotationForm.module.css
grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
grafana-plugin/src/pages/incident/Incident.tsx
grafana-plugin/src/pages/incidents/Incidents.tsx
grafana-plugin/src/pages/index.tsx
grafana-plugin/src/plugin.json
grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
grafana-plugin/src/utils/consts.ts
grafana-plugin/src/utils/url.ts

Reverts grafana/oncall#1600 as it makes Slack links not working correctly with the plugin UI.

Revert "Collection of bugs"

---

CHANGELOG.md
engine/apps/schedules/models/custom_on_call_shift.py
engine/apps/schedules/tests/test_custom_on_call_shift.py

When generating ical information for an event, the RRULE until value must be specified in UTC.
Related to https://github.com/grafana/support-escalations/issues/5426.

RRULE until values must be specified in UTC tz

---

docs/sources/calendar-schedules/web-schedule/create-schedule/index.md

Add a note that user working hours are currently hardcoded and will be updated in a future release
Adds a note that OnCall working hours are hardcoded and cannot be customized at the moment.

Include a note on user working hours

---

CHANGELOG.md
engine/apps/api/tests/test_team.py
engine/apps/api/views/team.py

Team search doesn't work when filtering by team:
This PR fixes it + adds backend unit tests.

Fix team search

---

tools/pagerduty-migrator/migrator/__main__.py
tools/pagerduty-migrator/migrator/config.py
tools/pagerduty-migrator/migrator/report.py
tools/pagerduty-migrator/migrator/resources/rulesets.py

Allows to include service & integration names to migrated ruleset name when passing `EXPERIMENTAL_MIGRATE_EVENT_RULES_LONG_NAMES=True`.

PD migrator: include service & integration names to ruleset

---

.github/workflows/linting-and-tests.yml

Will re-enable them (and set this job as a required passing build step) once all of the sub-tasks of https://github.com/grafana/oncall/issues/1692 are fixed

temporarily disable e2e CI job

---

engine/apps/api/tests/test_user.py
engine/apps/api/views/user.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py

Add internal API endpoint to get users' upcoming shifts:
`GET /api/internal/v1/users/<USER PK>/upcoming_shifts`
Related to https://github.com/grafana/oncall-private/issues/1602.

Add user endpoint to get upcoming shifts details

---

CHANGELOG.md
engine/apps/slack/slack_client/slack_client.py

Catch the new Slack error code "message_limit_exceeded" as a rate limit error

Add Slack Api error "message_limit_exceeded" to SlackAPIRateLimitException

---

grafana-plugin/src/components/GForm/GForm.tsx

Return behavior so GForm select drop-down accesses value field instead of using the KeyValuePair.

Fix GForm Select dropdowns

---

CHANGELOG.md
engine/apps/alerts/models/alert_group.py

The routing of the OnCall plugin has changed and no longer uses URL params
but instead uses paths. This link is used when declaring an Incident from
the OnCall Slack alert and needs to match the correct pattern in order for
Incident to correctly detect it.

Fix `web_link` property of AlertGroup

---

engine/apps/api/views/telegram_channels.py
engine/apps/api/views/user.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/slack/models/slack_team_identity.py
engine/apps/slack/views.py
engine/apps/social_auth/pipeline.py
engine/apps/telegram/models/connectors/channel.py
engine/apps/telegram/models/verification/channel.py
engine/apps/telegram/models/verification/personal.py
engine/apps/user_management/models/organization.py
engine/common/insight_log/__init__.py
engine/common/insight_log/chatops_insight_logs.py

Most of the PR is just renaming ChatOpsType to ChatOpsPlug, core changes are linked below: 
- Fix insight_logs error writing unlink_backend error https://github.com/grafana/oncall/pull/1757/files#diff-7ae187be84e55ebac962bad0984f7569186cdc83c896132b2ebcbcbb31bbf5dd
- Fix insight_logs error writing updated schedule with installed slack integration (https://github.com/grafana/oncall/pull/1757/files#diff-4037b7bbef9fc16d9b541beb3ed46f760916d7cd720847c3123adf7afb5ab4b4L690)

Fix insight_logs exceptions

---

CHANGELOG.md
helm/oncall/Chart.yaml
helm/oncall/templates/engine/job-migrate.yaml
helm/oncall/values.yaml

This PR adds the option to use helm hooks for the database migration.
Currently oncall always shows as out-of-sync in argo-cd because the name changes on each hard refresh. 
When using a helm hook the job is executed on sync but does not show as out-of-sync

Add option to use helm hook for migration job

---

CHANGELOG.md
engine/apps/api/tests/test_user.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py

Fix issue when creating web overrides for TF schedules using a non-UTC timezone (web UI assumes editable events are UTC-based).

Use shift tz for web-created events

---

CHANGELOG.md
engine/apps/api/tests/test_team.py
engine/apps/api/views/team.py

Fixes team update endpoint for internal API + adds a unit test for this scenario.
https://github.com/grafana/oncall/issues/1774

Fix team update

---

CHANGELOG.md
helm/oncall/templates/engine/job-migrate.yaml

This PR fixes the migration job when using helm hooks.
Currently when enabling the useHooks option in the helm chart there is a deadlock as the hook is defined as "post-upgrade, post-install". In this case the database migration will only be executed when all other pods are ready. This will not happen as the pods are waiting for the database migration. So we need to use "pre-install, preupgrade" instead of "post-install,post-upgrade"
- [ x] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

Fix helm hook for migration job

---

engine/apps/alerts/signals.py
engine/apps/alerts/tasks/distribute_alert.py
engine/apps/webhooks/listeners.py
engine/apps/webhooks/signals.py
engine/apps/webhooks/tests/test_trigger_webhook.py
engine/apps/webhooks/utils.py

- Change FIRING trigger for webhooks to be sent after escalation snapshot has been computed
- Extract users from `notify_to_users_queue` and `notify_schedule` from escalation snapshot to populate `users_to_be_notified` in webhook payload

Add users_to_be_notified to new webhooks payload

---

docs/Makefile
docs/docs.mk
docs/make-docs
docs/variables.mk

- Adds ability to build multiple projects simultaneously using, for example, `make docs PROJECTS='grafana grafana-cloud'`.
- Adds `make doc-validator` which runs [`doc-validator`](https://github.com/grafana/technical-documentation/tree/main/tools/cmd/doc-validator) on all documentation.
Using a centralized script will help ensure consistency in workflow across all projects.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

Use centralized make-docs script from Writers' Toolkit

---

engine/apps/schedules/ical_utils.py
engine/apps/schedules/models/on_call_schedule.py
grafana-plugin/src/containers/ScheduleIcalLink/ScheduleIcalLink.tsx
grafana-plugin/src/containers/UserSettings/parts/connectors/ICalConnector.tsx

Also include a suggested refresh interval in the generated ical
(Google Calendar will still ignore it, but may be useful for some other clients).

Add final schedule export refresh note

---

CHANGELOG.md
engine/apps/alerts/models/alert_group.py

This PR adds additional silence options in the UI. Currently we only have 1 hour, 4 hours and 12 hours silence options. I think it's worth it to have finer silence options.
No issue ticket but I can create one.

Add 2, 3 and 6 hours silence options

---

engine/apps/webhooks/tasks/trigger_webhook.py

team_id was removed from send_webhook_event when other calls were still adding it. Quick fix to restore it until we decide how to make use of it.

Restore removed parameter

---

engine/apps/slack/tests/factories.py

Fix [flaky test](https://github.com/grafana/oncall/actions/runs/4821277510/jobs/8586941639#step:5:706) `test_get_user_groups_filter_by_handle` using `UniqueFaker` on `SlackUserGroupFactory.handle` to make handles always unique.
Before:
```shell
>>> len(set([SlackUserGroupFactory().handle for _ in range(100)]))
93
```
After:
```shell
>>> len(set([SlackUserGroupFactory().handle for _ in range(100)]))
100
```

Fix flaky Slack test

---

engine/apps/grafana_plugin/tasks/sync.py

start_sync_organization is scheduled to run every 30 mins.  Countdown is not specified so the default countdown with exponential backoff will result in retries happening after the next 30 min trigger.  If it is in a state where it is retrying for a long period of time (>30 mins) it will stack up too many redundant sync_organization_async tasks when it finally does succeed.

Do not retry start_sync_organization

---

CHANGELOG.md
engine/apps/alerts/models/alert_receive_channel.py
engine/apps/slack/scenarios/alertgroup_appearance.py

Remove template editor from Slack

---

docs/sources/integrations/available-integrations/configure-jira/index.md
engine/apps/integrations/templates/html/integration_jira.html
grafana-plugin/src/components/IntegrationLogo/IntegrationLogo.config.ts

Add docs & logo for Jira integration. Main PR in private repo: https://github.com/grafana/oncall-private/pull/1769
https://github.com/grafana/oncall-private/issues/1620

Jira inbound integration docs

---

grafana-plugin/src/containers/Alerts/Alerts.tsx

This PR rewrites the misleading warning:

Rewrite texts for ~Connectivity~ Notification Warning

---

engine/requirements.txt

[v1.2.18](https://github.com/grafana/oncall/releases/tag/v1.2.18) has some issues with parsing responses from Slack due to using `requests==2.30.0`, so pinning `requests` and `urllib3` to latest stable versions from [v1.2.17](https://github.com/grafana/oncall/releases/tag/v1.2.17).

Pin requests and urllib3

---

engine/apps/integrations/templates/heartbeat_instructions/alertmanager.html
grafana-plugin/src/containers/HeartbeatModal/HeartbeatForm.tsx

There was an unnecessary indentation in the `rules:` key which made it invalid YAML.
Also replaced the mentions to Amixr with Grafana OnCall, used some `<code>` tags and reworded some sentences.
Also removed the anchor tag from the webhook link: we don't want people to follow that in their browser, we want them to copy it

Fix and tidy alertmanager heartbeat template

---

.drone.yml

The Lint Backend step was renamed to Lint Everything [here](https://github.com/grafana/oncall/pull/1849/files#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7)

Fix renamed step in drone deps

---

engine/apps/grafana_plugin/apps.py
engine/apps/integrations/mixins/alert_channel_defining_mixin.py
engine/engine/celery.py

https://www.loom.com/share/18cc445117de4895a10892d56c7d3699
In preparation to upgrade our cloud databases, this PR makes some minor changes which, after testing locally, allowed the `POST /<integration_type>/<alert_channel_key>` endpoints to successfully receive incoming alerts and queue the celery tasks.
I've tested all of the defined `POST /integrations/v1/<integration_type>/<alert_channel_key>` endpoints by sending `POST` requests to an integrations' URL while the MySQL database was down, bringing the database back up, and ensuring the alerts were created.
- the integration heartbeat endpoints will not work as we interact w/ the database to persist the incoming heartbeat instance
- if the integration was created in the last 180 seconds, incoming alerts will fail due to the way we cache …

allow the POST incoming alert endpoints to queue create_alert tasks independent of the database status

---

CHANGELOG.md
docs/sources/open-source/_index.md
engine/apps/slack/scenarios/profile_update.py
engine/apps/slack/scenarios/scenario_step.py
engine/apps/slack/views.py

Adds a handler for [user_profile_changed](https://api.slack.com/events/user_profile_changed) Slack event + updates the Slack app manifest.
This is needed to replace [user_change](https://api.slack.com/events/user_change) event with [user_profile_changed](https://api.slack.com/events/user_profile_changed) event, since using `user_change` can cause a lot of excessive requests from Slack.
Might be related to https://github.com/grafana/oncall-private/issues/1803

Slack: use `user_profile_changed` event instead of `user_change`

---

CHANGELOG.md
grafana-plugin/src/components/Policy/EscalationPolicy.tsx
grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx

Fixed bug in Escalation Chains where reordering an item crashed the list
#1936

Fix escalation reordering

---

engine/apps/grafana_plugin/helpers/client.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py

Organizations that have been deleted outside OnCall were not being cleaned up by this task as expected.
- Use PluginAuthToken instead of GCOM token == None to determine if the oncall organization should be matched in GCOM
- Fix how delete was being checked for the instance, the previous method does not work.

Fix organizations not being deleted by start_cleanup_deleted_organizations

---

CHANGELOG.md
engine/apps/email/inbound.py

Fix inbound email endpoint bug when attaching files to email leads to HTTP 500.

Fix inbound email bug when attaching files

---

CHANGELOG.md
docker-compose-developer.yml
engine/settings/base.py

Allow passing Google application credentials (used to send FCM messages using `fcm-django`) as an environment variable `GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64`. If the env variable is not provided, credentials will be taken from file. This change allows uWSGI workers send messages to FCM (currently it's not possible because the uWSGI user doesn't have access to the credentials file) + makes configuration more consistent.
Also removes a redundant `FCM_PROJECT_ID` env variable (Google application credentials already contain the project ID).

Allow passing Firebase credentials via environment variable

---

docker-compose-developer.yml
engine/settings/base.py

Bring back `FCM_PROJECT_ID` env variable that was removed in https://github.com/grafana/oncall/pull/1969.
I made an incorrect assumption that project ID is already specified in the credentials file, but in fact project ID can be different from the one in credentials file.

Bring back FCM_PROJECT_ID env variable

---

CHANGELOG.md
engine/Dockerfile
engine/apps/telegram/views.py
engine/engine/celery.py
engine/engine/management/commands/create_sqlite_db.py

Fixes https://github.com/grafana/oncall/issues/1960.

Fix SQLite permission issue

---

grafana-plugin/src/components/Timeline/Timeline.module.css
grafana-plugin/src/components/Timeline/TimelineItem.tsx
grafana-plugin/src/containers/AlertRules/parts/index.tsx
grafana-plugin/src/containers/GSelect/GSelect.tsx
grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.tsx

- Hide timeline numbering when `isDisabled` is being sent
- Fixed tooltips within expanded route for escalation chains actions
- Replaced GSelect with Select to allow refreshing list manually

Templates tweaks

---

CHANGELOG.md
engine/apps/auth_token/auth.py
engine/apps/auth_token/models/plugin_auth_token.py
engine/apps/auth_token/tests/test_plugin_auth.py
engine/apps/grafana_plugin/helpers/gcom.py

Handle different failing authentication scenarios (e.g. when token is invalid or instance context is not a valid JSON) so endpoints return appropriate response code (401 instead of 500).
Related to https://github.com/grafana/oncall-private/issues/1633

Improve plugin authentication

---

.github/workflows/linting-and-tests.yml
grafana-plugin/integration-tests/globalSetup.ts
grafana-plugin/playwright.config.ts

Occasionally, the Playwright global setup step (which authenticates w/ the Grafana API + configures the plugin) would fail, leading to the CI job to instantly fail (playwright doesn't retry global setup if it fails).
My current hypothesis as to why this is happening is because the `oncall-engine` and `oncall-celery` pods aren't _actually_  ready in these cases based on the way the `jupyterhub/action-k8s-await-workloads` action await k8s workloads:
By using the `kubectl rollout status deployment/<deployment-name> --timeout=300s` instead, we can be sure that these pods are _actually_ ready to receive traffic before we start the tests.
```bash
❯ kubectl rollout status --help
Show the status of the rollout.
By default 'rollout status' will watch the status of the latest rollout until it's …
```

e2e tests on CI - actually await k8s resources to be ready before starting tests

---

CHANGELOG.md
engine/apps/mobile_app/tasks.py
engine/apps/mobile_app/tests/test_your_going_oncall_notification.py

Remove user defined time period from "you're going oncall" mobile push 

---

engine/apps/mobile_app/tasks.py

This message appears very frequently in our logs and does not seem to be useful.  Please comment and close if this message is useful to you.

Remove spammy log message for device not setup

---

engine/apps/mobile_app/tasks.py

when running the mobile app (emulator) + OnCall locally and trying to trigger "You're Going OnCall" push notifications, I was seeing this in the `celery` logs:
```bash
2023-05-24 21:39:54,032 source=engine:celery worker=ForkPoolWorker-3 task_id=cf9e5b52-a213-430a-8e3c-d6c3bed53318 task_name=apps.mobile_app.tasks.conditionally_send_going_oncall_push_notifications_for_schedule name=celery.app.trace level=INFO Task apps.mobile_app.tasks.conditionally_send_going_oncall_push_notifications_for_schedule[cf9e5b52-a213-430a-8e3c-d6c3bed53318] retry: Retry in 2s: NameError("name 'MobileAppUserSettings' is not defined")
```
This PR patches that by adding the import (inside the relevant function, to avoid circular imports). After adding this import, I am seeing push notifications being sent …

fix import issue which affected going oncall push notification

---

CHANGELOG.md
engine/apps/slack/scenarios/resolution_note.py
engine/apps/slack/tests/test_scenario_steps/test_resolution_note.py

Handle HTTP 500 error when attempting to update resolution note modal window that was already closed by user.
Related to https://github.com/grafana/oncall-private/issues/1834

Handle error when updating closed modal window in Slack

---

engine/apps/mobile_app/tasks.py
engine/engine/middlewares.py

- update engine log format to include `org_slug` + `user_agent`
```bash
2023-05-25 11:28:22 source=engine:app google_trace_id=none logger=root inbound latency=0.33164 status=200 method=GET path=/api/internal/v1/alertgroups/stats user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 content-length=0 slow=0 user_id=1 org_id=1 org_slug=self_hosted_org
2023-05-25 11:28:23 source=engine:app google_trace_id=none logger=root inbound latency=0.402866 status=200 method=GET path=/api/internal/v1/alertgroups user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 content-length=0 slow=0 user_id=1 org_id=1 org_slug=self_hosted_org
```
- log out device …

update engine log format + log out device type when sending push notifications

---

CHANGELOG.md
engine/apps/schedules/models/custom_on_call_shift.py
engine/apps/schedules/tasks/drop_cached_ical.py
engine/apps/schedules/tests/test_tasks_drop_cached_ical.py

Make sure the final schedule is refreshed after dropping the cached ical representations (sometimes the refresh final task was completed before the cached ical files were refreshed).

Refresh final schedule after cached icals are dropped

---

CHANGELOG.md
engine/apps/mobile_app/alert_rendering.py
engine/apps/mobile_app/tasks.py

changed notification title and subtitle; removed body

---

CHANGELOG.md
engine/apps/api/serializers/on_call_shifts.py
engine/apps/api/tests/test_oncall_shift.py
grafana-plugin/src/containers/RotationForm/RotationForm.tsx

Make it possible to select "by day" active periods for every shift frequency (ie. enable it for hourly and monthly recurrent rotations).

Enable selecting active days for every shift freq

---

CHANGELOG.md
helm/oncall/templates/_env.tpl
helm/oncall/templates/_helpers.tpl
helm/oncall/tests/uwsgi_env_test.yaml
helm/oncall/values.yaml

Adds `uwsgi` configuration to helm chart.
Sets environment variables with name capitalized and prefixed with `UWSGI_`, and dashes are substituted with underscores like described [here](https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#environment-variables)
Sets `UWSGI_LISTEN=1024` by default, but can be overwritten or completely removed by `uwsgi: null`
Or is it better to not specify default value (it's not backward compatible)?
Also, small indentation fixes for postgresql configuration.
closes https://github.com/grafana/oncall/issues/562
Also, [this PR](https://github.com/grafana/oncall/pull/856) has been closed because of this PR

Helm chart: added configuration of uwsgi using environment variables

---

CHANGELOG.md
engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
engine/apps/alerts/tests/test_grafana_alerting_sync.py

Fixes issue when syncing contact points and there are receiver configs with no `grafana_managed_receiver_configs` key.
(eg. `{"name": "autogen-contact-point-default"}`)

Update find contact point name, receiver could be missing key

---

grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx

- Edits the send important notification button to be send critical notification button to align with the app conventions
Ref #2043

Edit critical to be  Important to align with the rest of app convention

---

CHANGELOG.md
engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/tests/test_alert_receive_channel_template.py

Continue the work, started in https://github.com/grafana/oncall/pull/2061. 
Check if slack or telegram integration is enabled to include related templates in the response
https://github.com/grafana/oncall/issues/1889

Fix 500 on templates when slack or tg integration is disabled

---

CHANGELOG.md
grafana-plugin/src/containers/UserSettings/parts/tabs/TelegramInfo/TelegramInfo.tsx

Changes a required role for telegram user settings from Admin to Editor.
closes https://github.com/grafana/oncall/issues/1617

Fix a bug #1617 with permissions for telegram user settings

---

docs/sources/get-started/_index.md

Link to the jinja2-templating page was not stepping backwards one level in the directory, therefore linking to a 404.

Fix relative link to resolve 404 error

---

CHANGELOG.md
engine/apps/alerts/tasks/notify_ical_schedule_shift.py
engine/apps/alerts/tests/test_notify_ical_schedule_shift.py

Before this change, a diff ical check (which happens with frequency with imported ical), particularly with overrides in an API/terraform schedule would trigger unexpected slack notifications because the prev vs current ical comparison will flag a diff, but when comparing current and previous shifts, `current_shifts` will have the shift in progress while the `prev_shifts` calculated from the overrides-only diff will most of the time be empty (unless you set/change an override at current time).
Simplified the checks to always compare previous current shifts (ie. the ones in the schedule from the DB) vs the recalculated ones using the (refreshed) ical data from the schedule.

Trigger slack shift notifications on current shift change

---

CHANGELOG.md
engine/apps/alerts/models/alert_receive_channel.py
engine/apps/alerts/tests/test_alert_receiver_channel.py
engine/apps/alerts/tests/test_default_templates.py
engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/api/views/alert_receive_channel.py
engine/config_integrations/direct_paging.py
engine/config_integrations/heartbeat.py
engine/config_integrations/inbound_email.py
engine/config_integrations/maintenance.py
engine/config_integrations/manual.py
engine/config_integrations/slack_channel.py

Fix HTTP 500 when sending demo alert for inbound integration email. 
- Make all integration configs have consistent `is_demo_alert_enabled` and `example_payload` values
- Add tests

Fix demo alert for inbound email

---

engine/apps/twilioapp/views.py

Fixes an issue where if a sender is defined for a certain country code and that sender belongs to a different account than the default from the environment the status callback would get a 443 response from OnCall back to Twilio.  Checking permission on status callbacks will now use the same account as was used to send the original message, verify, or make the call.

Use same account for status callback when using TwilioSender

---

CHANGELOG.md
engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
engine/apps/schedules/ical_utils.py
engine/apps/schedules/tests/test_ical_utils.py

When checking current shifts to trigger slack notifications, a stable value for timezone should be used (to avoid triggering multiple duplicated notifications; using the first `VTIMEZONE` value available may change on refresh, besides being potentially incorrect).
Also, `VTIMEZONE` shouldn't be used as the calendar timezone, it just describes a [timezone definition](https://icalendar.org/iCalendar-RFC-5545/3-6-5-time-zone-component.html) which can later be [used when specifying a start/end date/datetime](https://icalendar.org/iCalendar-RFC-5545/3-2-19-time-zone-identifier.html) ("The parameter MUST be specified on properties with a DATE-TIME value if the DATE-TIME is not either a UTC or a "floating" time.").
OTOH, Google uses the non-standard[ `X-WR-TIMEZONE` …

Use X-WR-TIMEZONE as calendar tz when available, fallback to UTC

---

engine/apps/api/serializers/webhook.py
engine/apps/api/tests/test_webhooks.py
engine/apps/webhooks/models/webhook.py
engine/apps/webhooks/tasks/trigger_webhook.py
grafana-plugin/src/containers/OutgoingWebhook2Form/OutgoingWebhook2Form.config.tsx

Replace password and authorization header fields with placeholders when returning data to the UI.  Mask the authorization header field when editing and in the status logs.

Webhooks 2 hide secrets

---

.github/workflows/triage-stale-pull-requests.yml

Use [this](https://github.com/actions/stale) GitHub Action to run a cron-job every morning to triage stale pull requests. The messages posted to the pull request when stale/closed were borrowed from the `grafana/grafana` repo ([example](https://github.com/grafana/grafana/pull/65754)).

add github action to triage stale pull requests

---

CHANGELOG.md
docs/sources/oncall-api-reference/integrations.md
engine/apps/alerts/models/alert_receive_channel.py
engine/apps/public_api/serializers/integrations.py
engine/apps/public_api/tests/test_integrations.py

Allows fetching inbound email address for an integration using public API. There's a new field `inbound_email` that's only defined for inbound email integration and `null` for any other integration types.
https://github.com/grafana/oncall/issues/1989

Add inbound email address in integration API

---

CHANGELOG.md
engine/apps/api/tests/test_live_settings.py
engine/apps/api/views/live_setting.py
engine/apps/base/models/live_setting.py
engine/apps/base/utils.py
engine/apps/telegram/client.py

Fixes https://github.com/grafana/oncall/issues/1103, inspired by https://github.com/grafana/oncall/pull/1934.
Makes sure that:
1. `LiveSettings.validate_settings` is only called once per update request and not called for any individual LiveSetting instance save.
2. `telegram.Bot.set_webhook` is only called once per request when changing `TELEGRAM_WEBHOOK_HOST`.
https://github.com/grafana/oncall/issues/1103

Fix Telegram ratelimit on live setting change

---

CHANGELOG.md
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/api/tests/test_channel_filter.py
engine/apps/api/views/alert_receive_channel.py
engine/apps/api/views/channel_filter.py
engine/apps/api/views/escalation_chain.py
engine/apps/api/views/escalation_policy.py
engine/apps/api/views/user.py
engine/apps/api/views/user_notification_policy.py
engine/apps/public_api/views/maintaiable_object_mixin.py
engine/apps/public_api/views/schedules.py
engine/apps/public_api/views/users.py
engine/common/api_helpers/mixins.py
engine/common/api_helpers/serializers.py
engine/common/tests/test_viewset_actions.py

Makes sure that all viewset actions with `detail=True` use `self.get_object()` to retrieve an instance that's being acted upon.

Make viewset actions more consistent

---

engine/apps/api/serializers/on_call_shifts.py
engine/apps/api/tests/test_oncall_shift.py
grafana-plugin/src/containers/RotationForm/RotationForm.tsx
grafana-plugin/src/models/schedule/schedule.types.ts
grafana-plugin/src/pages/schedule/Schedule.helpers.ts

Reworked https://github.com/grafana/oncall/pull/2124

Update shift week_start when translating to UTC

---

CHANGELOG.md
engine/apps/api/tests/test_alert_group.py
engine/apps/api/views/alert_group.py

We were noticing some discrepancies in alert groups counts.
From a real example:
```
>>> qs = queryset.filter(channel_filter__alert_receive_channel=arc)
>>> qs.filter(resolved_at__isnull=False).count()
1318
>>> qs = queryset.filter(channel=arc)
>>> qs.filter(resolved_at__isnull=False).count()
1356
>>> qs.filter(resolved_at__isnull=False, channel_filter__isnull=True).count()
38
```

Update alert group view receive channel filter

---

engine/apps/api/serializers/on_call_shifts.py
engine/apps/api/tests/test_oncall_shift.py

Related to https://github.com/grafana/oncall/issues/2118#issuecomment-1580390309

Require users before creating/updating shift

---

grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx

Changes on MobileApp screen
- Switched buttons to `secondary` instead of `destructive`
- Update copy (Send Test Push/Important) + notification copy

Use secondary btn, updated copies on MobileApp Send Push

---

engine/apps/metrics_exporter/metrics_collectors.py
engine/apps/metrics_exporter/tests/conftest.py

Eventually we could also process orgs by chunks.

Refactor metrics exporter to use `cache.get_many`

---

CHANGELOG.md
engine/apps/api/permissions.py
engine/apps/api/serializers/user.py
engine/apps/api/tests/test_user.py

Remove deprecated `permissions` `List[str]` from internal API user response. These permission strings are no longer used and AFAICT are not referenced anywhere in the UI.

remove legacy permission strings

---

grafana-plugin/src/containers/RotationForm/RotationForm.tsx
grafana-plugin/src/pages/schedule/Schedule.helpers.ts

On shift update, rotation start will be set to current time, prefer shift start instead when calculating the day/week start mapping.

Update UTC day mapping to use shift start

---

engine/Dockerfile

install `requirements-dev.txt` dependencies oncall docker image dev target to allow commands like `make test` to properly work. Otherwise you currently get:
```bash
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "pytest": executable file not found in $PATH: unknown
make: *** [test] Error 1
```

install requirements-dev.txt dependencies oncall docker image dev target

---

CHANGELOG.md
engine/apps/api/serializers/on_call_shifts.py
engine/apps/api/tests/test_oncall_shift.py
engine/apps/schedules/models/custom_on_call_shift.py
engine/apps/schedules/tests/test_custom_on_call_shift.py

Updating a schedule using the web UI sometimes you don't get the change immediately available (since the ical refresh is async). 
Related to https://github.com/grafana/oncall/issues/1968

Changed web schedule updates to sync refresh ical

---

CHANGELOG.md
grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
grafana-plugin/src/plugin.json

Add dashboard for oncall metrics to the plugin settings by following [this instruction](https://community.grafana.com/t/how-to-include-dashboards-in-your-data-source-plugin/62749). Dashboards files should be in `.json` format and stored in the plugin's directory in `/src/dashboards/`.
As the result the dashboard can be imported from the `Dashboards` tab at the plugin settings page:

Add dashboard for oncall metrics to provisioning plugin settings

---

grafana-plugin/src/components/HamburgerMenu/HamburgerMenu.module.scss
grafana-plugin/src/containers/IntegrationContainers/ExpandedIntegrationRouteDisplay/ExpandedIntegrationRouteDisplay.module.scss
grafana-plugin/src/style/vars.css

- light theme fixes for templates&grouping

light theme fixes

---

grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts
grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
grafana-plugin/src/containers/TemplatePreview/TemplatePreview.module.css
grafana-plugin/src/containers/TemplatePreview/TemplatePreview.tsx

Fix template preview markup

---

engine/apps/metrics_exporter/tasks.py

The `prefecth_related` data here is not being used later (since we are applying filters not getting `.all`) and it is preloading all alert groups for integrations into memory (which can be a lot).

Remove unused prefetch_related in metrics task

---

CHANGELOG.md
engine/apps/phone_notifications/phone_backend.py
engine/apps/phone_notifications/tests/test_phone_backend_oss_relay.py

Fix incorrect order of arguments for phone provider method invocations when relaying phone calls and SMS from OSS instances.

Fix phone call & SMS relay

---

grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts
grafana-plugin/src/containers/IntegrationContainers/IntegrationCommonTemplatesList.config.ts

Slack was prior to this using the wrong key to display the name of the template

Use correct slack key/display_name in templates

---

grafana-plugin/src/components/ScheduleQualityDetails/ScheduleQualityDetails.tsx

Fixes https://github.com/grafana/oncall/issues/2357
Old link (404): https://grafana.com/docs/oncall/latest/calendar-schedules/web-schedule/#schedule-quality-report 
New link: https://grafana.com/docs/oncall/latest/on-call-schedules/web-schedule/#schedule-quality-report

Fix 404 link for schedule quality

---

grafana-plugin/.gitignore
grafana-plugin/integration-tests/globalSetup.ts
grafana-plugin/playwright.config.ts

In the e2e tests, await the grafana instance if it is currently down/unavailable. This is mostly useful for when the tests are run against a hosted grafana instance and it is possible that the instance is paused ([example build](https://drone.grafana.net/grafana/oncall-private/5735/1/4)).
https://www.loom.com/share/35eb49035d454ac6ba306cddfe63f255

in the e2e tests, await the grafana instance if it is currently down/unavailable

---

.drone.yml
.github/workflows/linting-and-tests.yml
docker-compose-developer.yml
docker-compose-mysql-rabbitmq.yml

Update `rabbitmq` Docker containers used in the `docker-compose` config files, Drone pipelines, and GitHub Actions to use version 3.12.0.
FWIW, we're already using v12.0.0 of the bitnami `rabbitmq` `helm` chart which, by default, uses the `3.12.0-debian-11-r0` tag for the `rabbitmq` image ([chart docs](https://artifacthub.io/packages/helm/bitnami/rabbitmq/12.0.0)).
closes #695

update rabbitmq docker containers to v3.12.0

---

.drone.yml

`docker buildx` natively supports multiarch builds. This means we no longer need to have duplicate `docker build` Drone steps + there is no longer a need for the manual "manifesting" step. This [blog post](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) from Docker perfectly summarizes the difference between what we do now vs. what this PR would do.
This would also get rid of pushing `vX.Y.Z-{architecture}` tagged images. These are redundant because modern `docker` clients can pull the appropriate image for the host OS, from a multiarch image:

use docker buildx native multiarch image support

---

CHANGELOG.md
docs/sources/oncall-api-reference/alerts.md
engine/apps/public_api/tests/test_alerts.py
engine/apps/public_api/views/alerts.py

Change alerts order in `/alert` public api endpoint
https://github.com/grafana/oncall/issues/1031

Fix alerts order in public api

---

engine/apps/slack/views.py

Simplifies `_get_organization_from_payload` and `_get_slack_team_identity_from_payload` methods on `SlackEventApiEndpointView`, so it's (hopefully) easier to grasp.

Simplify `SlackEventApiEndpointView` methods

---

CHANGELOG.md
grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.test.tsx
grafana-plugin/src/containers/PluginConfigPage/PluginConfigPage.tsx
grafana-plugin/src/containers/PluginConfigPage/__snapshots__/PluginConfigPage.test.tsx.snap
grafana-plugin/src/state/plugin/index.ts

Remove attempt to check token when editor/viewers are accessing the plugin. Only check the token for reinstall during sync from the PluginConfigPage since only Admins would have access to it.

Remove attempt to check token when editor/viewers are accessing the plugin

---

CHANGELOG.md
engine/apps/api/tests/test_schedules.py
engine/apps/user_management/models/user.py

Adds full avatar URL for on-call users in schedule internal API (`avatar_full`).

Add full avatar URL for on-call users in schedule internal API

---

engine/apps/mobile_app/auth.py
engine/apps/user_management/middlewares.py

Add organization moved exception to mobile app auth to redirect requests to correct region

Add organization moved exception to mobile app auth

---

engine/apps/mobile_app/tasks.py
engine/apps/slack/scenarios/step_mixins.py
engine/apps/telegram/updates/update_handlers/button_press.py
engine/apps/telegram/updates/update_manager.py
engine/apps/twilioapp/phone_provider.py
engine/pyproject.toml

Fix the following `return` `mypy` errors (related to #2392):
```bash
❯ mypy .
apps/telegram/updates/update_manager.py:36: error: Missing return statement  [return]
apps/slack/scenarios/step_mixins.py:109: error: Missing return statement  [return]
apps/mobile_app/tasks.py:368: error: Missing return statement  [return]
apps/telegram/updates/update_handlers/button_press.py:48: error: Missing return statement  [return]
apps/twilioapp/phone_provider.py:28: error: Missing return statement  [return]
apps/twilioapp/phone_provider.py:61: error: Missing return statement  [return]
Found 6 errors in 5 files (checked 595 source files)
```

fix mypy return errors

---

CHANGELOG.md
engine/apps/api/tests/test_oncall_shift.py
engine/apps/api/tests/test_schedules.py
engine/apps/api/views/schedule.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py
engine/common/api_helpers/utils.py

add user (full) avatar to schedule filter events internal API endpoint

---

CHANGELOG.md
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/api/tests/test_schedules.py
engine/apps/api/views/alert_receive_channel.py
engine/apps/api/views/schedule.py
engine/common/api_helpers/paginators.py

closes https://github.com/grafana/oncall/issues/2463

fix pagination next and previous links for schedules and integrations GET endpoints

---

CHANGELOG.md
engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/tests/test_gcom_api_client.py

Grafana provides two methods for enabling feature flags:
- `feature_toggles.enabled`
- `feature_toggles.<name_of_feature_flag>`
For example, to enable `accessControlOnCall` you could either do:
```json
{
"feature_toggles": {
"enabled": "accessControlOnCall,someOtherCoolFeatureFlag"
}
}
```
or:
```json
{
"feature_toggles": {
"accessControlOnCall": true,
"someOtherCoolFeatureFlag": true
}
}
```
In method 1, if they're multiple feature flags present, they are _comma separated, not space separated_. This PR fixes this parsing issue.

fix parsing of grafana feature flags that're enabled via the feature_toggles.enabled syntax

---

docs/sources/_index.md

The doc squad is restructuring the Grafana Cloud TOC to align with UI navigation. This PR makes minor changes to the source _index.md file frontmatter in support of these changes.
Changed weight to 500 to manipulate order or doc sets and added menuTitle field to remove "Grafana" from TOC title for consistency.

adjust frontmatter weight and add menu title

---

CHANGELOG.md
engine/common/tests/test_markup.py
engine/common/utils.py

Fixes an issue when alert group list page fails to load if any alert group on the page has `- - ` substring in its message.

Fix cuddled list Markdown issue

---

CHANGELOG.md
engine/apps/alerts/tasks/notify_ical_schedule_shift.py
engine/apps/schedules/tasks/refresh_ical_files.py
engine/apps/schedules/tests/test_tasks_refresh_ical_files.py

On notifying about shifts change in slack we don't check whether organization was deleted. This PR excludes schedules from deleted organizations from shift notification list

Exclude schedules from deleted organizations from notification list

---

.github/CODEOWNERS

Fixes the CODEOWNERS file which is marked as invalid because of the team name change.
The team will need to be given write access to the repository by a repository admin.
https://github.com/orgs/grafana/teams/docs-gops is the team.

Update team name: grafana/docs-oncall is now grafana/docs-gops

---

engine/requirements.txt

I was seeing some strange logs occasionally pop up from celery:
```bash
[1;33m2023-07-13 10:05:14,772 source=engine:celery worker=MainProcess task_id=??? task_name=??? name=celery.redirected level=WARNING AttributeError: '_Code' object has no attribute 'co_positions'[0m
```
Did a bit of digging on this and [realized](https://github.com/DataDog/dd-trace-py/issues/4149) that `celery==5.2.7` does not support Python 3.11 (the version we use):
We should immediately upgrade to `celery==5.3.1`. It mentions in this in the changelog for that version:

bump celery version to a version which supports Python 3.11

---

CHANGELOG.md
engine/apps/webhooks/tasks/trigger_webhook.py

Fix authorization header was being masked in the requests instead of only in logs

Fix authorization header masked

---

docs/sources/mobile-app/alert-groups-feed/index.md
docs/sources/user-and-team-management/_index.md

- Update docs to callout permission requirement in mobile app doc for responding to alert group.
- Update link to RBAC fixed role doc for mapping between OnCall RBAC fixed role and Grafana basic role.

Docs: Update oncall rbac detail

---

.github/workflows/linting-and-tests.yml
.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml

My previous PR only updated the CI that ran on PRs, I forgot about the CD for releases.
Fixes https://github.com/grafana/oncall/actions/runs/5547818896.
You can see that this will resolve the problem because it is what allows the PR CI to pass. I just forgot to include it in the release CD.

Update all make docs CI to match

---

.drone.yml
CHANGELOG.md

Related to https://github.com/grafana/oncall/issues/458
Change version naming for plugin and docker releases to drop the `v` prefix (ie. `1.2.3` instead of `v1.2.3`).
Update both to keep consistency between plugin and engine versions, which are also checked to match.

Remove v prefix from plugin version on build

---

CHANGELOG.md
engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
engine/apps/alerts/models/alert_group.py
engine/apps/alerts/paging.py
engine/apps/api/serializers/alert_group.py
engine/apps/slack/scenarios/distribute_alerts.py
engine/apps/slack/scenarios/manage_responders.py
engine/apps/slack/scenarios/paging.py
engine/apps/slack/tests/test_interactive_api_endpoint.py
engine/apps/slack/tests/test_scenario_steps/test_manage_responders.py
engine/apps/slack/tests/test_slack_renderer.py
engine/apps/slack/views.py

Refactors the "invite" functionality in Slack to use direct paging and be more consistent with the web UI and `/escalate` Slack command.
Before:
After (replace "Invite..." dropdown with "Responders" button, swap it with the silence button):
The following modal opens up with a list of currently paged users and inputs to page more users/schedules:
This is supposed to be the Slack equivalent of this part of the web UI:
https://github.com/grafana/oncall/issues/2336

Update Slack "invite" feature to use direct paging

---

CHANGELOG.md
grafana-plugin/src/pages/incident/parts/PagedUsers.tsx

Changes wording so it's clear that only "additional" responders (i.e. users paged through direct paging) are shown in this section, and users paged via escalation chain are not shown.
Before:
After:

Current responders -> Additional Responders

---

CHANGELOG.md
engine/apps/slack/slack_client/slack_client.py
engine/apps/slack/tasks.py
engine/apps/slack/tests/test_populate_slack_channels.py
engine/apps/slack/utils.py

- Fixes issue with slack channels sync periodic tasks when we get slack rate limit exception.
- Adds check for active task id to avoid starting multiple tasks for one slack team.
Collecting channels for slack for some teams causes rate limit exception, which causes the task to restart and start collecting slack channels from the beginning. This PR adds new paginated api call and refactors the slack channel sync task to continue collect data after rate limit from the step before it was raised using `cursor` value from the slack response.

Fix slack channels sync

---

CHANGELOG.md
docs/sources/integrations/manual/index.md
docs/sources/notify/slack/index.md
engine/apps/slack/scenarios/paging.py
grafana-plugin/src/components/ManualAlertGroup/ManualAlertGroup.tsx

Updates public docs on direct paging after introducing numerous changes to the feature.
https://github.com/grafana/oncall/assets/20116910/f141e8b1-ac2c-455c-81f8-9c62c4c75234

Update direct paging docs

---

CHANGELOG.md
engine/apps/api/serializers/webhook.py
engine/apps/api/tests/test_webhooks.py

When a webhook is being copied if it contains a password or authorization header reference the original webhook to get this data since it has been masked in the input data.
Fixes #2604

Check original webhook for sensitive fields when copying

---

CHANGELOG.md
engine/apps/public_api/serializers/escalation_policies.py
engine/apps/public_api/serializers/routes.py
engine/apps/public_api/serializers/schedules_calendar.py
engine/apps/public_api/serializers/schedules_web.py
terraform/README.md

Removes unnecessary team checks enforced by public API, as they seem to be outdated and not aligned with the web UI and docs.
From public [docs](https://grafana.com/docs/oncall/latest/user-and-team-management/#manage-teams-in-grafana-oncall):
> Resources from different teams can be connected with one another. For instance, you can create an integration in one team, set up multiple routes for the integration, and utilize escalation chains from other teams. Users, schedules, and outgoing webhooks from other teams can also be included in the escalation chain.

Remove unnecessary team checks

---

CHANGELOG.md
engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/tests/test_gcom_api_client.py

See the following threads for more context on the issue this PR addresses:
- https://raintank-corp.slack.com/archives/CRUKW54N5/p1690068395450819
- https://raintank-corp.slack.com/archives/C036J5B39/p1690183217162019

support comma and space delimited grafana feature_toggles

---

CHANGELOG.md
engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
engine/apps/alerts/tests/test_escalation_policy_snapshot.py
engine/apps/api/tests/test_schedules.py
engine/apps/api/views/on_call_shifts.py
engine/apps/api/views/schedule.py
engine/apps/mobile_app/tasks.py
engine/apps/public_api/views/schedules.py
engine/apps/schedules/ical_utils.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_ical_utils.py
engine/apps/schedules/tests/test_on_call_schedule.py
engine/apps/schedules/tests/test_quality_score.py

First step towards reusing `schedule.final_events` where current / upcoming schedule shifts information is needed (eg. escalations, shift notifications, etc)

Refactoring schedule final events for reusability

---

grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
grafana-plugin/src/state/rootBaseStore/index.ts

Adding additional `UpdateBasicData` after installation, to handle that case
1. Plugin calls `UpdateBasicData` in parallel to `setupPlugin` which handles sync/install
2. If plugin is not installed, `UpdateBasicData` from step 1 will fail with 403s

Update basic data after installation

---

grafana-plugin/src/plugin.json

This should enable users with the OnCaller role to be added in a schedule rotation.
Related to
https://github.com/grafana/support-escalations/issues/6883

Add notifications:read permission to OnCaller role

---

grafana-plugin/src/state/rootBaseStore/index.ts
grafana-plugin/src/state/rootBaseStore/rootBaseStore.test.ts

Redirect to PLUGIN_ROOT after plugin install

Use locationService.push after plugin install

---

CHANGELOG.md
engine/Dockerfile

Fixes an issue with [alerts.0028](https://github.com/grafana/oncall/blob/f77a54b518ab8f1f42e33ca43328b75fde1903b9/engine/apps/alerts/migrations/0028_drop_alertreceivechannel_restricted_at.py) migration failing on SQLite with the following error: `sqlite3.OperationalError: near "DROP": syntax error`. 
The issue is fixed by updating the SQLite version from `3.27.2` to `3.40.1` (SQLite `3.35.0` introduced native support for dropping columns as per this [SO answer](https://stackoverflow.com/a/66399224)).
However, I couldn't find an easy way to independently update SQLite, since it's bundled into Python's standard library.
Updating the Docker image to use the latest Debian stable release fixes the issue as it already comes with SQLite `3.40.1` out of the box. So this PR effectively bumps the …

Fix `alerts.0028` migration for SQLite

---

CHANGELOG.md
engine/apps/schedules/ical_utils.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/models/shift_swap_request.py
engine/apps/schedules/tests/test_custom_on_call_shift.py
engine/apps/schedules/tests/test_on_call_schedule.py
engine/apps/schedules/tests/test_shift_swap_request.py

Reflect swap requests details in schedule events.

Apply shift swap requests to schedule events

---

CHANGELOG.md
engine/apps/api/tests/test_schedules.py
engine/apps/api/tests/test_shift_swaps.py
engine/apps/api/views/schedule.py
engine/apps/schedules/models/on_call_schedule.py
engine/common/api_helpers/utils.py

Example request/response
`GET /api/internal/v1/schedules/SVV8E9JGLLR9T/filter_shift_swaps/?date=2023-07-22&days=9`
```
{
"shift_swaps": [
{
"id": "SSR1QJ93UNCUPC4",
"created_at": "2023-07-27T12:55:32.188232Z",
"updated_at": "2023-07-28T13:28:08.027124Z",
"status": "taken",
"schedule": "SVV8E9JGLLR9T",
"swap_start": "2023-07-24T21:00:00.000000Z",
"swap_end": "2023-08-04T03:00:00.000000Z",
"description": null,
"beneficiary": "UWJWIN8MQ1GYL",
"benefactor": "UVSKHRA4YU328"
}
]
}
```

Add filter_shift_swaps endpoint to schedules API

---

CHANGELOG.md
helm/oncall/templates/celery/_deployment.tpl
helm/oncall/templates/engine/deployment.yaml
helm/oncall/templates/engine/job-migrate.yaml
helm/oncall/tests/extra_containers_celery_test.yaml
helm/oncall/tests/extra_containers_engine_test.yaml
helm/oncall/tests/migrate_extra_containers_test.yaml
helm/oncall/values.yaml

Adds support for defining extra containers which run as sidecar alongside the celery and engine containers

add option for sidecar containers in helm chart

---

CHANGELOG.md
engine/apps/api/tests/test_shift_swaps.py
engine/apps/api/views/shift_swap.py
engine/apps/schedules/models/shift_swap_request.py
engine/apps/schedules/tests/test_shift_swap_request.py

Example request/response:
`GET /api/internal/v1/shift_swaps/SSR3FJC9H3HZCHT/shifts`
```
{
"events": [
{
"all_day": false,
"start": "2023-08-01T00:00:00Z",
"end": "2023-08-01T03:00:00Z",
"users": [
{
"display_name": "testing",
"email": "testing",
"pk": "UWJWIN8MQ1GYL",
"avatar_full": "http://localhost:3000/avatar/ae2b1fca515949e5d54fb22b8ed95575",
"swap_request": {
"pk": "SSR3FJC9H3HZCHT"
}
}
],
"missing_users": [],
"priority_level": 1,
"source": "web",
"calendar_type": 0,
"is_empty": false,
"is_gap": false,
"is_override": false,
"shift": {
"pk": "OK9SS5YP42XRG"
}
},
{
"all_day": false,
"start": "2023-08-01T03:00:00Z",
"end": "2023-08-02T00:00:00Z",
"users": [
{
"display_name": "testing",
"email": "testing",
"pk": "UWJWIN8MQ1GYL",
"avatar_full": …
```

Add list shifts for swap request endpoint

---

helm/oncall/templates/engine/deployment.yaml

fixes a bug introduced in #2655 where the `topologySpreadConstraints` helm values are not scoped correctly on the engine template.
closes #2655

fix bug introduced by #2655

---

CHANGELOG.md
engine/apps/slack/scenarios/paging.py
engine/apps/slack/tests/test_scenario_steps/test_paging.py

Adds stack slug to organization options for `/escalate` (a single Grafana org might have multiple stacks).

Add stack slug to organization options for direct paging

---

dev/README.md
docker-compose-developer.yml
docker-compose-mysql-rabbitmq.yml
docker-compose.yml

Tested `make start` w/ both `mysql` and `postgres` in `COMPOSE_PROFILES` and things spin up properly.
- Fixes some `yaml` formatting issues introduced [here](https://github.com/grafana/oncall/pull/2728/files#diff-f5d10b03472abe3719098ae8a8855468e92524ebe790c39a34d2c632f3f0486d) in #2728 which were causing the `mysql` container to fail to start up when running `make start`
- Addresses #2492 by specifying `required: false` under `depends_on`, for containers in `docker-compose-developer.yml` which have container(s) which may be conditionally spun-up based on `COMPOSE_PROFILES`. Basically in v2.20.2 they introduced [this change](https://github.com/docker/compose/releases/tag/v2.20.2#:~:text=Add%20support%20of%20depends_on.required%20attribute%20by) which was a breaking change for our setup …

fix make start command when using mysql/postgres as db

---

CHANGELOG.md
engine/apps/alerts/tasks/notify_ical_schedule_shift.py
engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/models/shift_swap_request.py
engine/apps/schedules/tests/test_on_call_schedule.py
engine/apps/schedules/tests/test_shift_swap_request.py

Avoid creating (or notifying) about potential event splits resulting from untaken swap requests.

Filter out untaken swaps from final schedule and shift notifications

---

CHANGELOG.md
grafana-plugin/src/containers/UserSettings/parts/tabs/CloudPhoneSettings/CloudPhoneSettings.tsx
grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx

Sets the correct permission when accessing Phone Verification screen (Cloud/OSS)
Fix for https://github.com/grafana/oncall/issues/2761

Use UserSettingsWrite instead of OtherSettingsWrite for phone tab

---

CHANGELOG.md
engine/apps/api/serializers/organization.py
engine/apps/api/tests/test_organization.py

Fixes issue with response 400 on update "Require resolution note" setting

Make field rbac_enabled readonly for organization endpoint

---

CHANGELOG.md
engine/apps/mobile_app/tasks.py
engine/apps/mobile_app/tests/test_shift_swap_request.py

Fixes a bug when a user is receiving push notifications about past SSRs after turning on the info notifications in the mobile app.

Don't send notifications about past SSRs when turning on info notifications

---

CHANGELOG.md
engine/apps/api/serializers/on_call_shifts.py
engine/apps/api/tests/test_oncall_shift.py

Fixes https://github.com/grafana/oncall-private/issues/2089

Add schedule shift type validation on create/preview

---

CHANGELOG.md
engine/config_integrations/alertmanager.py
engine/config_integrations/grafana_alerting.py

– Fix error with missing "groupLabels" or "alertname"
– Support rendering alerts from migrated legacy alertmanagers

Improve template to handle empty group labels

---

CHANGELOG.md
engine/apps/alerts/tests/test_alert_receiver_channel.py
engine/apps/integrations/metadata/heartbeat/__init__.py
engine/apps/integrations/metadata/heartbeat/alertmanager.py

Related to https://github.com/grafana/oncall/issues/2801 and https://github.com/grafana/support-escalations/issues/7081.

Add alertmanager integration for heartbeat support

---

CHANGELOG.md
engine/apps/alerts/models/escalation_policy.py
grafana-plugin/src/components/Policy/EscalationPolicy.tsx
grafana-plugin/src/components/TimeRange/TimeRange.tsx

~~Adds a boolean `convertToUTC` to the `TimeRange` component.~~ 
- Discard conversion to UTC of strings within `TimeRange` component
For this use case on escalation chains since the user inputted fields are strings they will not be further converted to UTC and instead left as it is, which previously resulted in setting a wrong start/end combination.
https://github.com/grafana/oncall/issues/2781

Prevent conversion of escalation start/end times to UTC

---

engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py

Set is_escalation_finished to True if alert group won't be escalated due to active maintenance, absence of escalation chain or being restricted
Fix logging

Set is_escalation_finished to True if alert group won't be escalated

---

grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
grafana-plugin/src/pages/integration/Integration.tsx

- Sort of fixed the stalling issue of the `counters` request - now just the very first request to `counters` would be slow, everything else just uses existing data we already fetched
- Added validation if contact point is already defined for the selected datasource for alerting

Added validation for existent contact point for grafana alerting

---

CHANGELOG.md
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py
engine/apps/schedules/tests/test_quality_score.py

When an event is split because of a swap request, we were including the original event if it was supposed to be in progress during the requested time span.

Check possible split events in range when resolving schedule

---

CHANGELOG.md
docker-compose-developer.yml
engine/apps/mobile_app/models.py
grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
grafana-plugin/webpack.config.js

Trying to connect a mobile app emulator, following the instructions [here](https://github.com/grafana/oncall-mobile-app#getting-started), to a cloud stack is incredibly difficult given the 1 minute token TTL. You need to retrieve the token from the HTTP response in your browser's inspect panel, plug that token into the `make run` command and cross your fingers that the emulator starts up in < 45 seconds before the token expires.
This PR increases the verification token TTL from 1 minute to 5 minutes.

increase mobile app verification token TTL from 1 minute to 5 minutes

---

.github/workflows/update-make-docs.yml

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

Add 'pr: no changelog' label because these PRs dont need to update the changelog

---

CHANGELOG.md
docs/sources/oncall-api-reference/schedules.md
engine/apps/public_api/tests/test_schedules.py
engine/apps/public_api/views/schedules.py

Related to https://github.com/grafana/oncall/issues/2799

Enable shifts export endpoint for all schedule types

---

engine/apps/grafana_plugin/tests/test_status.py
engine/apps/grafana_plugin/views/status.py
engine/common/api_helpers/mixins.py

When accessing the status endpoint using a mobile authentication token do not use headers that would only be available if the request came from Grafana.

Status to not access grafana headers from mobile request

---

engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
engine/apps/alerts/models/alert_group.py
engine/apps/alerts/tasks/check_escalation_finished.py
engine/apps/alerts/tests/test_alert_group.py
engine/apps/alerts/tests/test_check_escalation_finished_task.py
engine/apps/alerts/tests/test_escalation_snapshot_mixin.py

Update `next_step_eta` in alert group escalation snapshot when alert group is silenced for period
Fixes the issue related to [this one](https://github.com/grafana/oncall-private/issues/2028)

Fix next step eta for silenced alert groups

---

CHANGELOG.md
engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py

Fixes an issue where OnCall could not parse Alerting configuration if there was a route created without a receiver.  The case where this comes up is a notification policy matcher is defined for the purpose of ignoring certain label values before continuing on to other matching rules.

Alerting integration use get for receiver key

---

engine/apps/integrations/views.py

If the same heartbeat is requested at a high rate it can create lock contention when updating the timestamp in the DB. Moving to always run update in task should free up the connection on the API server faster, although the task might still see some lock wait time.

Always update last_heartbeat_time async

---

engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
engine/apps/alerts/tests/test_escalation_policy_snapshot.py

Set next step eta to None if escalation was paused (escalation step "Continue escalation if num alerts > X in time window"
https://github.com/grafana/oncall-private/issues/2028

Set next step eta to None if escalation was paused

---

engine/apps/alerts/models/escalation_policy.py

Make descriptions consistent for the `STEP_NOTIFY_IF_TIME` escalation step (my [initial assumption](https://github.com/grafana/oncall/pull/2729#discussion_r1281929984) seems to be wrong and this can confuse users).
https://github.com/grafana/support-escalations/issues/7164

Update `STEP_NOTIFY_IF_TIME` step description

---

CHANGELOG.md
engine/apps/api/serializers/shift_swap.py
engine/apps/api/tests/test_schedules.py
engine/apps/api/views/schedule.py

Include additional information about beneficiary/benefactor users to avoid extra requests when listing swap requests details.

Expand users details in filter swaps endpoint

---

CHANGELOG.md
engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
engine/apps/alerts/tests/test_escalation_snapshot_mixin.py

Fix silence for paused escalations or alert groups with empty escalation chain
https://github.com/grafana/oncall/issues/2912

Fix silence for paused escalations or alert groups with empty escalation chain

---

CHANGELOG.md
engine/apps/alerts/escalation_snapshot/serializers/escalation_policy_snapshot.py
engine/apps/alerts/tests/test_escalation_snapshot.py
engine/apps/api/tests/test_escalation_policy.py

Fix escalation snapshot building if last notified user in escalation step "Notify users one by one (round-robin)" was deleted
https://github.com/grafana/oncall-private/issues/2148

Fix build escalation snapshot

---

CHANGELOG.md
helm/oncall/values.yaml

Set `oncall.smtp.enabled` to `true` by default to enable email notifications on Helm deployments.
Email notifications are enabled by default on docker-compose deployments already: see [this feature flag](https://github.com/grafana/oncall/blob/df6f6183ecc9e541d07317590db9d3affb7097ab/engine/settings/base.py#L63).
https://github.com/grafana/oncall/issues/2917

Enable email notification step by default on Helm

---

CHANGELOG.md
engine/apps/slack/tasks.py
engine/apps/slack/tests/test_user_group.py

Make sure that Slack user groups are not getting updated for deleted orgs.
Without this change, there could be issues with backends in multiple clusters trying to update a single Slack user group after migrating an org to another cluster (organizations get soft deleted from the original cluster after migration).
https://github.com/grafana/support-escalations/issues/6936

Don't update Slack user groups for deleted organizations

---

CHANGELOG.md
engine/apps/slack/tasks.py
engine/apps/slack/tests/test_reset_slack.py

Improve Slack disconnect cleanup:
- Reset Slack user group for schedules
- Reset Slack user identity for deleted users
https://github.com/grafana/oncall-private/issues/1962

Fix Slack integration leftovers after disconnecting

---

engine/apps/api_for_grafana_incident/serializers.py
engine/apps/api_for_grafana_incident/tests/test_views.py

Include alert group render_for_web details in the API response.
Related to https://github.com/grafana/oncall-private/issues/2159

Add render_for_web information to alert group incident API

---

CHANGELOG.md
engine/apps/alerts/tasks/delete_alert_group.py
engine/apps/alerts/tests/test_alert_group.py
engine/apps/slack/scenarios/distribute_alerts.py

- gracefully retry `apps.alerts.tasks.delete_alert_group.delete_alert_group` when hitting Slack ratelimits
- remove Slack messages from the DB as soon as they are deleted from Slack, so the tasks are not retrying perpetually

Handle Slack ratelimit on alert group deletion

---

engine/apps/webhooks/presets/preset_options.py

If a webhook preset is removed from configuration while there are still existing webhooks referencing it they will have the following behavior:
- Webhook can be viewed
- Webhook can be deleted
- Webhook cannot be modified
- Webhook will not execute
Removing a preset from configuration effectively disables all existing webhooks referencing it while retaining their data.

Allow deletion for removed presets

---

CHANGELOG.md
engine/apps/alerts/tasks/notify_ical_schedule_shift.py
engine/apps/alerts/tests/test_notify_ical_schedule_shift.py
engine/apps/schedules/ical_utils.py

Related to https://github.com/grafana/oncall/issues/3096

Fix slack notification for shift end affected by taken swap

---

CHANGELOG.md
engine/apps/public_api/serializers/action.py
engine/apps/public_api/tests/test_custom_actions.py
engine/apps/public_api/views/action.py

Fix update calls made by terraform when user field is empty or not present.
Should have been part of: https://github.com/grafana/oncall/pull/3053
https://github.com/grafana/terraform-provider-grafana/issues/1025

Fix action/webhook API not accepting empty/null user

---

grafana-plugin/e2e-tests/alerts/sms.test.ts

Since we now have a Mailslurp account we can start running this test. At the moment it is only run 1x daily on a GitHub Actions cron (to avoid incurring costs; [it is skipped](https://github.com/grafana/oncall/blob/dev/.github/workflows/linting-and-tests.yml#L317) via a Playwright "[test annotation filter](https://github.com/grafana/oncall/blob/dev/grafana-plugin/package.json#L14-L15)").
`MAILSLURP_API_KEY` repo secret has already been updated.
Closes #2693

unskip sms verification e2e test

---

CHANGELOG.md
grafana-plugin/src/plugin.json

When the direct paging role was [introduced](https://github.com/grafana/oncall/pull/3107), the OnCaller role didn't keep the permission to use this feature.
Also, being an OnCaller, makes sense user can update their own notification settings.
Related https://github.com/grafana/support-escalations/issues/7840.

Update plugin role permissions

---

CHANGELOG.md
engine/apps/api/serializers/schedule_ical.py
engine/apps/api/tests/test_schedules.py
engine/apps/public_api/serializers/schedules_ical.py
engine/apps/public_api/tests/test_schedules.py

Otherwise iCal schedules only refresh their cached final representation once a day (via periodic task).
Related to https://github.com/grafana/oncall/issues/3154

Update ical schedule creation/update to trigger final schedule refresh

---

grafana-plugin/src/pages/escalation-chains/EscalationChains.tsx
grafana-plugin/src/pages/schedules/Schedules.tsx

- Replaced `LoadingPlaceholder` with normal `Text` on the Escalations page
- Changed the copy for the loading indicator on Schedules
Both changes have been done to be consistent with the style used on the other pages.

Copy change for Schedules

---

CHANGELOG.md
engine/apps/alerts/models/channel_filter.py
engine/apps/api/serializers/channel_filter.py
engine/apps/api/tests/test_channel_filter.py
engine/apps/public_api/serializers/routes.py
engine/apps/public_api/tests/test_routes.py

Add filtering term length check for channel filter endpoints
Closes https://github.com/grafana/oncall-private/issues/2114

Fix channel filter endpoint

---

engine/apps/alerts/incident_appearance/renderers/slack_renderer.py
engine/apps/slack/scenarios/step_mixins.py
engine/apps/slack/tests/test_scenario_steps/test_alert_group_actions.py
engine/apps/slack/tests/test_scenario_steps/test_manage_responders.py
engine/apps/slack/tests/test_slack_renderer.py

https://github.com/grafana/oncall-private/issues/2217

Quickfix for getting alert group from slack message payload

---

CHANGELOG.md
engine/apps/slack/scenarios/distribute_alerts.py

Was able to reproduce locally with OnCall RBAC enabled and as a user with Viewer role:
Fixed with the changes introduced in this PR:
Closes #3212

fix RBAC authz issue for Slack Alert Group actions

---

CHANGELOG.md
engine/apps/api/serializers/on_call_shifts.py
engine/apps/api/tests/test_oncall_shift.py

Related to https://github.com/grafana/oncall-private/issues/2246

Disable updates for API/terraform shifts in internal API

---

CHANGELOG.md
engine/apps/api/serializers/team.py
engine/apps/api/tests/test_team.py
engine/apps/api/views/team.py
engine/apps/api/views/user.py
grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.module.scss
grafana-plugin/src/containers/AddResponders/parts/AddRespondersPopup/AddRespondersPopup.tsx
grafana-plugin/src/models/grafana_team/grafana_team.ts
grafana-plugin/src/models/grafana_team/grafana_team.types.ts
grafana-plugin/src/models/user/user.types.ts

Closes https://github.com/grafana/support-escalations/issues/8143
Fix a few minor issues introduced in #3128:
- Fix slow `GET /users` internal API endpoint related to [this change](https://github.com/grafana/oncall/blob/dev/engine/apps/api/views/user.py#L239)
- Fix slow `GET /teams` internal API endpoint. Introduced a `short` query parameter that only invokes `apps.schedules.ical_utils.get_oncall_users_for_multiple_schedules` when `short=false`.
- Order results from `GET /teams` internal API endpoint by name (ascending)
- Fix search issue when searching for teams in the add responders popup window (this was strictly a frontend issue)
- CSS changes to add responders dropdown to fix lonnnggg results list:
**Before**
**After**
The `apps.schedules.ical_utils.get_oncall_users_for_multiple_sched …

few add responders patches

---

grafana-plugin/src/models/alertgroup/alertgroup.types.ts
grafana-plugin/src/pages/incident/Incident.helpers.tsx
grafana-plugin/src/pages/incident/Incident.tsx

The concept of `AlertGroup.is_restricted` is deprecated and no longer used. In a future release I will remove all references to `is_restricted` from the backend (doing it in separate releases to avoid any potential issues where the frontend still references it shortly after release of it being removed from the API response)

remove is_restricted from frontend codebase

---

CHANGELOG.md
engine/apps/api/views/alert_group.py

Order alert groups in API by -started_at instead of -pk.  This should result in no visible change for most installations.  In the case where alert groups are being moved/restored between installations this allows for the display order to be as expected without relying on insertion order.
Note: Public API is already using -started_at instead of pk and it is already indexed.

Order alert groups by -started_at in internal API

---

.drone.yml
Tiltfile

`BUILDKIT_INLINE_CACHE` is required by `--cache-from`, otherwise it won't work.
It will improve build speeds when running `tilt up`

Add BUILDKIT_INLINE_CACHE build arg to docker builder step

---

CHANGELOG.md
engine/apps/mobile_app/models.py

Update wording for mobile push notifications timing choices

Update wording for mobile push notifications timing choices

---

engine/apps/webhooks/tasks/trigger_webhook.py

Set limit on number of times webhooks retry to 3

Limit number of times webhooks retry

---

engine/apps/telegram/tests/test_button_update_handler.py
engine/apps/telegram/updates/update_handlers/button_press.py

Fix getting alert group from telegram action: try to get alert group from telegram message first instead of getting it from action data

Fix getting alert group from telegram action

---

helm/local_image.yml

Forgot to add the `local_image.yml` file referenced [here](https://github.com/grafana/oncall/pull/3204/files#diff-ba66b531f5db27e2cb364be1b4cda073681f7447f088ac98139ca96c1609dc16R30).

Add missing referenced local_image.yml for local helm setup

---

engine/apps/heartbeat/tasks.py
engine/apps/heartbeat/tests/test_integration_heartbeat.py

Exclude deleted organizations before sending heartbeat alerts

Check if organization was deleted for heartbeat integration

---

engine/common/api_helpers/paginators.py

Fix inconsistency in alert group ordering introduced by #3240

Use started_at for alert group order in paginator

---

CHANGELOG.md
grafana-plugin/e2e-tests/escalationChains/escalationPolicy.test.ts
grafana-plugin/e2e-tests/utils/escalationChain.ts
grafana-plugin/src/models/escalation_policy/escalation_policy.helpers.ts

Fix escalation policy importance going back to default after changing users to notify + simple e2e test for this scenario
https://github.com/grafana/support-escalations/issues/7920
https://github.com/grafana/oncall/issues/1196

Fix escalation policy importance going back to default

---

engine/apps/alerts/escalation_snapshot/escalation_snapshot_mixin.py
engine/apps/alerts/models/alert_group.py
engine/apps/alerts/tasks/check_escalation_finished.py
engine/apps/alerts/tests/test_alert_group.py
engine/engine/management/commands/continue_escalation.py

Add an ability to continue escalations for alert groups from the point it was in case if it was stopped

Add a command to continue escalations for alert groups

---

engine/apps/alerts/models/alert.py
engine/apps/labels/tests/test_alert_group.py
engine/apps/labels/utils.py
engine/common/utils.py

Passes ALL integration labels down to alert groups, so it's easier to create labels for alert groups locally.
Related to https://github.com/grafana/oncall-private/issues/2179

Pass all integration labels down to alert groups

---

engine/apps/user_management/tests/factories.py

Some tests (particularly when there are schedules and shifts involved) depend on generated usernames being unique (we randomly get [CI errors](https://github.com/grafana/oncall/actions/runs/6812435056/job/18524768961#step:5:676) because of this). Although username field is not required to be unique, I think it makes sense for testing purposes to enable this (and when a duplicated username is needed in a test, make that explicit).

Make usernames unique in tests

---

engine/engine/management/commands/restart_acknowledge_reminder.py

Add command for restarting acknowledge reminder tasks for organization. It allows to easily restart these tasks for migrated organizations
related to https://github.com/grafana/oncall-private/issues/1955

Add command for restarting acknowledge reminder tasks for organization

---

CHANGELOG.md
engine/apps/integrations/views.py
engine/apps/user_management/tests/test_region.py

Handle OrganizationMoved, OrganizationDeleted and PermissionDenied exceptions same as other integration API views instead of converting to BadRequest.

AmazonSNS integration exception handling

---

CHANGELOG.md
docs/sources/oncall-api-reference/users.md
engine/apps/public_api/serializers/users.py
engine/apps/public_api/tests/test_users.py

Return the `timezone` field for the users GET API call
Closes #3093

fix(3093) Return timezone field of the user via public API

---

engine/apps/integrations/tests/test_views.py
engine/apps/labels/tests/factories.py

Handling alert payloads should work without db access (but still requires cached integrations information)

Add test ensuring ingestion works without db access

---

CHANGELOG.md
engine/apps/user_management/middlewares.py
engine/apps/user_management/tests/test_region.py

Forward headers for Amazon SNS when forwarding requests for moved organizations. Previous [PR](https://github.com/grafana/oncall/pull/3315) missed this since the test did not check mocked make_request for headers.

Forward headers for Amazon SNS

---

CHANGELOG.md
engine/apps/api/tests/test_auth.py
engine/apps/social_auth/pipeline.py
grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.tsx
grafana-plugin/src/containers/MobileAppConnection/__snapshots__/MobileAppConnection.test.tsx.snap
grafana-plugin/src/containers/UserSettings/parts/connectors/SlackConnector.tsx
grafana-plugin/src/containers/UserSettings/parts/tabs/SlackTab/SlackTab.tsx
grafana-plugin/src/models/user/user.types.ts
grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx

Closes https://github.com/grafana/oncall-private/issues/2289
- Fix issue where if you try connecting your Slack user to your OnCall user and the first time around you encounter an error (ex. connecting to the wrong Slack workspace), you will see the same error banner message despite a successful connection. Now we clear the session upon successful connection to ensure that you will not see any previously encountered errors.
- Fix some alignment issues on the Slack connection buttons
**Before**
**After**
- On the "User Info" user settings modal tab, render `display_name` instead of `slack_login`. Currently we prefix `@` before `slack_login`, which is a bit confusing as it makes you think that this is the handle you would use to `@` your user in Slack. `display_name` corresponds to the …

Fix few minor Slack connection issues

---

CHANGELOG.md
grafana-plugin/src/assets/style/vars.css

Fix styling when light theme is turned on via system preferences by excluding dark theme css vars in this case
https://github.com/grafana/oncall/issues/3188

Exclude dark css vars when light theme is turned on

---

CHANGELOG.md
engine/apps/api/tests/test_user.py
engine/apps/api/views/user.py

Related to https://github.com/grafana/oncall/issues/3164
This will allow the following request to check if a user is currently on-call:
`GET /api/internal/v1/users/?search=UCGEIXI1MR1NZ&is_currently_oncall=true`

Enable filtering users by public primary key

---

CHANGELOG.md
engine/apps/alerts/tasks/acknowledge_reminder.py
engine/apps/alerts/tests/test_acknowledge_reminder.py

Fix acknowledge reminder:
- check if organization was deleted
- improve logging

Fix acknowledge reminder

---

CHANGELOG.md
grafana-plugin/src/components/UserGroups/UserGroups.module.css
grafana-plugin/src/containers/RotationForm/RotationForm.module.css
grafana-plugin/src/containers/RotationForm/RotationForm.tsx

- adds proper boundary constraints on dragging the rotation modal (can't drag outside of parent container anymore)
- add scrolling within the users list in the rotation modal
Fixes https://github.com/grafana/oncall-private/issues/2299

Schedules rotation form tweaks

---

engine/apps/alerts/models/alert_group.py
engine/apps/api/serializers/alert_group.py
engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/serializers/alerts_field_cache_buster_mixin.py
engine/apps/api/tests/test_openapi_schema.py
engine/apps/api/views/alert_group.py
engine/requirements.txt
engine/settings/ci-test.py

- Fix issue that was causing our openapi schema to return HTTP 500 + add an integration test which fetches the `.yaml` schema and validates that the endpoint returns HTTP 200 (should hopefully prevent this from happening again).
- add a few more type hints along the way

Fix broken openapi schema + add integration test

---

CHANGELOG.md
engine/apps/user_management/middlewares.py
engine/apps/user_management/tests/test_region.py

Previous PR #3326 test and forwarding code was not representative of actual request.  This fixes forwarding of Amazon SNS headers.

Handle Amazon SNS headers for moved

---

.github/workflows/daily-e2e-tests.yml
.github/workflows/e2e-tests.yml
.github/workflows/linting-and-tests.yml
grafana-plugin/playwright.config.ts

In PR pipelines install dependencies and run e2e tests only in Chromium.
In daily e2e workflow use Chromium, Firefox and Webkit.

Use chromium only in PRs e2e tests

---

CHANGELOG.md
engine/apps/schedules/ical_utils.py
engine/apps/schedules/tests/test_ical_utils.py

1. Enable RBAC
2. Create a schedule rotation layer which includes a user whom is Viewer + has role `Notifications Receiver` (this is the RBAC role we use to filter which users show up in the user dropdown in the rotations modal when creating a rotation)
3. The user _sorta_ shows up in the schedule but they are listed in `missing_users`

fix missing users in rotations when RBAC is enabled

---

engine/requirements.txt
engine/settings/base.py

Moving to django-redis and updating related deps.
django-redis has better support for [sentinel setup](https://github.com/jazzband/django-redis#use-the-sentinel-connection-factory), besides improved cache helpers (and being actively maintained).

Switch to django-redis, update redis deps

---

CHANGELOG.md
engine/apps/slack/client.py
engine/apps/slack/tests/test_slack_client.py

Fixes https://github.com/grafana/oncall-private/issues/2293
Enable Slack client retries on `ratelimited` errors: it will check the `Retry-After` header before trying again. After 3 attempts it will raise the error (and we will fallback to the usual error/task retry handling).

Add builtin slack retry on ratelimited error

---

engine/apps/alerts/tasks/notify_user.py

add more logging in `apps.alerts.tasks.notify_user.perform_notification` task (related to https://github.com/grafana/oncall-private/issues/2318; won't solve that issue but will help with the investigation)

add more logging in apps.alerts.tasks.notify_user.perform_notification task

---

docs/sources/integrations/inbound-email/index.md
docs/sources/open-source/_index.md

This PR adds some more depth to the documentation regarding the setup of the "Inbound Email" integration.
In particular it references the setup requirement in the integration documentation and also outlines the requirements for the secret syntax and usage in the process.
https://github.com/grafana/oncall/issues/3015

[Docs] add details inbound email integration setup

---

engine/apps/api/serializers/webhook.py
engine/apps/api/views/webhooks.py

This should help with slowness in webhooks listing page (do not fetch *all* responses for webhooks, which besides were not used in the serializer).

Remove unused prefetch; prefer indexed query

---

CHANGELOG.md
engine/apps/api/tests/test_user.py
engine/apps/api/views/user.py

Fixed issue where `User Settings Reader` was missing permission to list users.

Allow users with user settings read to list users

---

engine/apps/alerts/models/alert.py
engine/apps/alerts/tests/test_alert.py

Fix issue triggering task retries because alert is not yet committed to the DB.
Similar to https://github.com/grafana/oncall/pull/3001.

Trigger distribute task after alert is committed

---

engine/apps/integrations/tests/test_views.py

Complements https://github.com/grafana/oncall/pull/3414/

Add test to ensure integrations work when cache is down

---

CHANGELOG.md
engine/apps/slack/slack_formatter.py
engine/apps/slack/tests/test_slack_formatter.py

Fix alert group rendering when some links were broken because of replacing `-` to `_`.
https://github.com/grafana/support-escalations/issues/8119
https://github.com/grafana/support-escalations/issues/8468

Fix alert group rendering

---

grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkDropdown.tsx
grafana-plugin/src/components/ExtensionLinkMenu/ExtensionLinkMenu.tsx
grafana-plugin/src/pages/incident/Incident.tsx
grafana-plugin/src/types.ts
grafana-plugin/src/utils/string.ts

This PR adds an [extension point] to the Grafana plugin, allowing other plugins to add menu items to the dropdown independently of this plugin.
It also moves the 'Declare incident' button into the 'Actions' menu representing the extension point, and displays it conditionally; the menu item is shown if all of the following are true:
1. the Grafana Incident plugin is installed (using the `PluginBridge` as before)
2. the alert group has a valid Grafana Incident URL
3. the alert group hasn't already been linked to an Incident
4. the Grafana Incident plugin hasn't _also_ configured an identical extension link to show in the dropdown.
Ideally the Grafana Incident plugin would soon configure an extension using this extension point, at which point we can remove the custom 'Declare incident' …

Add alert group actions extension point to plugin

---

engine/apps/alerts/models/alert_group.py
engine/apps/alerts/tasks/notify_user.py
engine/apps/metrics_exporter/apps.py
engine/apps/metrics_exporter/metrics_cache_manager.py
engine/apps/metrics_exporter/signals.py
engine/apps/metrics_exporter/tasks.py
engine/apps/metrics_exporter/tests/test_calculation_metrics.py
engine/apps/metrics_exporter/tests/test_update_metics_cache.py
engine/settings/celery_task_routes.py

Moving metrics creation into separate task to make alert ingestion more robust

Move new alert group metric creation into async task

---

CHANGELOG.md
grafana-plugin/src/plugin.json

When reading plugin provisioning data if the value was > 999999 it was converted to exponential notation by the template which the backend could not understand as an ID.  This makes sure it is written as an int.

Ensure stack_id and org_id are ints

---

grafana-plugin/src/state/rootBaseStore/index.ts
grafana-plugin/src/utils/async.test.ts
grafana-plugin/src/utils/async.ts

Pass correct params to functions when using retryFailingPromises
https://github.com/grafana/oncall/issues/3479

Pass correct params when using retryFailingPromises

---

grafana-plugin/src/assets/style/utils.css
grafana-plugin/src/components/MonacoEditor/MonacoEditor.tsx
grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.module.scss
grafana-plugin/src/containers/IntegrationTemplate/IntegrationTemplate.tsx
grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.module.css
grafana-plugin/src/containers/TemplatesAlertGroupsList/TemplatesAlertGroupsList.tsx
grafana-plugin/src/containers/WebhooksTemplateEditor/WebhooksTemplateEditor.tsx

Use css height: 100% instead of manually calculating height of monaco editor
https://github.com/grafana/oncall-private/issues/2351

Fix monaco editor height

---

grafana-plugin/src/containers/IntegrationLabelsForm/IntegrationLabelsForm.tsx

Rely on local state instead of checked attribute when toggling inheritance
https://github.com/grafana/oncall-private/issues/2352

Fix inherit label toggler

---

CHANGELOG.md
engine/apps/telegram/alert_group_representative.py
engine/apps/telegram/tasks.py
engine/settings/celery_task_routes.py

[send_alert_group_signal](https://github.com/grafana/oncall/blob/dev/engine/apps/alerts/tasks/send_alert_group_signal.py#L12) task is not idempotent. It launches [on_alert_group_action_triggered_async](https://github.com/grafana/oncall/blob/a2851d3f813c04768ce825c8af99e26912d80b4e/engine/apps/slack/representatives/alert_group_representative.py#L158) for slack and then might fail on [on_alert_group_action_triggered](https://github.com/grafana/oncall/blob/b2f4ffb98a940b894042df9161e209dc8a781dc1/engine/apps/telegram/alert_group_representative.py#L79) (not async) due to database DoesNotExist exception.
This PR makes telegram representative asyncronous

Make telegram on_alert_group_action_triggered asynchronous

---

engine/requirements.txt

Pins markdown to 2.4.10 to fix [failing test](https://github.com/grafana/oncall/actions/runs/7082829248/job/19276914906?pr=3490).

Pin markdown2 to 2.4.10

---

engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/tests/test_gcom_api_client.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py

Reverts grafana/oncall#3489
Reviewing logs, it seems something broke related to [token auth](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22ffS%22:%7B%22datasource%22:%22OP27Xzxnk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D~%5C%22dev-.%2A%5C%22,%20namespace%3D%5C%22grafana-com%5C%22,%20job%3D%5C%22grafana-com%2Fgrafana-com-api%5C%22%7D%20%7C~%20%5C%22%2Finstances%2F%5Ba-z0-9%5D%2B.config%3Dtrue%5C%22%20%7C%3D%20%5C%22Grafana%20OnCall%5C%22%22,%22editorMode%22:%22code%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22OP27Xzxnk%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1). Reverting for now, will revisit in a later PR.

Revert "Refactor gcom api calls when syncing org"

---

engine/settings/base.py

Update celery beat schedule to use crontab schedule types, since otherwise the timedelta is relative to the celery start and when we have a restart we have some bigger than expected gaps between task runs (alternatively it seems we could also use the `relative` option described [here](https://docs.celeryq.dev/en/main/userguide/periodic-tasks.html#available-fields))
Related to https://github.com/grafana/oncall-private/issues/2347

Update beat schedule to use crontab schedule types

---

CHANGELOG.md
grafana-plugin/e2e-tests/integrations/integrationsTable.test.ts
grafana-plugin/src/pages/integrations/Integrations.tsx
grafana-plugin/src/plugin.json

Rename "Connections" tab to "Monitoring Systems" and "Direct Paging" to "Manual Direct Paging" on Integrations page
https://github.com/grafana/oncall-private/issues/2302

Rename integrations table tabs

---

engine/apps/metrics_exporter/metrics_collectors.py
engine/apps/metrics_exporter/tests/conftest.py
engine/apps/metrics_exporter/tests/test_metrics_collectors.py

Fixes this issue we started seeing popping up because of a change introduced in #3496:
```python3
File "/etc/app/apps/metrics_exporter/views.py", line 22, in get
result = generate_latest(application_metrics_registry).decode("utf-8")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/prometheus_client/exposition.py", line 198, in generate_latest
for metric in registry.collect():
File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 97, in collect
yield from collector.collect()
File "/etc/app/apps/metrics_exporter/metrics_collectors.py", line 56, in collect
alert_groups_total, missing_org_ids_1 = self._get_alert_groups_total_metric(org_ids)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

address issue with metrics calculations when redis cluster is used

---

engine/apps/api/views/labels.py
engine/apps/mobile_app/tests/test_mobile_app_gateway.py
engine/apps/mobile_app/urls.py
engine/apps/mobile_app/views.py

Changes how the `MOBILE_APP_GATEWAY_ENABLED` feature flag enables/disables the mobile app gateway viewset.

Return 404 from mobile app gateway viewset

---

engine/apps/alerts/models/alert_group_log_record.py
engine/apps/alerts/tests/test_alert_group_log_record.py

Do not trigger update log report signal until there is an alert set for the [recently created alert group](https://github.com/grafana/oncall/blob/dev/engine/apps/alerts/models/alert.py#L110) to avoid retries when trying to post an updated report when there isn't yet a message posted (or an alert to render).

Do not trigger alert group update log signal before setting alert

---

CHANGELOG.md
engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/serializers/escalation_chain.py
engine/apps/api/serializers/schedule_base.py
engine/apps/api/serializers/webhook.py
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/api/tests/test_escalation_chain.py
engine/apps/api/tests/test_schedules.py
engine/apps/api/tests/test_webhooks.py

Removes setting team to default value on PUT request to internal endpoints if team is not in request data.
(For integrations, escalation chains, schedules and webhooks)
https://github.com/grafana/oncall-private/issues/2368

Fix team changing on PUT request if team is not in request data

---

engine/apps/telegram/models/connectors/personal.py
engine/apps/telegram/tests/test_personal_connector.py

https://github.com/grafana/oncall-private/issues/2377

Handle `Unauthorized` exception on posting alert group to telegram

---

CHANGELOG.md
engine/apps/base/models/user_notification_policy_log_record.py
engine/apps/mobile_app/tasks/new_alert_group.py
engine/apps/mobile_app/tests/tasks/test_new_alert_group.py

Adds error code for mobile notification logs

Add error code for mobile notification logs

---

CHANGELOG.md
engine/apps/mobile_app/alert_rendering.py
engine/apps/mobile_app/tests/tasks/test_new_alert_group.py

Adds limit for alert title length in mobile app push notifications
https://github.com/grafana/oncall-private/issues/2375

Fix `message is too big` exception for mobile push notification

---

engine/apps/alerts/tasks/check_escalation_finished.py
engine/apps/alerts/tests/test_check_escalation_finished_task.py

There is no index for the `received_at` column, and the filter isn't really needed (aggregation will work in any case, considering only the entries for which we have data).

Remove unneeded filter making query slower

---

CHANGELOG.md
engine/apps/alerts/models/alert_group.py
engine/apps/alerts/tasks/notify_user.py
engine/apps/alerts/tests/test_notify_user.py

Updates check if escalation was skipped in Slack before trying to notify user by Slack.

Check if escalation was skipped in Slack before trying to notify user

---

helm/oncall/values.yaml

The examples at extraVolumeMounts and extraVolumes properties are swapped
Fixing the properties  extraVolumeMounts and extraVolumes in Helm chart

Fix: the examples in extraVolumeMounts and extraVolumes are swapped

---

CHANGELOG.md
engine/apps/api/serializers/alert_group_table_settings.py
engine/apps/api/tests/test_alert_group_table_settings.py

Fix alert group columns validation: - validate column ids by each type separately
validation check from this issue - https://github.com/grafana/oncall-private/issues/2378

Fix alert group columns validation

---

CHANGELOG.md
engine/apps/email/inbound.py
engine/apps/email/tests/test_inbound_email.py

Handle exception on parsing sender email address from email message for inbound email integration endpoint
https://github.com/grafana/oncall-private/issues/2398

Fix inbound email integration endpoint

---

CHANGELOG.md
engine/apps/api/tests/test_webhooks.py
engine/apps/webhooks/models/webhook.py
engine/apps/webhooks/tests/test_webhook.py

Adds PATCH method Support for outgoing webhook
Fixes #3564

fix(3564) Support PATCH Method In Outgoing webhook

---

CHANGELOG.md
engine/apps/slack/tests/test_scenario_steps/test_paging.py
engine/apps/user_management/models/organization.py
engine/apps/user_management/tests/test_organization.py

- Closes https://github.com/grafana/support-escalations/issues/8763
- Closes https://github.com/grafana/oncall/issues/3388

fix duplicate teams showing up in teams dropdown for `/escalate` slack command

---

grafana-plugin/src/containers/RotationForm/RotationForm.tsx

Hide "Limit each shift length" control for month-based rotations
https://github.com/grafana/support-escalations/issues/8874

Hide "Limit each shift length" control for month-based rotations

---

engine/requirements.txt

This helps with debugging https://github.com/grafana/oncall-private/issues/2406 (**note**: it doesn't fix it)

use forked version of redis-py which adds extra debug logging

---

CHANGELOG.md
grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx

Closes https://github.com/grafana/oncall/issues/3564

Add ability to create an Outgoing Webhook with the PATCH HTTP method via the UI

---

CHANGELOG.md
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py
engine/common/utils.py

Related to https://github.com/grafana/support-escalations/issues/8844
Queuing multiple sync_organization tasks for the same org could lead to parallel running of the sync task for the same organization, potentially creating duplicated entries and/or generating multiple unneeded API calls. This prevents running an organization sync while there is a sync for that same org in progress.

Setup one-at-a-time lock for sync_organization tasks

---

CHANGELOG.md
engine/apps/mobile_app/tests/test_utils.py
engine/apps/mobile_app/utils.py

_tldr_; we had a lengthy discussion about this [here](https://raintank-corp.slack.com/archives/C04JCU51NF8/p1701893410542629?thread_ts=1701690117.016909&cid=C04JCU51NF8). `firebase.messaging.UnregisteredError` errors occur because of events outside of our control and retrying will never fix them, therefore we should simply skip retrying in this case.
We retry these fairly often ([logs](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22iWZ%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%23%20%7Bcluster%3D~%5C%22prod-%28eu-west-0%7Cus-central-0%29%5C%22,%20namespace%3D%5C%22amixr-prod%5C%22%7D%20%7C%3D%20%5C%22task_name%3Dapps.webhooks.tasks.trigger_webhook.execute_webhook%5C%22%20%7C%3D%20%5C%22retry%5C%22%5Cn%7Bcluster%3D~%5C%22pr …

do not retry `firebase.messaging.UnregisteredError` exceptions for FCM relay tasks

---

CHANGELOG.md
docs/sources/outgoing-webhooks/_index.md
engine/apps/webhooks/tests/test_trigger_webhook.py
engine/apps/webhooks/utils.py

See all the context [here](https://raintank-corp.slack.com/archives/C025VMT6SPK/p1704802171131009?thread_ts=1704762857.043879&cid=C025VMT6SPK)

Decrease outgoing webhook timeouts from 10secs to 4secs

---

CHANGELOG.md
engine/apps/schedules/tasks/__init__.py
engine/apps/schedules/tasks/drop_cached_ical.py
engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
engine/apps/schedules/tasks/refresh_ical_files.py
engine/apps/schedules/tests/tasks/test_drop_cached_ical.py
engine/apps/schedules/tests/tasks/test_refresh_ical_files.py
engine/apps/schedules/tests/test_notify_about_empty_shifts_in_schedule.py
engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py
engine/settings/celery_task_routes.py

We've been seeing this `AttributeError` quite frequently for quite some time ([logs](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22oPl%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D~%5C%22prod-%28eu-west-0%7Cus-central-0%29%5C%22,%20namespace%3D%5C%22amixr-prod%5C%22%7D%20%7C%3D%20%60AttributeError%28%5C%22module%20%27apps.schedules.tasks.notify_about_empty_shifts_in_schedule%27%20has%20no%20attribute%20%27apply_async%27%5C%22%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1))

Fix `module 'apps.schedules.tasks.notify_about_empty_shifts_in_schedule' has no attribute 'apply_async'` `AttributeError`

---

CHANGELOG.md
engine/apps/webhooks/tests/test_webhook.py
engine/apps/webhooks/utils.py

Fixes escaping for unicode characters in webhooks.
#3149

Fix unicode character encoding in JSON for webhooks

---

CHANGELOG.md
engine/apps/grafana_plugin/helpers/client.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py

Fix this issue I came across in a celery task retry exception log:

Fix occasional `AttributeError` in `apps.grafana_plugin.tasks.sync.sync_organization_async` task

---

CHANGELOG.md
engine/apps/slack/scenarios/shift_swap_requests.py
engine/apps/slack/tests/test_scenario_steps/test_shift_swap_requests.py

Fixes https://github.com/grafana/oncall/issues/3648

Fix updating a shift swap with no Slack message

---

engine/common/custom_celery_tasks/dedicated_queue_retry_task.py
engine/common/custom_celery_tasks/tests/test_dedicated_queue_retry_task.py
engine/common/tests/test_task_queue_assignment.py

This is a follow up to https://github.com/grafana/oncall/pull/3677.
It appears that when a task uses the [`autoretry_for` kwarg](https://docs.celeryq.dev/en/stable/userguide/tasks.html#automatic-retry-for-known-exceptions) in the task decorator, it doesn't log the exception in `on_failure` as would be expected. Now when retrying, we log out a message + any exception/stack trace information.

add more logging on celery task retry

---

engine/apps/slack/tests/test_utils.py
engine/apps/slack/utils.py

Extend list of exceptions to ignore on posting message to slack channel
https://github.com/grafana/oncall/issues/3694

Fix post message to slack channel

---

engine/apps/alerts/tasks/check_escalation_finished.py
engine/apps/alerts/tests/test_check_escalation_finished_task.py

Sent SMS messages are considered completed for our purpose here (ie. do not wait for Twilio delivered confirmation).

Update alert group personal notifications checker to check sent SMS

---

engine/apps/user_management/subscription_strategy/free_public_beta_subscription_strategy.py

Removes unnecessary filtering by organization during emails limit check in send email notification task since there is filtering by user there, so there is no need to check organization
https://github.com/grafana/oncall-private/issues/2205

Speed up send email notification task

---

docs/sources/get-started/_index.md

Fixes the escalations typo.
Someone noticed the typo internally.

OnCall Docs: Fix 'escalations' typo on Get Started page

---

engine/apps/schedules/ical_utils.py

Minor formatting change to the suggested REFRESH-INTERVAL of iCal exports. DURATION units less than 1d must be prefixed by "T". Fixes issue with Atlassian Confluence failing to subscribe to iCal URLs from Grafana OnCall
RFC 2445 explains this a bit more clearly in section 4.3.6 on DURATION. 
https://www.ietf.org/rfc/rfc2445.txt
Obviously I wish Atlassian could just be a little more forgiving in their digestion of the iCal data since clearly Gmail and others have no problem with it, but I doubt I'm going to get much traction with them (we do have a case open though).
I haven't logged one yet but I can if you want. Again, my main issue was with Atlassian Confluence. Kept throwing errors of "The uploaded data does not seem to be iCalendar content" as long as the REFRESH-INTERVAL DURATION was …

Minor Fix to Format of REFRESH-INTERVAL in ical_utils.py

---

engine/apps/integrations/mixins/alert_channel_defining_mixin.py
engine/apps/integrations/tests/test_views.py

Related to [logs](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22hum%22:%7B%22datasource%22:%22c-R8UWvVk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22amixr-prod%5C%22,%20job%3D%5C%22amixr-prod%2Famixr-integrations%5C%22%7D%20%7C%3D%20%5C%22django.core.serializers.base.DeserializationError%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22c-R8UWvVk%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221706023840486%22,%22to%22:%221706024722486%22%7D%7D%7D&orgId=1)

Handle a possible outdated cached integration error

---

CHANGELOG.md
engine/apps/alerts/tasks/notify_user.py
engine/apps/alerts/tests/test_notify_user.py

Use Telegram ratelimit countdown when retry `perform_notification` task on `RetryAfter` error
https://github.com/grafana/oncall-private/issues/2451

Retry `perform_notification` with Telegram ratelimit countdown on `RetryAfter` error

---

CHANGELOG.md
engine/apps/public_api/serializers/routes.py
engine/apps/public_api/serializers/schedules_base.py
engine/apps/public_api/tests/test_integrations.py
engine/apps/public_api/tests/test_routes.py
engine/apps/public_api/tests/test_schedules.py

Add check whether organization has Slack connection on update Slack related field using public api endpoints
https://github.com/grafana/oncall-private/issues/1611

Fix `routes` and `schedules` public api endpoints

---

CHANGELOG.md
grafana-plugin/src/components/Integrations/IntegrationTemplateBlock.tsx
grafana-plugin/src/components/WithConfirm/WithConfirm.tsx
grafana-plugin/src/containers/IntegrationContainers/IntegrationTemplatesList.tsx

show autoresolve template for ALL integrations when autoresolve is ON
show modal on edit button click for alertmanager based integrations
Frontend part of https://github.com/grafana/oncall-private/issues/2260

Show warning when edit AM-based resolve templates

---

CHANGELOG.md
engine/apps/api/serializers/team.py
engine/apps/api/tests/test_team.py

Fixes calculating number of oncall users per team for `team` api endpoint

Fix calculating number of oncall users per team

---

CHANGELOG.md
engine/apps/slack/tasks.py
engine/apps/slack/tests/tasks/test_send_message_to_thread_if_bot_not_in_channel.py

See [this conversation](https://raintank-corp.slack.com/archives/C04JCU51NF8/p1706722752735009) for more context.
Additionally, improves logging for this task + adds unit tests.

fix slack API rate limit errors in `send_message_to_thread_if_bot_not_in_channel` task

---

CHANGELOG.md
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py

- Handle case where key exists for jsonData but explicitly set to None
- Disable incident if plugin disabled after or in the case it was removed completely from the Grafana instance

Fix Incident plugin status sync

---

engine/apps/slack/models/slack_message.py
engine/apps/slack/utils.py

Closes https://github.com/grafana/oncall-private/issues/2515
Attempts to address some `SlackAPIRatelimitError` exceptions seen in the following tasks:
- `apps.slack.tasks.post_slack_rate_limit_message` ([logs](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22qhs%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%23%20%7Bcluster%3D~%5C%22prod-%28us-central-0%7Ceu-west-0%29%5C%22,%20namespace%3D%5C%22amixr-prod%5C%22,%20job%3D~%5C%22amixr-prod%2Famixr-engine-celery-retry%2A%5C%22%7D%5Cn%7Bcluster%3D~%5C%22prod-%28us-central-0%7Ceu-west-0%29%5C%22,%20namespace%3D%5C%22amixr-prod%5C%22%7D%20%7C%3D%20%5C%22apps.slack.tasks.post_slack_rate_limit_message%5C%22%20%7C%3D%20%5C%22retry%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B …

attempt to address some `SlackAPIRatelimitError` exceptions 

---

CHANGELOG.md
engine/apps/webhooks/models/webhook.py
engine/apps/webhooks/tests/test_trigger_webhook.py
engine/apps/webhooks/tests/test_webhook.py
engine/pyproject.toml
engine/requirements-dev.txt

Closes https://github.com/grafana/oncall/issues/3831

patch occasional `UnicodeEncodeError` that occurs with outgoing webhooks

---

engine/apps/integrations/tests/test_views.py
engine/requirements-dev.txt
engine/tox.ini

Speeds up `pytest` test execution by ~30%.
More specifically, adds [`pytest-xdist`](https://pytest-xdist.readthedocs.io/en/stable/), which according to their docs:
> plugin extends pytest with new test execution modes, the most used being distributing tests across multiple CPUs to speed up test execution 
**Before**
**After**

add `pytest-xdist` to speed up backend tests

---

CHANGELOG.md
engine/apps/mobile_app/models.py
engine/apps/mobile_app/tasks/going_oncall_notification.py
engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py

So because of how we run the task that sends the "You're going oncall" push notifications, there are sometimes rounding "errors" in the displayed text of the push notification. For example, if you've configured your mobile app to remind you 12h before your on-call shift starts it sometimes might say:
> You're going oncall in 11 hours
This is because of the [background task being executed every 10mins](https://github.com/grafana/oncall/blob/dev/engine/settings/base.py#L545-L548) and us continually checking if now is the appropriate time to send the notification (we took this approach because we don't have any easy way of emitting an event exactly when a shift starts.. yay ical).
This PR corrects that by rounding to the closest configuration value that we allow.

Fix rounding issue with displayed time when sending "You're going oncall" push notification

---

CHANGELOG.md
engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/public_api/serializers/integrations.py
engine/apps/public_api/tests/test_integrations.py

Related to https://github.com/grafana/oncall/issues/3858
We still need to improve error messages in the UI, [to be discussed](https://raintank-corp.slack.com/archives/C04JCU51NF8/p1707486122947369).

Restrict integration name uniqueness per team

---

CHANGELOG.md
engine/apps/slack/scenarios/paging.py
engine/apps/slack/tests/test_scenario_steps/test_paging.py

Reverting part of https://github.com/grafana/oncall/pull/3861

Revert requiring permission on Slack direct paging

---

CHANGELOG.md
engine/apps/api/tests/test_alert_group.py
engine/common/utils.py

Disable escaping quotes for html in template results
Alert group 6 shows the new rendering vs group 5 which has the previous incorrect rendering.
#3864

Don't html escape quotes when rendering

---

CHANGELOG.md
engine/apps/slack/scenarios/paging.py
engine/apps/slack/tests/test_scenario_steps/test_paging.py

Related to https://github.com/grafana/oncall/issues/3109
Fixes issue from https://github.com/grafana/oncall/pull/3881 (problem was that there is no organization set in the Slack request, making it impossible to check for user permissions; check permission once an organization is set in the form instead).

Check for permissions on Slack escalate command

---

CHANGELOG.md
engine/apps/api/tests/test_team.py
engine/apps/api/tests/test_user.py
engine/apps/api/views/user.py

Related to https://github.com/grafana/oncall/issues/1820
Editor and Viewer roles have the user-settings:read permission, which allows them to list users but with some of the data hidden. It makes sense to allow the same thing for the detail endpoint, keeping the viewable data restriction (fixing the referenced issue too).

Update user details internal API perms

---

grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts

Add labels to routing templating cheatsheet

add labels to routing templating cheatsheet

---

grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookForm.config.tsx

This was missing in https://github.com/grafana/oncall/pull/3920

Expose status change trigger type when setting up a webhook

---

.drone.yml

Now `requirements-dev.txt` lists deps introduced by `pre-commit`, and so the `grep` command was returning multiple lines.
Fixes builds [here](https://drone.grafana.net/grafana/oncall/3591/1/6).

Fix .drone grepping for pre-commit

---

grafana-plugin/src/network/network.ts

Fixes the issue that after axios was updated the paramsSerializer was not being set correctly. I am not sure if there are other changes we need to make after updating. No changelog as the version with the issue has not been released.

Fix for update to axios that changed how paramsSerializer is setup

---

grafana-plugin/e2e-tests/escalationChains/escalationPolicy.test.ts
grafana-plugin/e2e-tests/globalSetup.ts
grafana-plugin/e2e-tests/schedules/quality.test.ts
grafana-plugin/e2e-tests/utils/schedule.ts
grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts

Fix failing e2e tests on `dev`

fix e2e tests

---

engine/common/ordered_model/ordered_model.py
engine/common/tests/test_ordered_model.py

Related to https://github.com/grafana/oncall-private/issues/2386.
Issue seems related to [multiple concurrent Terraform-triggered updates](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22j0s%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcluster%3D%5C%22prod-eu-west-0%5C%22,%20namespace%3D%5C%22amixr-prod%5C%22%7D%20%7C%3D%20%5C%22logger%3Dinsight_logger%20tenant_id%3D735393%5C%22%20%7C%3D%20%5C%22resource_type%3Droute%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221707813893526%22,%22to%22:%221707815856774%22%7D%7D%7D&orgId=1
) changing the route order to zero (and eventually succeeding)
Sample test …

Update OrderedModel.swap to retry on IntegrityError

---

.drone.yml

Fixes the path of the plugin file to public.  Leftover from last round of build changes

Fix path for plugin release publish

---

grafana-plugin/src/components/Policy/EscalationPolicy.tsx
grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
grafana-plugin/src/pages/integration/Integration.helper.ts
grafana-plugin/src/pages/integration/Integration.tsx

- Fetch selected schedule on mount which is not done as soon as schedule is not on the first page
- Add missing observer decorator
- Fix incorrect HTTP calls when creating integrations https://raintank-corp.slack.com/archives/C04JCU51NF8/p1708703429829919
https://github.com/grafana/oncall/issues/3966

Fetch selected value of notify schedule in escalation policy

---

engine/engine/middlewares.py
engine/engine/wsgi.py
engine/requirements.in
engine/requirements.txt
engine/settings/base.py
engine/tox.ini

Use uwsgi instead of TracingMiddleware to not to mess up with span attrs. Also it's an attempt to fix different trace IDs between cortex-gw, oncall and labels plugin. Last, but not least - add a middleware to log request headers if OTEL is enabled. It's needed to debug tracing headers

Use uwsgi instrumentation and log request headers

---

grafana-plugin/src/containers/RotationForm/RotationForm.tsx
grafana-plugin/src/models/schedule/schedule.types.ts
grafana-plugin/src/pages/schedule/Schedule.helpers.ts

- handle nullable shift.by_day
https://github.com/grafana/support-escalations/issues/9548

Support nullable shift.by_day

---

engine/Dockerfile
engine/requirements.in

This is the workaround to make local image build faster on arm64 machines 
This commit can be reverted once https://github.com/grpc/grpc/issues/34998 is resolved

Use local arm64 grpcio wheel to make local builds on arm64 faster

---

.github/CODEOWNERS

On https://github.com/grafana/oncall/pull/3992 I needed to poke the `docs-gops` team for an approval, even though it was only a one line change and can be safely approved by anyone on the OnCall team

allow `@grafana/grafana-oncall` GitHub team users to approve changes to `/docs`

---

engine/settings/celery_task_routes.py

The fcm_relay task was in the wrong queue, moves it to critical.

Move fcm_relay task from webhook to critical queue

---

grafana-plugin/src/network/oncall-api/http-client.test.ts
grafana-plugin/src/network/oncall-api/http-client.ts

Fix passing additional headers to custom fetch
Closes https://github.com/grafana/support-escalations/issues/9630

Fix passing additional headers to custom fetch

---

engine/apps/alerts/models/alert_receive_channel.py
engine/apps/api/tests/test_alert_receive_channel.py

Delete alert receive channel connections on alert receive channel delete
Related to https://github.com/grafana/oncall-private/issues/2540

Delete connection on channel delete

---

engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/api/views/alert_receive_channel.py

Related to https://github.com/grafana/oncall-private/issues/2541

Create default webhooks on integration creation

---

engine/apps/integrations/tests/test_views.py
engine/apps/integrations/views.py

Reject integration requests with a null payload

Update universal integrations to reject requests without payload

---

engine/apps/alerts/incident_appearance/templaters/web_templater.py
engine/apps/alerts/tests/test_alert_group_renderer.py

Web templater had a bug with link substitutions: it replaced every link
with 'oncallsubstitutedlink{link_idx}', and then replaced them back.
But if we have more than 10 links in the message, there
would be replacements like 'oncallsubstitutedlink10', which will be
partially replaced by match from 'oncallsubstitutedlink1', yielding
incorrect links in the resulting message. This fixes this behaviour.

Fix web alert templater with many links

---

engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/api/views/alert_receive_channel.py
engine/common/exceptions/__init__.py
engine/common/exceptions/exceptions.py

Related to https://github.com/grafana/oncall-private/issues/2542

Add test_connection endpoint for alert receive channel backsync setup

---

grafana-plugin/src/plugin.json

I'm _fairly_ certain these are duplicates of this 👇 route that already exists in our `plugin.json` ([here](https://github.com/grafana/oncall/blob/dev/grafana-plugin/src/plugin.json#L184C5-L198C6)):
```json
{
"path": "api/internal/v1/*",
"method": "*",
"url": "{{ .JsonData.onCallApiUrl }}/api/internal/v1/",
"headers": [
{
"name": "X-Instance-Context",
"content": "{ \"stack_id\": \"{{ printf \"%.0f\" .JsonData.stackId }}\", \"org_id\": \"{{ printf \"%.0f\" .JsonData.orgId }}\" }"
},
{
"name": "Authorization",
"content": "{{ .SecureJsonData.onCallApiToken }}"
}
]
}
```
all of the headers being sent are identical + the `api/internal/v1/*` route should forward all of these deleted routes to the right `api/internal/v1` api endpoint

remove duplicate `plugin.json` routes

---

grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.helpers.ts
grafana-plugin/src/models/alert_receive_channel_connected_channels/alert_receive_channel_connected_channels.ts
grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts
grafana-plugin/src/pages/integration/Integration.hooks.ts
grafana-plugin/src/pages/integration/OutgoingTab/ConnectIntegrationModal.tsx
grafana-plugin/src/pages/integration/OutgoingTab/ConnectedIntegrationsTable.tsx

Disable integration backsync conditionally if token has not been generated
Closes https://github.com/grafana/oncall-private/issues/2599

Disable integration backsync conditionally

---

engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/api/views/alert_receive_channel.py

Related to https://github.com/grafana/oncall-private/issues/2542
Make it possible to test connection for an existing integration, without needing to explicitly pass the password.

Enable test_connection for existing integrations reusing data

---

engine/apps/api/serializers/alert_group.py

closes https://github.com/grafana/oncall/issues/4099

Add permalinks field to the alert groups list view in internal api

---

engine/apps/api/serializers/organization.py
engine/apps/api/tests/test_organization.py

Needed for some mobile app work.

add `grafana_incident_enabled` to `GET /organization` internal API response

---

engine/apps/social_auth/pipeline/google.py
grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx

- UI enhancements
- Fix bug when going through the Google OAuth2 disconnection flow. We should send the `refresh_token` in the `revoke` HTTP request, rather than the `access_token` (`access_token` expires frequently and can result in Google sending back HTTP 400.. `refresh_token` is long lived and can also be sent in the revoke flow)

Google Calendar integration improvements

---

grafana-plugin/src/models/user/user.ts

Remove updating user's timezone on backend if there are no changes
Closes https://github.com/grafana/oncall/issues/4112

Remove updating user's timezone on backend if there are no changes

---

engine/apps/google/tasks.py
engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py

Fixes issue where you create a Google Calendar OOO that overlaps with an in-progress oncall shift (currently we only consider future/upcoming shifts).
Related to https://github.com/grafana/oncall-private/issues/2555

Google Calendar Integration - consider current oncall shifts for autogeneration of shift swap requests

---

engine/apps/mobile_app/tests/test_mobile_app_gateway.py
engine/apps/mobile_app/views.py

Adds `X-Grafana-User` header in proxied mobile app proxy gateway requests. This is required by the Grafana Incident backend to be able to properly resolve the currently authenticated user.

add `X-Grafana-User` header in proxied mobile app proxy gateway requests

---

engine/apps/alerts/incident_log_builder/incident_log_builder.py
engine/apps/alerts/tests/test_incident_log_builder.py

Adds the Outgoing web hooks escalation step to the escalation plan log.
Closes #4037

Added Outgoing Web hooks to escalation policy log

---

engine/apps/alerts/models/alert_group.py
engine/apps/alerts/tests/test_alert_group.py
engine/apps/slack/scenarios/distribute_alerts.py

Update by backsync will now expect the source alert receive channel triggering the transition (and update the log record using this information).

Update backsync method to take source channel as param

---

engine/apps/integrations/mixins/alert_channel_defining_mixin.py
engine/apps/integrations/tests/test_views.py
engine/engine/tests/test_views.py
engine/engine/views.py

- Refactor alert receive channel lookup so it is easier to follow
- Remove the additional lookup that was taking place for alert receive channels that belong to a deleted organization, these can be treated as deleted for usage purposes even though the alert receive channel itself does not have `deleted_at` populated
- Organizations that have been moved will still need to be looked up everytime.  This is not optimized in favor of not maintaining a cache of Organizations.  These are not frequent requests and can be optimized later if necessary.

Improve performance for deleted integration lookups

---

engine/apps/webhooks/listeners.py
engine/apps/webhooks/tasks/alert_group_status.py
engine/apps/webhooks/tasks/trigger_webhook.py
engine/apps/webhooks/tests/test_alert_group_status_change.py
engine/apps/webhooks/tests/test_trigger_webhook.py

Avoid triggering a webhook if it is from a connected integration and the triggering event was caused by a backsync update.

Check for backsync updates before triggering connected webhooks

---

engine/apps/integrations/tests/test_views.py
grafana-plugin/src/components/PageErrorHandlingWrapper/PageErrorHandlingWrapper.helpers.tsx
grafana-plugin/src/network/oncall-api/http-client.test.ts
grafana-plugin/src/network/oncall-api/http-client.ts

Throw full fetch response to allow existing error handlers to work properly

Fix incident error handling

---

engine/apps/webhooks/models/webhook.py
engine/apps/webhooks/utils.py

Fix source integration filter query

---

engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/webhooks/models/webhook.py
engine/apps/webhooks/tests/test_trigger_webhook.py
engine/apps/webhooks/tests/test_webhook.py
engine/apps/webhooks/utils.py

Also, some refactoring on the way we get the source integration from a connected webhook.

Handle webhooks update on source integration settings update

---

helm/oncall/values.yaml

Fixes https://github.com/grafana/oncall/issues/4178
Closes https://github.com/grafana/oncall/issues/4178

Add retry queue to helm chart

---

engine/apps/api/serializers/user.py
engine/apps/api/views/user.py
engine/apps/mobile_app/backend.py

Speed up `GET /users` internal api endpoint by reducing number of calls to database 
Related to slow schedules page issue - https://github.com/grafana/oncall-private/issues/1552

Optimize GET /users internal api endpoint

---

engine/apps/api/views/schedule.py
engine/apps/schedules/constants.py
engine/apps/schedules/ical_utils.py
engine/apps/schedules/models/on_call_schedule.py

Speed up `GET /schedules` and `GET /current_user_events` internal api endpoints by reducing number of calls to database 
Related to https://github.com/grafana/oncall-private/issues/1552

Optimize GET /schedules and /current_user_events internal api endpoints

---

engine/apps/webhooks/tasks/trigger_webhook.py
engine/apps/webhooks/tests/test_trigger_webhook.py

Only create a response object if the request is triggered, otherwise log the reason.
Avoid creating multiple/unneeded responses, which can be also confusing when displaying response objects. If there is no response, the webhook/request wasn't triggered (possible reasons: integrations are filtered, or the trigger template evaluates to False).

Avoid creating a webhook response if request is not triggered

---

engine/apps/webhooks/tasks/trigger_webhook.py
engine/apps/webhooks/tests/test_trigger_webhook.py

fix incorrect args passed to `apps.webhooks.tasks.trigger_webhook.execute_webhook`

fix incorrect args passed to `apps.webhooks.tasks.trigger_webhook.execute_webhook`

---

grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx

This is a requirement to get our Google OAuth2 consent screen re-approved

Add Google privacy policy note for Google Calendar integration

---

engine/apps/api/serializers/alert_group.py
engine/apps/api/tests/test_alert_group.py
grafana-plugin/src/network/oncall-api/autogenerated-api.types.d.ts

Alert groups connected to an external source will return external URLs information, eg.
```
{
"external_urls": [
{
"integration": "C2IFSTV93NQUW",
"integration_type": "servicenow",
"external_id": "4c686e1e83d1021075feb3a6feaad3a8",
"url": "https://some.service-now.com/incident.do?sys_id=4c686e1e83d1021075feb3a6feaad3a8"
}
]
}
```

Add alert groups external URLs information to details API

---

engine/apps/alerts/models/alert.py
engine/apps/alerts/models/alert_group.py
engine/apps/alerts/tasks/__init__.py
engine/apps/alerts/tasks/distribute_alert.py
engine/apps/alerts/tests/test_alert.py
engine/apps/webhooks/listeners.py
engine/settings/celery_task_routes.py
grafana-plugin/package.json

- Since send_alert_create_signal is inside transaction on_commit we can conclude that if it does not exist it was intentionally deleted before the task could run and the task can exit instead of retrying
- Improve logging when send_alert_create_signal is called so both alert and alert group are in the same line so you don't need to search the logs as much
- Improve logging on public api delete alert group so we can know what the alert group belonged to and the responsible user/org
- Remove distribute_alerts (Stopped using a while back, code should be safe to remove now, no tasks running in system)
Closes https://github.com/grafana/oncall-private/issues/2640

Handle alert group deleted when task is already queued

---

engine/apps/alerts/models/alert_receive_channel.py
engine/apps/webhooks/tests/test_webhook.py

It makes it so webhooks are deleted when a "connected" integration is deleted. Related to https://github.com/grafana/oncall-private/issues/2615.

Fix deleting integration with connected webhooks

---

grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx

Right now there's an issue where we call the contact point endpoint upon integration creation, even though the integration is not grafana_alerting. The PR addresses this issue

Prevent calling contact point endpoint for other integrations

---

engine/apps/public_api/serializers/webhooks.py
engine/apps/public_api/tests/test_webhooks.py
engine/apps/webhooks/presets/preset_options.py
engine/apps/webhooks/tests/test_webhook_presets.py
engine/conftest.py
engine/settings/base.py

Enables the API to perform updates on the advanced webhooks created via the UI
Closes #3958 

Allow webhook modification by API for advanced webhook

---

engine/apps/metrics_exporter/metrics_collectors.py
engine/apps/metrics_exporter/tests/conftest.py
engine/apps/metrics_exporter/tests/test_metrics_collectors.py

Fix calculating metric values per integration from different services

Fix calculating metrics from different services in metrics collector

---

grafana-plugin/src/components/Policy/EscalationPolicy.tsx
grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx

Make team selects searchable

---

Tiltfile
dev/README.md
grafana-plugin/Dockerfile.dev

- Add `yarn install` to Tiltfile when running locally
- Build prod bundle of the frontend without watch mode on CI
- Remove `engine` from Tilt deps of grafana and oncall provisioning config map so grafana can be built in parallel to engine to speed up things
- Update dev/README.md with Node.js requirement
Closes https://github.com/grafana/oncall/issues/4295 

improve frontend dev exp

---

engine/engine/celery.py

Follow-up to #4314. Remove kwargs from celery logging as it included more information than needed.

Remove kwargs from celery logging

---

engine/apps/alerts/escalation_snapshot/snapshot_classes/escalation_policy_snapshot.py
engine/apps/alerts/models/alert_group_log_record.py
engine/apps/alerts/tests/test_escalation_policy_snapshot.py

Fixes issue where custom webhooks that are part of an escalation chain were still being executed even though they were disabled.  Now the attempt will be logged in the escalation log and noted that the webhook was disabled.

Fix escalation chain webhooks executing when disabled

---

grafana-plugin/src/models/filters/filters.helpers.ts

Handle empty values in convertFiltersToBackendFormat
Broken Insights page

Handle empty values in convertFiltersToBackendFormat

---

engine/apps/slack/models/slack_message.py
engine/apps/slack/tests/test_slack_message.py

It updates the slack deep link url to respect the [correct format](https://api.slack.com/reference/deep-linking#app_or_bot) requested [here](https://github.com/grafana/oncall/issues/4122)

Update deep link URL for Slack messages

---

engine/apps/google/client.py
engine/apps/google/tasks.py
engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
engine/pyproject.toml

Do not keep retrying on HttpErrors (eg. 403). Also, we will re-queued periodically later.

Update out of office task to not retry on HttpError

---

engine/apps/slack/errors.py
engine/apps/slack/scenarios/distribute_alerts.py
engine/apps/slack/tests/test_scenario_steps/test_distribute_alerts.py
engine/apps/slack/tests/test_slack_client.py

Do not retry updating a message if Slack returns `cant_update_message` API [error](https://api.slack.com/methods/chat.update#errors) (meaning bot user has no permission to update the message).

Avoid retrying to update Slack log message if cant_update_message

---

engine/apps/api/serializers/alert_receive_channel.py

Related to https://github.com/grafana/support-escalations/issues/10505
(getting only `id` is enough here and the query performs **much** better)

Improve query performance when fetching alert payload for templating

---

grafana-plugin/src/components/IntegrationContactPoint/IntegrationContactPoint.tsx

It was not clear that the user was expected to enter a name for the new contact point. Changed "Choose Contact Point" to "Enter New Contact Point Name"

Fix misleading placeholder when creating a new Alerting Integration Contact Point

---

engine/apps/metrics_exporter/metrics_collectors.py
engine/apps/metrics_exporter/tests/conftest.py
engine/apps/metrics_exporter/tests/test_metrics_collectors.py

This should help with ongoing issue generating too big metrics payloads (issue introduced when including service name labels).

Avoid generating response time value metrics for empty integrations

---

grafana-plugin/src/plugin.json

Adding `grafana-oncall-app.user-settings:read` Notifications Receiver so that it can use `get_backend_verification_code`

Add grafana-oncall-app.user-settings:read permission to notifications receiver role

---

engine/apps/api/tests/test_schedules.py
engine/apps/api/views/schedule.py

Fixes Slack user group warning false positives on the schedule detail page

Fix Slack user group warning false positives

---

grafana-plugin/src/dashboards/oncall_metrics_dashboard.json
grafana-plugin/src/pages/insights/variables.ts

- show data source filter also on cloud
- use custom All option value to prevent invalid queries when there are too many values

show datasource dropdown on cloud

---

engine/apps/alerts/tasks/notify_all.py
engine/apps/alerts/tasks/notify_group.py
engine/apps/alerts/tests/test_notify_all.py
engine/apps/alerts/tests/test_notify_group.py

Fixes https://github.com/grafana/oncall-private/issues/2708

Fix order filtering when executing notify all/group steps from snapshot

---

grafana-plugin/src/pages/integration/Integration.tsx

When editing a jinja route template the filtering_term_type was not being provided so it was being validated as regex instead.  This adds the missing flag so that the route will use the correct validation.  The reason this was not being hit in the past is most jinja templates were still passing regex validation.
Closes #4259 

Fix missing filtering term type 1 when editing jinja route template

---

grafana-plugin/src/pages/insights/variables.ts

hide datasource dropdown on cloud

hide datasource dropdown on cloud

---

Tiltfile
dev/grafana/provisioning/plugins/grafana-oncall-app-provisioning.yaml
grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx
grafana-plugin/src/state/plugin/plugin.ts
grafana-plugin/src/types.ts
grafana-plugin/src/utils/consts.ts

Read useBackendPlugin from jsonData. Passing meta to window object is done to avoid unnecessary changes in http interceptors and requests. This hack will be removed once we enable backend plugin by default - it's just for development purposes

Read useBackendPlugin from jsonData

---

.github/workflows/expensive-e2e-tests.yml
.github/workflows/linting-and-tests.yml
engine/apps/grafana_plugin/tests/test_app_config.py

This command is no longer necessary. Currently it doesn't seem to be working (see screenshot 👇). Presumably `netcat-traditional` is installed on the `ubuntu-latest-8-cores` runner.

remove unnecessary CI step `bash` command

---

engine/apps/api/tests/test_user_groups.py
engine/apps/api/views/user_group.py

Add endpoint to return slack user group from public primary key

Add endpoint to get a single user group

---

engine/apps/slack/models/slack_usergroup.py
engine/apps/slack/tests/test_user_group.py

Fixes https://github.com/grafana/oncall-private/issues/2664

Fix update slack group to not raise if group is not found

---

engine/apps/alerts/tasks/check_escalation_finished.py

Related to https://github.com/grafana/oncall-private/issues/2619
(we need the succeeding number to make the SLO query happy with cluster/namespace filtering)

Update escalation auditor logs to expose succeeding count

---

engine/apps/api/serializers/escalation_policy.py
engine/apps/api/serializers/user_notification_policy.py
engine/apps/api/tests/test_escalation_policy.py
engine/apps/api/tests/test_user_notification_policy.py
engine/apps/api/views/alert_group.py
engine/apps/api/views/escalation_policy.py
engine/common/api_helpers/custom_fields.py
grafana-plugin/src/components/Policy/EscalationPolicy.tsx
grafana-plugin/src/components/Policy/NotificationPolicy.tsx
grafana-plugin/src/components/Policy/Policy.consts.ts
grafana-plugin/src/containers/EscalationChainSteps/EscalationChainSteps.tsx
grafana-plugin/src/models/alertgroup/alertgroup.ts
grafana-plugin/src/models/escalation_policy/escalation_policy.ts
grafana-plugin/src/pages/incident/Incident.tsx
grafana-plugin/src/pages/incidents/Incidents.tsx
grafana-plugin/src/pages/incidents/parts/IncidentDropdown.tsx
grafana-plugin/src/pages/incidents/parts/IncidentSilenceModal.tsx
grafana-plugin/src/pages/incidents/parts/SilenceButtonCascader.tsx
grafana-plugin/src/pages/incidents/parts/SilenceSelect.tsx

Same as https://github.com/grafana/oncall/pull/4422 but returns wait delays as strings so it's backward-compatible with the mobile app API calls.
Related to https://github.com/grafana/oncall/issues/2464

Allow custom wait delay

---

grafana-plugin/src/plugin.json

- Manually added ui-extensions metadata to the plugin.json (to be able to lazy-load plugins in Grafana, based on [this PR](https://github.com/grafana/grafana/pull/88288)

Plugin.json: update with extensions info

---

grafana-plugin/src/containers/Rotations/SchedulePersonal.tsx
grafana-plugin/src/pages/schedule/Schedule.tsx
grafana-plugin/src/styles/utils.styles.ts

Part of https://github.com/grafana/oncall/issues/4428
Additionally it fixes
- NPE within `SchedulePersonal`
- changes the line-break to use `contrastText` instead of `main` (from grafana theme)

Show correct swap request dates

---

engine/apps/base/models/live_setting.py

Only validate live settings in `AVAILABLE_NAMES` to avoid issues when a live setting is renamed (one of the settings was renamed in https://github.com/grafana/oncall/pull/4287 earlier)

only validate existing settings

---

.github/workflows/build-engine-docker-image-and-publish-to-dockerhub.yml
.github/workflows/linting-and-tests.yml
.github/workflows/snyk-security-scan.yml
engine/apps/alerts/tests/test_escalation_snapshot.py
engine/apps/api/tests/test_user.py
engine/tox.ini

Closes https://github.com/grafana/oncall-private/issues/2733

fix flaky tests + increase runner size when building docker image

---

grafana-plugin/src/pages/insights/variables.ts

Disable All option for non selectable variables

Disable All option for non selectable variables

---

helm/oncall/templates/secrets.yaml

New secret values were being generated for OnCall secrets `secretKey` and `mirageSecretKey` even when a fixed value was provided in the `values.yaml` file. This causes encryption of tokens to break in the DB through inconsistency when things are redeployed. This PR fixes it so that the value will only be generated if it is not set and the values in `values.yaml` are used.

Only generate random OnCall secrets value when it is not provided

---

engine/apps/slack/scenarios/paging.py

Related to https://github.com/grafana/oncall-gateway/issues/240

Inject chatops-proxy metadata into direct paging user dropdown

---

engine/apps/phone_notifications/phone_backend.py

Add a space between "team" and the quoted team name. Currently this renders as:
```
This phone number has been connected to Grafana OnCall team"ops"
```
(which is an SMS I just received on my phone.)

Add spacing between words in notifications.

---

grafana-plugin/package.json
grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
grafana-plugin/src/containers/ServiceNowConfigDrawer/ServiceNowConfigDrawer.tsx
grafana-plugin/src/pages/incident/Incident.tsx
grafana-plugin/src/utils/string.ts
grafana-plugin/yarn.lock

make links clickable in resolution notes
Closes https://github.com/grafana/oncall/issues/4231
Closes https://github.com/grafana/oncall/issues/505

make links clickable in resolution notes

---

docs/sources/configure/escalation-chains-and-routes/index.md
docs/sources/manage/notify/slack/index.md
engine/apps/alerts/models/escalation_policy.py

rename "Notify whole Slack channel" escalation step into "Escalate to all slack channel members"
Closes https://github.com/grafana/oncall/issues/4373

Rename notify whole Slack channel

---

engine/apps/api/views/user.py

Handle PhoneNumberBanned as status code 403 instead of 500

Fix PhoneNumberBanned producing status code 500

---

engine/apps/auth_token/auth.py
engine/apps/grafana_plugin/serializers/sync_data.py
engine/apps/grafana_plugin/urls.py
engine/apps/grafana_plugin/views/__init__.py
engine/apps/grafana_plugin/views/install_v2.py
engine/apps/grafana_plugin/views/sync_v2.py
engine/apps/user_management/models/team.py
engine/apps/user_management/models/user.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py
grafana-plugin/pkg/plugin/resources.go
grafana-plugin/pkg/plugin/sync.go

- Implement organization sync on install
- Expose sync endpoint to post org data from backend plugin
(sync can be manually triggered by
`curl http://oncall:oncall@localhost:3000/api/plugins/grafana-oncall-app/resources/plugin/sync`)
- Setup OnCall user if missing on first plugin interaction
- Reworked previous existing sync logic to use the updated one (atm periodic sync tasks are still running)

Add backend plugin org sync and rework existing sync

---

engine/apps/slack/urls.py

Related to https://github.com/grafana/oncall-gateway/issues/254

Make Slack URLs work without trailing slashes

---

.github/CODEOWNERS
engine/apps/auth_token/auth.py
engine/apps/auth_token/tests/test_plugin_auth.py
engine/apps/grafana_plugin/tests/test_sync_v2.py
engine/apps/grafana_plugin/views/install_v2.py
engine/apps/grafana_plugin/views/sync_v2.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py
grafana-plugin/pkg/plugin/proxy.go
grafana-plugin/pkg/plugin/sync.go

Include teams membership details in user header (allowing teams setup during first login user creation).
Add authentication bits for sync endpoint.

Sync teams on user creation during first login

---

engine/apps/chatops_proxy/tasks.py
engine/settings/celery_task_routes.py

Fix for https://raintank-corp.slack.com/archives/C04JCU51NF8/p1719452618841629.
* Move chatops-proxy sync tasks to the long queue
* Batch tasks slower (12 hours instead of 30 minutes)

 Tweak chatops-proxy sync

---

.github/actions/build-sign-and-package-plugin/action.yml

Install Go and Mage + run `mage buildAll` when building grafana plugin

install Mage, Go and build plugin backend on Github CI

---

engine/apps/alerts/incident_appearance/renderers/slack_renderer.py

Removes @mention from Alert Slack message
Fixes https://github.com/grafana/oncall/issues/187

Remove mention from aler group main slack message

---

grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookFormFields.tsx
grafana-plugin/src/models/alert_receive_channel/alert_receive_channel.ts

Closes https://github.com/grafana/support-escalations/issues/11299

fix outgoing webhook form race condition which causes integrations to sometimes not be populated

---

grafana-plugin/src/containers/RotationForm/RotationForm.tsx

Fixes a bug when changing the start date of a monthly masked rotation breaks the rotation.
Related to https://github.com/grafana/support-escalations/issues/11374

Fix monthly masked rotation bug

---

.github/actions/build-sign-and-package-plugin/action.yml
.github/workflows/linting-and-tests.yml

`oncall-private` is using [actions/build-sign-and-package-plugin/action.yml](https://github.com/grafana/oncall/pull/4658/files#diff-6200ac63c387869ca55bc34d1b343a96c667daef428602f910d696836cb09f84) from the dev branch of this repo when doing the deployment. In order to deploy new OnCall initialization which has Go backend component, we need this action to install Go, Mage and do the `mage buildAll`. For other branches where there are no Go files yet, it would just swallow the error thanks to the `|| true` part

run `mage buildAll || true` when building the plugin 

---

engine/engine/urls.py
grafana-plugin/pkg/plugin/app.go

duplicate health endpoint into internal api + use it in backend plugin oncall api url check

duplicate health endpoint into internal api

---

grafana-plugin/src/containers/RotationForm/RotationForm.tsx

Fixes a bug when changing recurrence period for shifts with "Mask by weekdays" setting enabled breaks the schedule.
https://github.com/grafana/oncall/assets/20116910/396359c5-4ba6-47d7-b003-fea9db709bea
Related to https://github.com/grafana/support-escalations/issues/11374

Fix changing recurrence for weekday masked shifts

---

engine/apps/email/inbound.py
engine/apps/email/tests/test_inbound_email.py

Related to https://github.com/grafana/oncall-private/issues/2683
(when using mailgun backend, you can get multiple recipients, keep the first one matching the domain; other backends seem to just return the first one)

Handle inbound email integration alert getting multiple recipients

---

docs/sources/configure/escalation-chains-and-routes/index.md

Clarifies how the `Notify users one by one (round robin)` escalation policy works.
Related to https://github.com/grafana/support-escalations/issues/11449

Make docs clearer for "Notify users one by one" policy

---

grafana-plugin/src/components/Policy/EscalationPolicy.tsx
grafana-plugin/src/containers/AlertRules/parts/connectors/MSTeamsConnector.tsx
grafana-plugin/src/containers/AlertRules/parts/connectors/SlackConnector.tsx
grafana-plugin/src/containers/AlertRules/parts/connectors/TelegramConnector.tsx
grafana-plugin/src/containers/AttachIncidentForm/AttachIncidentForm.tsx
grafana-plugin/src/containers/EscalationChainForm/EscalationChainForm.tsx
grafana-plugin/src/containers/GrafanaTeamSelect/GrafanaTeamSelect.tsx
grafana-plugin/src/containers/IntegrationForm/IntegrationForm.tsx
grafana-plugin/src/containers/MaintenanceForm/MaintenanceForm.tsx
grafana-plugin/src/containers/OutgoingWebhookForm/OutgoingWebhookFormFields.tsx
grafana-plugin/src/containers/ScheduleForm/ScheduleForm.tsx
grafana-plugin/src/containers/UserSettings/parts/tabs/GoogleCalendar/GoogleCalendar.tsx
grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx

Make sure GSelect gets rerendered with updated items., more context [here](https://raintank-corp.slack.com/archives/C04JCU51NF8/p1720559481963519) 
https://github.com/grafana/oncall/issues/4670

Fix Slack channel and user group values not populating on first visit of schedule notification settings

---

tools/scripts/oncall_reports.py

- Flag users missing a required notification method
- Check users have scheduled shifts in non-orphaned (web or terraform) schedules
- Generate a `teams.csv` file with information about alert groups per team, and their MTTA and MTTR (in the specified period)

Add additional information to the reports script

---

Tiltfile

Explicitly install oncall resources in default namespace which helps running OnCall + Incident via ops-devenv

explicitly install oncall resources in default namespace

---

engine/apps/grafana_plugin/tasks/sync.py
engine/settings/base.py
engine/settings/celery_task_routes.py

Changes operations to cleanup deleted empty integrations so that they are only performed on organizations that have deleted integrations recently.  The previous task checked everything because we were not performing the cleanup on a regular basis, now that it has been scheduled regularly we can operate on recently deleted integrations instead.
The existing task has been removed from the schedule, the code for it can be removed after the other tasks have cleared.

Only run cleanup for integrations deleted recently

---

dev/grafana/provisioning/plugins/grafana-oncall-app-provisioning.yaml
grafana-plugin/pkg/plugin/install.go
grafana-plugin/pkg/plugin/proxy.go
grafana-plugin/pkg/plugin/settings.go
grafana-plugin/pkg/plugin/status.go
grafana-plugin/pkg/plugin/sync.go
grafana-plugin/src/models/plugin/plugin.ts

- license now determined based on value of version in package.json (vX.Y.Z or dev-oss => OpenSource, rWWW-vX.Y.Z => Cloud). You can still set it in the provisioning data to override
- grafanaUrl is based on GrafanaCfg AppURL if it is not overridden by being set in provisioning data
- Change /status call to GET
- Enforce http method for sync, install and status
- Add custom user agent to identify plugin

Get license and grafanaUrl from environment

---

.github/pull_request_template.md

Make it so that you need to explicitly use the "Closes" keyword when opening PRs (as per [this sprint retro comment](https://miro.com/app/board/uXjVKzhhfgE=/?moveToWidget=3458764594901560846&cot=14))

PR template: "Closes" -> "Related to"

---

engine/apps/metrics_exporter/metrics_collectors.py
engine/apps/metrics_exporter/tests/conftest.py
engine/apps/metrics_exporter/tests/test_metrics_collectors.py

based on this PR - https://github.com/grafana/oncall/pull/4517
Related to https://github.com/grafana/oncall/issues/4455

Drop stale metrics cache

---

engine/apps/alerts/tasks/notify_user.py

Fix scheduling `perform_notification` from `send_bundled_notification` task - leftover after resolving merge conflict

Fix `send_bundled_notification` task

---

engine/apps/api/tests/test_oncall_shift.py
engine/apps/api/tests/test_schedules.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py

No need to change 0 to `None` in priority level when returning schedule events (related to this [thread](https://raintank-corp.slack.com/archives/C0229FD3CE9/p1721239227358309?thread_ts=1721148066.857589&cid=C0229FD3CE9))

Update schedule events internal API to return default priority level

---

engine/apps/alerts/models/alert_group.py
engine/apps/alerts/tests/test_alert_group.py

Related to https://github.com/grafana/oncall-private/issues/2816

Handle multiple unpage event logs when getting paged users

---

engine/apps/api/serializers/channel_filter.py
engine/apps/api/tests/test_channel_filter.py

Related to this [thread](https://raintank-corp.slack.com/archives/C0229FD3CE9/p1721309907422709).

Update regex to jinja route conversion to correctly escape double quotes

---

engine/apps/grafana_plugin/tasks/sync.py
engine/settings/celery_task_routes.py

- Fixes a bug where cleanup_empty_deleted_integrations was not being passed the correct arguments
- Removes start_cleanup_organizations now that it is no longer in use

Fix bug for incorrect arguments used to invoke cleanup_empty_deleted_integrations

---

Tiltfile
grafana-plugin/pkg/plugin/settings.go

- Handle getting plugin version in the backend plugin for older Grafana versions (e.g. 10.1.7)
- Make sure to set Grafana URL so engine can request the Grafana API

Set external URL for Grafana in tiltfile

---

engine/apps/api/views/alert_group.py
engine/apps/api/views/alert_receive_channel.py
engine/apps/api/views/escalation_chain.py
engine/apps/api/views/schedule.py
engine/apps/api/views/user.py
engine/apps/api/views/webhooks.py
grafana-plugin/e2e-tests/utils/alertGroup.ts
grafana-plugin/src/containers/RemoteFilters/RemoteFilters.tsx
grafana-plugin/src/models/filters/filters.ts

* Make the filter input say `Filter results...` instead of `Search or filter results...` on the alert group page; disallow custom input there so it's only possible to choose among existing filters
* Remove outdated `<page>/filters?search=` functionality from internal API
Related to https://github.com/grafana/oncall-private/issues/2679

Make it clear alert groups can't be searched

---

grafana-plugin/src/plugin.json

Upcoming changes to OnCall plugin initialization will be expecting `grafana_token` from all requests coming from the OnCall plugin.  It is not currently used it is being added so the plugin can tolerate the update without errors.

Prepare for changes to OnCall plugin initialization 

---

grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.helpers.ts
grafana-plugin/src/pages/settings/tabs/ChatOps/ChatOps.tsx

show chatops proxy error if present in query params
Related to https://github.com/grafana/oncall-gateway/issues/255

show chatops proxy error

---

grafana-plugin/src/containers/IntegrationContainers/RouteHeading.tsx
grafana-plugin/src/containers/RouteLabelsDisplay/RouteLabelsDisplay.tsx
grafana-plugin/src/pages/integration/Integration.tsx

- Set the unique key on `Expanded` and `Collapsed` containers, otherwise React has problems figuring out state for each of them when you append a new route
- Fixed NPE found by Faro
- Tweaked warnings display of `Routing template not set` and `Routing labels not set`
Closes https://github.com/grafana/oncall/issues/4720

Set unique key on each rendered route

---

engine/apps/api/views/alert_group.py
engine/common/api_helpers/paginators.py
engine/settings/base.py

Related to https://github.com/grafana/oncall-private/issues/2679
Confirmed the query rewriting works via MySQL query logs (index is also forced for the stats queries):
`2024-07-24T19:50:59.482751Z      3977 Query     SELECT `alerts_alertgroup`.`id` FROM `alerts_alertgroup` FORCE INDEX (`alert_group_list_index`) WHERE (`alerts_alertgroup`.`channel_id` IN (13) AND (1) AND (`alerts_alertgroup`.`public_primary_key` LIKE 'test' OR `alerts_alertgroup`.`inside_organization_number` LIKE 'test' OR `alerts_alertgroup`.`web_title_cache` LIKE '%test%') AND `alerts_alertgroup`.`root_alert_group_id` IS NULL AND ((`alerts_alertgroup`.`silenced` = ('0') AND `alerts_alertgroup`.`acknowledged` = ('0') AND `alerts_alertgroup`.`resolved` = ('0')) OR (`alerts_alertgroup`.`acknowledged` = ('1') AND …

Update alert group search to force index in MySQL

---

engine/apps/slack/scenarios/distribute_alerts.py
engine/apps/slack/tasks.py

Stop posting a new message, as it is available from the button (https://github.com/grafana/oncall/pull/4641)
This is an intermediate step, so we will only update posted messages but not post new ones
Once the majority of messages are updated, we can remove this step (https://github.com/grafana/oncall/pull/4686)

Stop posting new slack log reports

---

engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/tests/test_grafana_api_client.py
engine/apps/grafana_plugin/tests/test_self_hosted_install.py
engine/apps/grafana_plugin/views/self_hosted_install.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py

Fixes a bug when RBAC permissions are getting erased when Grafana's API returns a 5xx server error on organization sync.
Closes https://github.com/grafana/oncall-private/issues/2834

Don't update RBAC status on Grafana server error

---

engine/apps/schedules/ical_utils.py
engine/apps/schedules/tests/test_ical_utils.py

Covers the case on getting cached on-call users when cached schedule was deleted
Related to https://github.com/grafana/oncall-private/issues/2836

Fix deleted schedule on getting on-call users from cache

---

engine/apps/auth_token/auth.py
engine/apps/auth_token/tests/test_plugin_auth.py
engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/helpers/gcom.py
engine/apps/grafana_plugin/serializers/sync_data.py
engine/apps/grafana_plugin/sync_data.py
engine/apps/grafana_plugin/tasks/__init__.py
engine/apps/grafana_plugin/tasks/sync_v2.py
engine/apps/grafana_plugin/tests/test_grafana_api_client.py
engine/apps/grafana_plugin/tests/test_sync_v2.py
engine/apps/grafana_plugin/urls.py
engine/apps/grafana_plugin/views/__init__.py
engine/apps/grafana_plugin/views/install_v2.py
engine/apps/grafana_plugin/views/recaptcha.py
engine/apps/grafana_plugin/views/status_v2.py
engine/apps/grafana_plugin/views/sync_v2.py
engine/apps/user_management/models/team.py
engine/apps/user_management/models/user.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_sync.py
engine/common/api_helpers/errors.py
engine/engine/urls.py
engine/settings/celery_task_routes.py

Related to https://github.com/grafana/oncall-private/issues/2806#issuecomment-2246286918.
Prepare engine for the backend plugin enablement/migration:
- Refactor sync code
- Improve plugin user authentication to set up user on-the-fly (when missing)
- Implement v2 endpoints for install, sync and status (to be used via the backend plugin)
(most of the changes come from https://github.com/grafana/oncall/pull/4657; backport all engine changes that keep backwards compatibility)

Rework organization sync and grafana plugin engine backend

---

engine/apps/email/models.py
engine/apps/email/tasks.py
engine/apps/email/tests/test_notify_user.py

Email tasks are failing and retrying when they use the fallback default notification policy as it does not get saved in the DB.  This PR uses the same way as UserNotificationPolicyLogRecord to set that field to null to avoid `ValueError("save() prohibited to prevent data loss due to unsaved related object 'notification_policy'.").` when that is the case.

Fix retrying email notification task

---

engine/apps/api/views/features.py
grafana-plugin/src/models/slack/slack.ts
grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.module.css
grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx
grafana-plugin/src/state/features.ts

Introduce OnCall UI for Unified Slack migration. It's mostly banners and text adjustments. Changes are behind feature flag.

adjust to unified slack

---

.github/workflows/expensive-e2e-tests.yml
engine/apps/google/client.py
engine/apps/google/tasks.py
engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
engine/apps/social_auth/pipeline/google.py
engine/apps/user_management/models/user.py
engine/apps/user_management/tests/test_user.py
engine/pyproject.toml

Attempting to solve some Celery retry errors we're seeing around `apps.google.tasks.sync_out_of_office_calendar_events_for_user`. This PR adds better logging and documents some findings so far.

add better logging for Google Calendar task

---

docs/sources/manage/notify/slack/index.md
engine/apps/slack/errors.py
engine/apps/slack/models/slack_usergroup.py
engine/apps/slack/tests/test_slack_client.py
engine/apps/slack/tests/test_user_group.py

Semi-related to https://github.com/grafana/oncall-private/issues/2131
Addresses occasional task failures for `apps.slack.tasks.update_slack_user_group_for_schedules` when trying to update a Slack user group for a non-paid Slack account. [Slack's documentation](https://slack.com/help/articles/212906697-Create-a-user-group) mentions this is a paid only feature, hence the error ([logs](https://ops.grafana-ops.net/goto/-AWfsrrIR?orgId=1) from an actual task):
```
2024-08-08 16:20:36,613 source=engine:celery worker=ForkPoolWorker-16 task_id=6bdaae94-1552-4b6d-93e2-e2fa0bae57b1 task_name=apps.slack.tasks.update_slack_user_group_for_schedules name=apps.slack.models.slack_usergroup level=WARNING Slack usergroup S06LW5GJ88Z update failed: Slack API error! Response: {'ok': False, 'error': …
```

Update Slack user group for a schedule - handle `paid_team_only` Slack API error

---

engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/tests/test_gcom_api_client.py

Addressing this task exception ([logs](https://ops.grafana-ops.net/goto/rkVAurrSR?orgId=1)):
```
2024-08-08 16:30:49,455 source=engine:celery worker=ForkPoolWorker-18 task_id=969226be-64a8-4616-ac32-3909d1f0cb60 task_name=apps.grafana_plugin.tasks.sync.start_sync_organizations name=celery.app.trace level=ERROR Task apps.grafana_plugin.tasks.sync.start_sync_organizations[969226be-64a8-4616-ac32-3909d1f0cb60] raised unexpected: KeyError('nextCursor')
```
[This conversation](https://raintank-corp.slack.com/archives/C0K031RP1/p1723158123932529) in `#grafana-com-dev` has more context. The _tldr;_ takeaway after chatting w/ the GCOM team was lets simply retry requests in this case.

address occasional missing `nextCursor` data key from GCOM GET /instances

---

engine/apps/webhooks/tasks/trigger_webhook.py
engine/apps/webhooks/tests/test_trigger_webhook.py

Address retrying `apps.webhooks.tasks.trigger_webhook.execute_webhook` task when `requests.exceptions.SSLError` is raised ([logs](https://ops.grafana-ops.net/goto/vqrouqrIR?orgId=1)). Don't retry the task on these exceptions as retrying will not help. From the [`request`'s docs](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification):
> By default, SSL verification is enabled, and Requests will throw a SSLError if it’s unable to verify the certificate

`apps.webhooks.tasks.trigger_webhook.execute_webhook` task - don't retry on `requests.exceptions.SSLError`

---

.github/actions/setup-python/action.yml
engine/Dockerfile
engine/requirements-dev.txt
engine/requirements.in
engine/requirements.txt

_tldr;_ I think we should install `setuptools` into our engine `Dockerfile` + in our CI env because Python 3.12 no longer installs `distutils` by default. This should unblock us from being able to merge #4656 and #4555.
**More details**
I would like to be able to merge #4656 and #4555. _However_, in both of these PRs `setuptools` is being removed from `requirements-dev.txt` ([here](https://github.com/grafana/oncall/pull/4555/files#diff-d8146d0816a943b0fa69a20399d7bbdb58e1c84c8b7933b2ba6dea7c10c410f5L113-L116) and [here](https://github.com/grafana/oncall/pull/4656/files#diff-d8146d0816a943b0fa69a20399d7bbdb58e1c84c8b7933b2ba6dea7c10c410f5L113-L116)). This leads to things breaking (CI job [#1](https://github.com/grafana/oncall/actions/runs/9865348392/job/27242117474?pr=4555#step:5:98) and …

Fix missing `setuptools` dep

---

engine/apps/grafana_plugin/serializers/sync_data.py
engine/apps/user_management/sync.py

SyncData was parsing users so permissions were dictionaries instead of SyncPermission objects.

Parse permissions in SyncPermission instead of dict

---

grafana-plugin/src/plugin.json

I tried redirecting to the backend plugin resources instead, but I don't seem to have `grafanaUrl` set in `jsonData` (at least locally, so I cannot use that in the route `url` field), and also there are some issues with the auth headers (if I force a fixed URL pointing to my local grafana). OTOH, using the original route setting things work (in any case I guess it would be nice to migrate people to the new endpoints eventually).

Keep internal API proxy plugin route

---

engine/apps/slack/views.py

Return 422 instead of 500 when the handler for the slack incoming event was not found to gracefully omit events on call not subscribed to.

chore: return 422 on slack step not found

---

engine/apps/google/tasks.py
engine/apps/google/tests/test_sync_out_of_office_calendar_events_for_user.py
engine/apps/mobile_app/tasks/going_oncall_notification.py
engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py

Makes it so that:
* Shift swap requests are not created from Google Calendar for deleted orgs
* On-call shift mobile app notifications are not sent to users from deleted orgs

Deleted organization fixes

---

grafana-plugin/src/assets/style/utils.css
grafana-plugin/src/components/WithConfirm/WithConfirm.tsx
grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.module.css
grafana-plugin/src/pages/settings/tabs/ChatOps/tabs/SlackSettings/SlackSettings.tsx

polish ui of unified slack:
Related to https://github.com/grafana/oncall-gateway/issues/299

Polish unified slack ui

---

engine/apps/metrics_exporter/metrics_collectors.py

Reverts the accidental removal of the ApplicationMetricsCollector from the metric register

Fix collecting metrics

---

engine/apps/alerts/grafana_alerting_sync_manager/grafana_alerting_sync.py
engine/apps/alerts/tests/test_grafana_alerting_sync.py
grafana-plugin/src/plugin.json

As we are not getting back the same info when querying `/api/alertmanager/grafana/config/api/v1/alerts` when using the external service account vs admin account we will only validate that the contact point exists instead of checking if it is in the notification policy tree as well.
Note: This could be cleaner either remove the field or fix but that should be done as part of a separate task to improve contact point <-> integration in general. This is to unblock the plugin initialization changes.

Disable checking alerting notification policy when checking contact points

---

.github/workflows/snyk-security-scan.yml
engine/Dockerfile

Fixes [many CVEs](https://ops.grafana-ops.net/a/grafana-vulnerabilityobs-app/sources/9/version/5561?var-package=&var-cve=CVE-2023-42363&var-riskLevel=$__all) currently present in our `latest` tagged Docker image:
**Before**
**After**

upgrade Docker base image from `python:3.12.3-alpine3.18` to `python:3.12.3-alpine3.20`

---

grafana-plugin/src/containers/ApiTokenSettings/ApiTokenForm.tsx
grafana-plugin/src/models/plugin/plugin.ts
grafana-plugin/src/network/oncall-api/api.types.d.ts
grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.module.css
grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.tsx
grafana-plugin/src/state/rootBaseStore/RootBaseStore.ts
grafana-plugin/src/types.ts

- show api_url from GET /status endpoint on settings page
- refactor MainSettings to be functional component
https://raintank-corp.slack.com/archives/C0713BYQB0W/p1724249719392329

fix: show api url in main settings

---

engine/apps/grafana_plugin/tests/test_sync.py

See https://github.com/grafana/oncall/actions/runs/10513279782/job/29128524241

Fix flaky test depending on DB ordering

---

engine/apps/grafana_plugin/tasks/sync_v2.py
engine/apps/grafana_plugin/tests/test_sync_v2.py

Add logging for when we skip an organization for sync if it is missing its api token.

Add logging for invalid api_tokens during sync

---

engine/apps/grafana_plugin/helpers/gcom.py
engine/apps/grafana_plugin/tests/test_gcom.py

Fixes organization api_token not being updated when it differs from what is stored in the DB.

Fix api_token not being updated

---

engine/apps/grafana_plugin/helpers/gcom.py
engine/apps/grafana_plugin/tests/test_gcom.py

Skip updating stored api_token for Grafana if it does not look like one.  Note: Exact format is not checked (prefix) since there are some differences between versions for what API tokens might look like and this should tolerate those differences.

Add more validation when updating api_token

---

engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/helpers/gcom.py
engine/apps/grafana_plugin/tasks/sync_v2.py
engine/apps/grafana_plugin/tests/test_sync_v2.py

Moves validate_grafana_token_format to GrafanaAPIClient, use it in sync_v2 to improve logging and skip requests that would not work.

Move validate_grafana_token_format to common location, use in sync_v2

---

engine/apps/grafana_plugin/helpers/gcom.py
engine/apps/grafana_plugin/tests/test_gcom.py

Fix issue related to [logs](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%2257p%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22amixr-prod%5C%22,%20cluster%3D%5C%22prod-us-central-0%5C%22,%20job%3D%5C%22amixr-prod%2Famixr-engine%5C%22%7D%20%7C%3D%20%5C%22user_management_organization.user_management_organization_stack_id_org_id_727b4929_uniq%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)
(check for existing org using the unique DB index)

Update org creation to use DB uniqueness constraint

---

grafana-plugin/pkg/plugin/settings.go
grafana-plugin/pkg/plugin/users.go

- Fixes ID being used to lookup user permissions during sync.
- Reduce level on overly chatty log message

Fix incorrect IDs being used to lookup user permissions during sync

---

engine/apps/mobile_app/tests/test_mobile_app_gateway.py
engine/apps/mobile_app/views.py

Related to some issues we have noticed in our logs ([example](https://ops.grafana-ops.net/goto/8sa28TqIR?orgId=1)).
Also make sure unexpected responses are logged too.

Check for incident enabled before making mobile app request

---

grafana-plugin/src/components/CardButton/CardButton.tsx

fix alert group card layout
[Related to [issue link here]](https://raintank-corp.slack.com/archives/C06K1MQ07GS/p1724882302489259)

fix: fix alert group card layout

---

engine/apps/public_api/views/users.py

Avoid checking all schedules in an organization when filtering user events during export.
This should help with some slow requests we are noticing.

Improve schedule filters before generating user calendar export

---

.github/workflows/on-release-published.yml

related to https://github.com/grafana/oncall-private/issues/2881
use the same token to both sign and publish plugin

Use cloud access policy to publish plugin to grafana.com

---

engine/apps/grafana_plugin/serializers/sync_data.py
engine/apps/grafana_plugin/tests/test_sync_v2.py

- Teams do not require valid email addresses to be sync'd
- AvatarURL can be blank

Relax sync team serializer validation to match underlying model

---

.github/actions/install-frontend-dependencies/action.yml

- support running install-frontend-dependency from subdirectory (used by oncall-private)
https://raintank-corp.slack.com/archives/C06K1MQ07GS/p1725445756941869

fix: support running install-frontend-dependency from subdirectory

---

engine/config_integrations/alertmanager.py
engine/config_integrations/grafana_alerting.py

Changing source link default template to the link to the first alert in the group `alerts[0].generatorURL`. `externalURL` as a backlink to the Alertmanager, is too general

Change default source link template for alertmanager

---

helm/oncall/Chart.yaml

Can we update this dependency? The current version of Redis has CVE.

Bump Redis deps

---

docs/sources/configure/integrations/references/slack/index.md

This PR hides the IRM Slack doc currently located in the OnCall TOC to support moving this content to the top-level IRM docs navigation. This will improve visibility and clarify that this is an IRM feature, not just an OnCall feature. 
Rather than removing the document altogether, we can hide it so that the URL is still active for anyone who is directed to it. This also gives us transition time to update the links in the product and elsewhere. 
This update addresses our initial feedback on the Unified IRM Slack app. The goal of this change is to reduce confusion around migration and document location to ease the transition to the new app.
Replacement docs can be found here:
https://github.com/grafana/website/pull/21657

docs: hide slack doc from toc

---

engine/apps/alerts/incident_appearance/templaters/web_templater.py
engine/apps/alerts/tests/test_alert_group_renderer.py

Removed escaping of html in web template to fix issue where <a> links were not being detected correctly when post processing the web template.
https://github.com/grafana/support-escalations/issues/12412

Fix <a> link escaping in web template

---

engine/apps/alerts/incident_appearance/templaters/web_templater.py
engine/apps/alerts/tests/test_alert_group_renderer.py

Reverts grafana/oncall#5019
Investigating alternatives, although we have a sanitize function called on the UI side we probably don't want to allow other html.

Revert "Fix <a> link escaping in web template"

---

grafana-plugin/webpack.config.ts

Always point livereload to localhost. I missed this change when submitting this PR: https://github.com/grafana/oncall/pull/5021

chore: always point livereload to localhost

---

engine/apps/integrations/mixins/ratelimit_mixin.py
engine/apps/integrations/tests/test_ratelimit.py
engine/apps/public_api/tests/test_ratelimit.py
engine/common/api_helpers/custom_rate_scoped_throttler.py
engine/common/api_helpers/custom_ratelimit.py
engine/settings/base.py

Follow up PR for https://github.com/grafana/oncall/pull/5004
Tests haven’t caught a bug, so the method and the tests are fixed

Use dataclass methods in custom ratelimits and fix tests

---

engine/apps/api/serializers/on_call_shifts.py
engine/apps/api/tests/test_oncall_shift.py
engine/apps/public_api/serializers/on_call_shifts.py
engine/apps/public_api/tests/test_on_call_shifts.py
engine/common/api_helpers/custom_fields.py

Adds validation for rolling users param in the shift api
Closes [5041](https://github.com/grafana/oncall/issues/5041)

fix: Add rolling users validation for oncall shift API

---

engine/config_integrations/alertmanager.py
engine/config_integrations/grafana_alerting.py

We recently changed the default template (https://github.com/grafana/oncall/pull/5005) but some alertmanagers may send invalid URLs.
Our fronted has the check for invalid URLs ("he Integration template Source Link is invalid"), but slack does not, so I added this check

Check for invalid urls in slack

---

engine/apps/api/views/alert_group.py

Adds default value for `started_at` filter for `/alertgroups` internal endpoint
Related to https://raintank-corp.slack.com/archives/C06K1MQ07GS/p1727184726971589?thread_ts=1727162658.629509&cid=C06K1MQ07GS

Add default value for `started_at` filter for `/alertgroups` internal endpoint

---

.github/workflows/on-helm-release-pr-merged.yml
helm/oncall/Chart.yaml

- Closes https://github.com/grafana/oncall/issues/5065
- Fixes [failing update Helm repo github workflows](https://github.com/grafana/oncall/actions/workflows/on-helm-release-pr-merged.yml) (due to `secrets. GH_HELM_RELEASE` now seeming to return "Bad credentials")

fix "on helm release pr merged" GitHub Actions workflow

---

docs/sources/oncall-api-reference/schedules.md
docs/sources/oncall-api-reference/teams.md
docs/sources/oncall-api-reference/users.md
engine/apps/public_api/serializers/teams.py
engine/apps/public_api/serializers/users.py
engine/apps/public_api/tests/test_teams.py
engine/apps/public_api/tests/test_users.py

- add Grafana IDs to users and teams public API endpoints
- update Schedules public API docs to reflect the fact that [we allow filtering by `team_id`](https://github.com/grafana/oncall/blob/dev/engine/apps/public_api/views/schedules.py#L42)

feat: add Grafana IDs to users and teams public API endpoints

---

.github/workflows/on-release-published.yml

Stop merging Helm release chart PRs as me 🙃 and instead use the "Grafana IRM App" GitHub App credentials:

chore: merge helm request PRs using the `grafana-irm-app` GitHub App

---

engine/apps/api/permissions.py
engine/apps/api/serializers/user_notification_policy.py
engine/apps/user_management/models/user.py
engine/apps/user_management/tests/test_user.py
engine/common/api_helpers/mixins.py
grafana-plugin/src/plugin.json

**NOTE**: should be merged/released after https://github.com/grafana/irm/pull/183 has been rolled out to most stacks (as that frontend update is what will grant that new RBAC "action" to users whom already have the "OnCall Admin" RBAC role assigned)
tldr; from the comment in the `RBACPermission.Permission.ADMIN` comment in `engine/apps/api/permissions.py`:
> NOTE: this is a bit of a hack for now. See https://github.com/grafana/support-escalations/issues/12625
> Basically when it comes to filtering teams that are configured to share their resources with
> "Team members and admins", we have no way of knowing, when a user is ACTUALLY an Admin when RBAC is involed.
>
> Example: Take a user with the basic role of None/Editor/Viewer but with the "OnCall Admin" role assigned.
> Without this RBAC …

fix: address RBAC Admin issue

---

dev/helm-local.yml
grafana-plugin/jest.setup.ts
grafana-plugin/src/PluginPage.tsx
grafana-plugin/src/containers/Alerts/Alerts.tsx
grafana-plugin/src/containers/DefaultPageLayout/DefaultPageLayout.tsx
grafana-plugin/src/containers/MobileAppConnection/MobileAppConnection.test.tsx
grafana-plugin/src/containers/RotationForm/RotationForm.helpers.ts
grafana-plugin/src/navbar/Header/Header.tsx
grafana-plugin/src/navbar/LegacyNavHeading.tsx
grafana-plugin/src/pages/pages.tsx
grafana-plugin/src/pages/settings/SettingsPage.tsx
grafana-plugin/src/pages/settings/tabs/MainSettings/MainSettings.tsx
grafana-plugin/src/plugin/GrafanaPluginRootPage.helpers.tsx
grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx

- removes references to `topnav`
- `topnav` was default enabled in grafana v9.5
- we intend to remove the toggle soon™️ 

Chore: Remove `topnav` references

---

engine/apps/alerts/tests/test_paging.py
engine/apps/api/tests/test_schedules.py
engine/apps/mobile_app/tests/tasks/test_new_shift_swap_request.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py
engine/apps/slack/tests/test_scenario_steps/test_manage_responders.py
engine/apps/slack/tests/test_scenario_steps/test_paging.py

Related to https://github.com/grafana/oncall/issues/4936
Cached final schedule keeps a (now - 15d, now + 6m) window representation of a schedule (this representation always use users' username; it will un-relate users that are not anymore associated to a schedule).

Update schedule related users to use cached final representation

---

engine/settings/base.py

Makes SLOW_THRESHOLD_SECONDS configurable from environment variable.  This is to support separate metrics pods as having a different definition of slow request (10s)

Make threshold for logging slow requests configurable

---

engine/apps/slack/models/slack_message.py

Truncates text for slack message to avoid this error:
```
File "/usr/local/lib/python3.12/site-packages/slack_sdk/web/slack_response.py", line 199, in validate
raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/chat.postMessage)
The server responded with: {'ok': False, 'error': 'invalid_blocks', 'errors': ['failed to match all allowed schemas [json-pointer:/blocks/0/text]', 'must be less than 3001 characters [json-pointer:/blocks/0/text/text]'], 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/blocks/0/text]', '[ERROR] must be less than 3001 characters [json-pointer:/blocks/0/text/text]']}}
```
show up in the …

Truncate slack block text so it is not rejected by slack API

---

engine/apps/alerts/models/alert_group_log_record.py
engine/apps/alerts/tests/test_alert_group_log_record.py

Reworked https://github.com/grafana/oncall/pull/5112 (post-revert)

Include link information for objects referenced in alert group timeline

---

engine/apps/public_api/tests/test_resolution_notes.py
engine/apps/public_api/views/resolution_notes.py

Reduces the number of `chat.update` Slack API calls when a resolution note is updated with the same text.

fix: don't update Slack messages if resolution note text not changed

---

engine/apps/grafana_plugin/tests/test_install_v2.py
engine/apps/grafana_plugin/views/install_v2.py

Fixes incorrect encoding when SyncException contains one of the predefined dataclass errors in install_v2 endpoint.
Related to #5124 

Fix error encoding on install_v2 endpoint

---

engine/apps/metrics_exporter/helpers.py
engine/settings/base.py

Limits organizations that a metrics exporter is responsible for.  As more organizations are added it becomes more difficult for the exporter to deliver metrics within the scrape timeout. This would let us use the settings to divide up the organizations between multiple exporters.

Split up organizations across metrics exporters

---

engine/settings/base.py

Adds a separate env variable for logging headers and sets it to false by default.

LOG_REQUEST_HEADERS

---

engine/apps/alerts/models/alert.py
engine/apps/alerts/models/alert_group.py
engine/apps/user_management/tests/test_organization.py

fix: no longer set `AlertGroup.resolved_by_alert`

---

engine/apps/alerts/tasks/notify_user.py
engine/apps/alerts/tests/test_notify_user.py

Sometimes a task is queued and scheduled for later (or for a retry too), but the alert group is resolved by then. Skip notification in that case.

Skip user notification if alert group is already resolved

---

docs/sources/configure/jinja2-templating/advanced-templates/index.md
engine/common/jinja_templater/filters.py
engine/common/jinja_templater/jinja_template_env.py
engine/common/tests/test_apply_jinja_template.py
grafana-plugin/src/components/CheatSheet/CheatSheet.config.ts

If an OnCall template needs to contain a date relative to a date in the alert response, currently there is no way for the template to add or subtract time from a parsed date.
This PR adds a function that allows a time-window (e.g., 1s, 5m, 6h, 7d, 2w) to be converted into a Python timedelta, which can then be added or subtracted from a datetime. An example usage might be:
```
{% set delta = alert.timeWindow | timedeltaparse %}
{% set time = alert.startsAt | iso8601_to_time - delta | datetimeformat('%s') %}
```

feat: add `timedeltaparse` function to the jinja template

---

engine/apps/grafana_plugin/helpers/client.py
engine/apps/grafana_plugin/serializers/sync_data.py
engine/apps/grafana_plugin/sync_data.py
engine/apps/grafana_plugin/tasks/sync_v2.py
engine/apps/grafana_plugin/tests/test_sync_v2.py
engine/apps/user_management/models/organization.py
engine/apps/user_management/sync.py
engine/apps/user_management/tests/test_organization.py
engine/apps/user_management/tests/test_sync.py

Will start persisting the `organization.is_grafana_irm_enabled` flag from the backend plugin's sync data that is sent to the oncall backend. The implications of this are that when `is_grafana_irm_enabled` is set to True, we will:
- start using `grafana-irm-app` prefixed RBAC permissions (RBAC permissions for `grafana-irm-app`, as well as `grafana-oncall-app`, are already being synced to the OnCall backend since https://github.com/grafana/irm/pull/200 was merged/deployed)
- start building UI URLs w/ `grafana-irm-app` instead of `grafana-oncall-app`
Closes https://github.com/grafana/irm/issues/242

feat: persist `is_grafana_irm_enabled` from backend plugin sync data

---

engine/apps/public_api/serializers/escalation_chains.py
engine/apps/public_api/serializers/escalation_policies.py
engine/apps/public_api/serializers/integrations.py
engine/apps/public_api/serializers/on_call_shifts.py
engine/apps/public_api/serializers/routes.py
engine/apps/public_api/serializers/schedules_base.py
engine/apps/public_api/serializers/schedules_web.py
engine/apps/public_api/serializers/webhooks.py
engine/apps/public_api/views/escalation_chains.py
engine/apps/public_api/views/integrations.py
engine/apps/public_api/views/routes.py
engine/apps/public_api/views/schedules.py
engine/apps/public_api/views/webhooks.py
engine/apps/schedules/ical_utils.py

- Add/update eager loading for public API serializers
- Use cached final schedule to get currently on-call users

Minor optimizations for public API endpoints

---

engine/apps/api/serializers/schedule_base.py
engine/apps/public_api/serializers/schedules_base.py

Undo one of the changes from https://github.com/grafana/oncall/pull/5172 (since it seems to make the schedules endpoint a bit worse; OTOH, other changes improved latency). Eventually we may consider using the cached on-call users information instead.

Undo schedules using ical cached final data

---

engine/common/incident_api/client.py
engine/common/incident_api/tests/test_client.py

Handle some (unexpected) incident request errors more gracefully.

Handle incident client general request errors

---

engine/apps/social_auth/backends.py

Tested on dev (by manually changing the sign in URL in oauth flow). All works correctly

Remove deprecated identify slack scope

---

tools/migrators/README.md
tools/migrators/lib/pagerduty/resources/notification_rules.py
tools/migrators/lib/tests/pagerduty/test_migrate_notification_rules.py

Makes so that user notification rules from PD are migrated into both "default" and "important" OnCall user notification rules instead of just "default".
Before this PR:
After this PR:
Related to [Slack thread](https://raintank-corp.slack.com/archives/C07HMCM59TK/p1730306579122409?thread_ts=1730303532.031559&cid=C07HMCM59TK)

PD migrator: populate important OnCall notification rules

---

engine/apps/api/serializers/organization.py
engine/apps/api/tests/test_organization.py

Backend portion of https://github.com/grafana/oncall-mobile-app/issues/1021

feat: add `grafana_irm_enabled` to `GET /organization` endpoint response

---

engine/apps/alerts/migrations/0063_migrate_channelfilter_slack_channel_id.py
engine/apps/alerts/migrations/0064_migrate_resolutionnoteslackmessage_slack_channel_id.py
engine/apps/schedules/migrations/0019_auto_20241021_1735.py
engine/apps/user_management/migrations/0026_auto_20241017_1919.py

After deploying [`r439-v1.12.0`](https://github.com/grafana/oncall-private/releases/tag/r439-v1.12.0) to staging, I noticed that the migrations were taking a long time, and caused some wonkiness (see https://raintank-corp.slack.com/archives/C08063QES5N). 
```bash
Apply all migrations: [redacted secret grafana-admin-creds:admin-user], alerts, auth, auth_token, base, contenttypes, email, exotel, fcm_django, google, heartbeat, labels, mobile_app, oss_installation, phone_notifications, schedules, sessions, slack, social_django, telegram, twilioapp, user_management, webhooks, zvonok
Running migrations:
source=engine:app google_trace_id=none logger=apps.alerts.migrations.0063_migrate_channelfilter_slack_channel_id Starting migration to populate slack_channel field.
source=engine:app …
```

fix: improve performance of recent `SlackChannel` related migrations

---

engine/apps/slack/scenarios/alertgroup_timeline.py

Limit length of text in block being posted to slack when showing alert group timeline.

Limit slack block text length when rendering alert group timeline

---

.github/workflows/linting-and-tests.yml
Tiltfile
dev/helm-local.yml
helm/oncall/values.yaml

Disable accessControlOnCall for Grafana 11.3

fix: disable accessControlOnCall for Grafana 11.3

---

docker-compose-developer.yml
docker-compose-mysql-rabbitmq.yml
docker-compose.yml

Disable accessControlOnCall for Grafana 11.3 in docker compose
Similar to https://github.com/grafana/oncall/pull/5245

fix: disable accessControlonCall for Grafana 11.3 in docker compose

---

engine/apps/mobile_app/demo_push.py
engine/apps/mobile_app/tasks/going_oncall_notification.py
engine/apps/mobile_app/tasks/new_alert_group.py
engine/apps/mobile_app/tasks/new_shift_swap_request.py
engine/apps/mobile_app/tests/tasks/test_going_oncall_notification.py
engine/apps/mobile_app/tests/tasks/test_new_shift_swap_request.py
engine/apps/mobile_app/tests/test_demo_push.py

We noticed that the backend was adding the stack name to the notification title only on Android. 
We thought it makes sense to add the stack name only if the user has more than 1 stack connected, but that's not doable right now since the backend doesn't know how many stacks are connected in the app.
Also we took a look at the analytics for the app and basically 95% of the users have only 1 stack connected.
This pr removes the stack name from the notifications title.
If in the future we think it makes sense to add it conditionally based on the number of stacks we can open another pr, but given the very little amount of users with more than 1 stack I think this is not needed.

remove add_stack_slug_to_message_title utility from push notification titles

---

engine/apps/email/inbound.py
engine/apps/email/tests/test_inbound_email.py

follow up to https://github.com/grafana/oncall/pull/5259:
* Auto confirm SNS subsriptions for ESP `amazon_ses_validated`
* Add a couple of tests for SNS message validation (try with wrong SNS topic ARN, try with wrong singature)

Inbound email improvements (continued)

---

.github/workflows/linting-and-tests.yml
docker-compose-developer.yml
docker-compose-mysql-rabbitmq.yml
docker-compose.yml

Updating docker image for Redis to latest version on 7.0 branch
* (CVE-2022-35977) Integer overflow in the Redis SETRANGE and SORT/SORT_RO
commands can drive Redis to OOM panic
* (CVE-2023-22458) Integer overflow in the Redis HRANDFIELD and ZRANDMEMBER
commands can lead to denial-of-service
* (CVE-2023-25155) Specially crafted SRANDMEMBER, ZRANDMEMBER, and HRANDFIELD
commands can trigger an integer overflow, resulting in a runtime assertion
and termination of the Redis server process.
* (CVE-2022-36021) String matching commands (like SCAN or KEYS) with a specially
crafted pattern to trigger a denial-of-service attack on Redis, causing it to
hang and consume 100% CPU time.
* (CVE-2023-28425) Specially crafted MSETNX command can lead to assertion and denial-of-service
* (CVE-2023-28856) …

security: Update docker redis image to v7.0.15

---

engine/apps/alerts/incident_log_builder/incident_log_builder.py
engine/apps/alerts/tasks/notify_user.py
engine/apps/alerts/tests/test_notify_user.py

Changes UserNotificationPolicyLogRecord to success when slack_prevent_posting is set as the user has already been notified in slack or another method in their personal notification preferences.  These entries have also been filtered out of the alert group history timeline as they were causing confusion to users thinking notifications failed when in fact they had already been sent.
https://github.com/grafana/support-escalations/issues/13236

fix: remove notification failure policy log record when prevent posting is set

---

engine/apps/schedules/ical_events/adapter/amixr_recurring_ical_events_adapter.py
engine/apps/schedules/tests/test_on_call_schedule.py

This older version of recurring_ical_events does not call the pytz .normalize() function, which can cause some invalid datetime objects to return when a DST swap happens. For example: Nov 3, 2024 9:00 AM CDT instead of the correct 8:00 AM CST). By calling tz.normalize on the end date and checking if the time zone information changed, we can detect when DST starts/stops and adjust the end date accordingly.
| | DST stopping on November 3, 2024: | DST starting on March 9, 2024 |
|-|-----------------------------------------|-----------------------------------|
| Before | ![image](https://github.com/user-attachments/assets/933bce80-9b6a-475b-88f2-6356d0e3a6fd) | ![image](https://github.com/user-attachments/assets/264b816f-6f40-4f14-bbc0-1d03f7b74ac4)
| After | …

Fix issue with DST starting/ending causing overlaps/gaps

---

engine/apps/public_api/serializers/resolution_notes.py
engine/apps/public_api/tests/test_resolution_notes.py

Related to https://raintank-corp.slack.com/archives/C06K1MQ07GS/p1732179451119299?thread_ts=1731693276.392569&cid=C06K1MQ07GS

fix: check for service account user on public API resolution note

---

engine/apps/alerts/migrations/0063_migrate_channelfilter_slack_channel_id.py
engine/apps/alerts/migrations/0064_migrate_resolutionnoteslackmessage_slack_channel_id.py
engine/apps/schedules/migrations/0019_auto_20241021_1735.py
engine/apps/user_management/migrations/0026_auto_20241017_1919.py

Fixes https://github.com/grafana/oncall/issues/5244#issuecomment-2493688544

fix: patch data migration scripts for non-MySQL databases

---

docs/sources/configure/jinja2-templating/advanced-templates/index.md
engine/common/jinja_templater/filters.py
engine/common/jinja_templater/jinja_template_env.py
engine/common/tests/test_apply_jinja_template.py

Related to https://github.com/grafana/support-escalations/issues/13670
Given a payload like this:
```
{  
"Sometime": "1730893740"  
}
```
the following template expression:
`{{ payload.Sometime | int | timestamp_to_datetime }}`
will render as:
`2024-11-06 11:49:00`

feat: add timestamp_to_datetime jinja template filter

---

engine/apps/auth_token/auth.py
engine/apps/auth_token/grafana/grafana_auth_token.py
engine/apps/auth_token/tests/helpers.py
engine/apps/auth_token/tests/test_grafana_auth.py
engine/apps/auth_token/tests/test_plugin_auth.py
engine/apps/grafana_plugin/helpers/client.py
engine/apps/public_api/tests/test_alert_groups.py
engine/apps/public_api/tests/test_integrations.py
engine/apps/public_api/tests/test_resolution_notes.py

Related to https://github.com/grafana/oncall-private/issues/2826
Related to https://github.com/grafana/irm/pull/459
Allow org sync requests from service account users. Also trigger a sync during public API requests if the org wasn't yet setup.

feat: add service account checks in plugin auth

---

engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/mobile_app/alert_rendering.py

Related to https://github.com/grafana/support-escalations/issues/13689

fix: mobile app template preview use dynamic value

---

engine/apps/public_api/serializers/webhooks.py
engine/apps/public_api/tests/test_webhooks.py
engine/apps/user_management/models/service_account.py

There is no user to be set when creating a webhook via the public API if authenticated using service account tokens (insight logs will still keep track of the service account information behind the request).

fix: service accounts creating webhooks through API

---

engine/apps/alerts/models/alert_group.py
engine/apps/alerts/models/channel_filter.py
engine/apps/alerts/tests/test_alert_group.py
engine/apps/alerts/tests/test_channel_filter.py
engine/apps/alerts/tests/test_notify_all.py
engine/apps/slack/scenarios/distribute_alerts.py
engine/apps/slack/tasks.py
engine/apps/slack/tests/scenario_steps/test_distribute_alerts.py
engine/apps/slack/tests/test_installation.py

Fixes https://github.com/grafana/irm/issues/469

fix: patch slack ID reference issue

---

engine/apps/public_api/tests/test_escalation_chain.py
engine/apps/user_management/models/service_account.py

Related to https://github.com/grafana/oncall-private/issues/2826

fix: allow service account requests to access organization teams

---

engine/apps/email/inbound.py
engine/tox.ini

Adds some logging for inbound email + comment on why I disabled `pytest-socket` in a [recent PR](https://github.com/grafana/oncall/pull/5328)

Inbound email additional logging

---

engine/apps/auth_token/auth.py
engine/apps/auth_token/tests/test_grafana_auth.py

Ignore setup organization response (for now, since it can return a 400 when a sync is/was recently in progress) and base response on organization being available or not instead.

chore: update service account token auth organization setup check

---

engine/apps/auth_token/auth.py
engine/apps/auth_token/tests/test_plugin_auth.py

External service accounts do not have a role set so async triggered periodic org syncs were rejected. Improving role/perm check in a later PR instead (restriction wasn't originally there).

fix: remove service account role check on sync requests

---

docs/sources/set-up/open-source/index.md

It explains how to connect to the cloud if you are outside of the US -- I couldn't find this information anywhere and I was stuck for several months until the user who opened https://github.com/grafana/oncall/issues/5214 solved their own problem.
https://community.grafana.com/t/trying-to-connect-selfhosted-grafana-to-cloud-oncall/129985
https://github.com/grafana/oncall/issues/5214

Explain setting the GRAFANA_CLOUD_ONCALL_API_URL

---

engine/apps/alerts/models/alert_receive_channel.py
engine/apps/api/serializers/alert_receive_channel.py
engine/apps/api/tests/test_alert_receive_channel.py
engine/apps/labels/alert_group_labels.py
engine/apps/labels/tests/test_alert_group.py
engine/apps/labels/tests/test_labels.py
engine/apps/labels/tests/test_labels_cache.py
engine/conftest.py

1. Fix https://github.com/grafana/irm/issues/530 - applied same validation logic as for multi-label extraction template to dynamic label.  Actual fix is here - https://github.com/grafana/oncall/pull/5363/files#diff-58657df0f1ff9a8578a14504f1c6cfd240e45e084171c5bbeb09d975c3ec72ddR74
2. Some minor refactorings over static/dynamic/integration label naming. This work should be continued in separate PR.

Fix dynamic label template validation

---

engine/apps/auth_token/auth.py
engine/apps/auth_token/tests/test_grafana_auth.py

Related to https://github.com/grafana/oncall-private/issues/2826
When Terraform triggers multiple requests and org needs to be synced in OnCall, the first request will wait for sync to complete but others will get an immediate response, before a 403, with these changes a 429 indicating to retry (Terraform [client](https://github.com/grafana/amixr-api-go-client/blob/main/client.go#L310) will handle the response and perform a retry).

fix: return a throttled response if org is being synced for the first time during auth

---

engine/apps/schedules/ical_utils.py
engine/apps/schedules/models/custom_on_call_shift.py
engine/apps/schedules/tasks/__init__.py
engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
engine/apps/schedules/tests/test_notify_about_empty_shifts_in_schedule.py
engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py
engine/apps/schedules/tests/test_on_call_schedule.py
engine/settings/celery_task_routes.py

Related to https://github.com/grafana/oncall-private/issues/2950
- Represent missing users in schedule events (so they are displayed in the web UI)
- Fix schedule checks for gaps/empty shifts so they send notifications

fix: update missing users / empty shifts check

---

.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml

Use a centralized composite action that uses GitHub App authentication to publish documentation.
The organization secrets used in the current workflows have expired.

Update publishing workflows to use GitHub App authentication 

---

engine/apps/alerts/migrations/0073_update_direct_paging_integration_non_default_routes.py

Patches some issues experienced on dev related to https://github.com/grafana/oncall/pull/5397. Previous migration was running into the following:
```bash
File "/usr/local/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
packet.raise_for_error()
File "/usr/local/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
err.raise_mysql_exception(self._data)
File "/usr/local/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
raise errorclass(errno, errval)
django.db.utils.OperationalError: (1093, "You can't specify target table 'alerts_channelfilter' for update in FROM clause")
```

fix: patch direct paging routes migration

---

.github/workflows/publish-technical-documentation-release.yml

Without this, the action assumes there is a release branch that a tag is made on because that is common to most other Grafana repositories. Those repositories maintain a long-lived release branch to facilitate backports to documentation and code.
Since grafana/oncall doesn't follow this pattern, it doesn't make sense to try and discover the matching release branch. That action behavior is disabled by the `tags_only: true` setting.

Use tags only workflow behavior

---

engine/apps/labels/models.py
engine/apps/labels/tests/test_labels_cache.py

Handle JSONDecodeError on getting label key by name

Fix getting label by name

---

engine/apps/api/serializers/schedule_base.py
engine/apps/api/serializers/schedule_calendar.py
engine/apps/api/serializers/schedule_ical.py
engine/apps/api/serializers/schedule_web.py
engine/apps/api/views/schedule.py
engine/apps/schedules/constants.py
engine/apps/schedules/models/on_call_schedule.py
engine/apps/schedules/tasks/check_gaps_and_empty_shifts.py
engine/apps/schedules/tasks/notify_about_empty_shifts_in_schedule.py
engine/apps/schedules/tasks/notify_about_gaps_in_schedule.py
engine/apps/schedules/tests/test_check_gaps_and_empty_shifts.py
engine/apps/schedules/tests/test_notify_about_gaps_in_schedule.py

Related to https://github.com/grafana/oncall-private/issues/2994
- Extend gaps/empty shift checks to consider 30 days (customizable via param, eventually make it customizable per schedule?); ie. every week (per beat schedule), check the schedule next 30 days
- Trigger checks via async task on schedule API updates (instead of a sync call)
- Update notifications wording / link to schedule

chore: update schedule checks notification period and improve wording

---

engine/apps/api/tests/test_alert_group.py
engine/apps/api/views/alert_group.py
engine/apps/grafana_plugin/tests/test_ui_url_builder.py
engine/apps/grafana_plugin/ui_url_builder.py
engine/common/constants/plugin_ids.py

Related to https://github.com/grafana/oncall-private/issues/2977
e.g.
`GET /api/plugins/grafana-oncall-app/resources/alertgroups/filter_affected_services?service=service-a&service=service-b`
```
[
{"name": "service-a",
"service_url": "http://localhost:3000/a/grafana-slo-app/service/service-a",
"alert_groups_url": "http://localhost:3000/a/grafana-oncall-app/alert-groups?status=0&status=1&started_at=now-7d_now&label=service_name:service-a"}
]
```

feat: add filter affected services internal endpoint

---

grafana-plugin/src/containers/UserSettings/parts/UserSettingsParts.tsx
grafana-plugin/src/containers/UserSettings/parts/tabs/PersonalWebhookInfo/PersonalWebhookInfo.tsx

Restyles the Webhook connection UI to match [the designs in Figma](https://www.figma.com/design/sJ4RvHvnUq6AZAiHYYiB5j/Grafana-OnCall?node-id=12993-188431&t=6h84zanlHB0agXlX-1)
Related to https://github.com/grafana/irm/issues/332

feat: restyled UI to match Figma

---

.github/workflows/on-release-published.yml

related to https://github.com/grafana/irm/issues/455, the secret was populated as part of https://github.com/grafana/deployment_tools/pull/221022

Use a different GH secret to sign plugin

---

grafana-plugin/src/containers/UserSettings/parts/tabs/PhoneVerification/PhoneVerification.tsx
helm/oncall/Chart.yaml

Although recaptcha verification is disabled by default on the backend for OSS installs, the plugin was still making use of the site key and trying to load recaptcha.  As that recaptcha site was removed this no longer works.  The updated plugin code will skip recaptcha verification if it does not have a site key set.
Related to #5449

fix: disable recaptcha when site key is not set

---

tools/migrators/lib/pagerduty/resources/services.py
tools/migrators/lib/tests/pagerduty/resources/test_services.py

This PR applies the diff described in https://github.com/grafana/irm/issues/1863 to the PagerDuty migrator tool.
Specifically, it:
- Fixes the target type check for user references in service filtering
- Ensures escalation policies are included in the PagerDuty API request
- Corrects the logging output for service migration errors

fix(pagerduty): apply several small PagerDuty migrator fixes

---

grafana-plugin/src/components/AlertTemplates/CommonAlertTemplatesForm.config.ts

Spelling fix. Noticed during a demo that cheatsheet was misspelled.

chore: fix spelling in CommonAlertTemplatesForm.config.ts

---

.github/workflows/on-pull-requests.yml
.github/workflows/snyk-security-scan.yml

Changes the Snyk Monitoring to use Grafana's [Action](https://github.com/grafana/security-github-actions)
The current setup prevents Snyk from running on forks and blocks contributions because of the `id-token: write` permission

chore: Update snyk monitor scan to use Grafana's GH action
